### ISSUE TITLE
New use case: DNS

### ISSUE THREAD

**Issue by praseodym** [elastic/ecs#10]
A very useful log source is DNS query logging, either from DNS resolver logging or network packet analysis. In my opinion, this is currently not easy to map to the current set of ECS fields.

Packetbeat has [a list of DNS fields](https://www.elastic.co/guide/en/beats/packetbeat/current/exported-fields-dns.html) which could be used as a starting point.

**Comment by ave19** [comment]
Here here!  That's something we're looking into as well.

**Comment by ruflin** [comment]
+1 on adding DNS fields. To get started I would probably add only a subset of the dns fields you linked above, taking the one that are most important for correlating data. Do you want to start a PR to discuss more details or should we discuss fields here?

**Comment by praseodym** [comment]
Sounds like a plan! 

One thing I’m not quite sure about is whether we only want to model DNS query/answer events, or if we should also account for static DNS records (e.g. an imported zonefile). To me it would make sense to be able to correlate across these two kinds of information.

**Comment by ruflin** [comment]
I would start with the dynamic queries as I think that is what normally is part of the events. 

For the zone file are you thinking of a monitoring system that frequently pull it from each DNS server and the you want to compare it with the events?

**Comment by ave19** [comment]
The queries are the most important thing for us.  They are different things, queries vs zone transfers, maybe they should be two kinds of ECS things as well.

**Comment by ruflin** [comment]
Let's discuss directly about the fields that this will involve and how they might differ. This should make the discussion more concrete.

**Comment by megadevx** [comment]
+1 I like this idea

**Comment by megadevx** [comment]
A list of fields I have found useful. 

1. dns.response_code
2. dns.question.name
3. dns.question.type
4. dns.question.class
5. dns.answers
6. dns.answers_count
7. dns.answers.name
8. dns.answers.type
9. dns.answers.class
10. dns.answers.ttl


Now I know these aren't a perfect list, but at least it will get us started.

**Comment by ruflin** [comment]
@megadevx Thanks. Could you complete the above also with some example values for each field? I'm mostly curious on what is in `dns.answers` as it will conflict with `dns.answer.name`. Could we call the first one something else?

**Comment by willemdh** [comment]
Did a quick search in my Infoblox index for all DNS fields. 

Example log:

`<150>Jul 31 08:25:03 5.5.1.51 named[31968]: client 2.2.1.4#2953/key dhcp_updater_default: updating zone '24.10.in-addr.arpa/IN': deleting rrset at '15.2.54.10.in-addr.arpa' PTR`
`<150>Jul 31 08:32:12 5.5.1.51 named[26944]: client 2.2.1.4#12347: received notify for zone 'mextern.local'`

dns_client_ip => Should be renamed to source.ip? (2.2.1.4)
dns_client_key => This is probably Infoblox specific (2953)
dns_client_name => Should be renamed to? (24.10.in-addr.arpa)
dns_client_notify_reverse => Not sure what to do with this
dns_client_notify_zone => Not sure what to do with this (mextern.local)
dns_client_record_ip => Wasn't mapped yet, so I don't found immediate exampe
dns_client_record_type =>(PTR, A, AAAA) should probabaly be splitted between dns.answer.type and dns.question.type?
dns_client_reverse => (15.2.54.10.in-addr.arpa)
dns_client_signer => Probabaly Infoblox specific (dhcp_updater_default)
dns_client_signer_result => (approved)
dns_client_system =>(deleting rrset, adding an rr, signer, received notify for zone) should probabaly renamed to event.type or sth similar
dns_client_zone => (mextern.local)
dns_client_zone_reverse => (24.10.in-addr.arpa)
dns_system => (Zone Update, Zone Transaction, CLient Action, Zone Notify) should probabaly be renamed to event.category or sth similar
dns_zone => (mextern.local)
dns_zone_action => (ADD,DELETE) =>Rename to event.action?
dns_zone_host_ip
dns_zone_host_name
dns_zone_host_reverse
dns_zone_message
dns_zone_metrics
dns_zone_nr
dns_zone_record
dns_zone_reerse
dns_zone_serial
dns_zone_server
dns_zone_soa_serial
dns_zone_transaction_id
dns_zone_user
dns_zone_version

Out of time to add examples for all fields.

**Comment by ruflin** [comment]
I would say best way to move this forward is to start opening a PR with a few fields? We don't need all to get started I think but 5-6 to have the basic structure and we can keep iterating from there.

**Comment by sfd** [comment]
Am I right in thinking the ECS dns schema currently only covers Answer RRs, and not Authority or Additional RRs? Or are you rolling all RR types together under 'answers' and distinguishing only by answers.type?

**Comment by webmat** [comment]
@sfd You're right, currently only Answers are standardized in ECS. However Packetbeat will still give Authority and Additionals via custom fields, if configured to do so.

I'm closing this issue, as we've had the DNS field set for a while. Feel free to open other issues, if you feel anything is still missing.
