### ISSUE TITLE
Rename two field suffixes to ".original"

### ISSUE THREAD

**Issue by webmat** [elastic/ecs#102]
In issue #87 I brought up the inconsistent usage of `.raw` between situations that meant "original/unparsed" and `.raw` meaning the keyword indexing of a multi-field.

We've decided to rename the fields with the unambiguous suffix `.original` instead:

- [ ] `event.raw` => `event.original`
- [ ] `user_agent.raw ` => `user_agent.original`

If you've noticed other field names that could be named `.original` please point them out here. This is a small cleanup I'll do next week.

**Comment by ruflin** [comment]
@webmat As I already was working on the raw fields I opened https://github.com/elastic/ecs/pull/107
