### ISSUE TITLE
Proposal - Add IOC fields

### ISSUE THREAD

**Issue by SHolzhauer** [elastic/ecs#1023]
Proposal for #741

**Summary**  
Adding a new top level field in which IOC information can be stored. The goal of this issue is to get an understanding and agreement on what the structure could be before creating a RFC.

**Motivation**:  
With the [upcoming changes](https://github.com/elastic/kibana/pull/78955) to detections making it possible to match against Threat Intelligence indices it becomes
usefull to have a place in the ECS where IOC's (Threat intelligence) can be stored in a common format.

This proposal focuses on IOC's specifically without taking into account other types of Threat Intel and attempts to capture the required information whilest staying simple to not overly complicate the schema.

**Detailed Design**:  
```json
{
  "ioc": {
    "reference": [
      "https://example.com/"
    ],
    "value": "",
    "type": "",
    "provider": {
      "name": "",
      "creator": "",
      "reference": ""
    },
    "original": ""
  },
  "threat": {},
  "rule": {},
  "vulnerability": {}
}
```

| field | type | description | rationale |
|-------|------|-------------|-----------|
| ioc.reference | array | List of links which provide context on an IOC | Gathering information quickly about an unknown IOC is beneficial. |
| ioc.value | keyword | The IOC value, the "what" on which can be monitored. E.g a hash, domain, ip, etc | A single field in which the IOC value is stored makes searching, correlation and matching a lot easier then having to think `Now in what field would this type of IOC be stored` |
| ioc.type | keyword | A given type of IOC `hash`, `domain`, `ip`, `string`, `unknown` | A categorization field for IOC's, this should be one of the listed values |
| ioc.provider.name | keyword | Name of the provider; e.g `abuse.ch`, `emergingthreats` | An identifier for where the IOC came from. |
| ioc.provider.creator | keyword | Name of who created the IOC | An identifier for who created the IOC originally, some TIP's allow for community contributions and this field can hold the original creator |
| ioc.provider.reference | keyword | Link to the source of the IOC | This makes it possible to quickly find the source of an IOC |
| ioc.original | text | Full text value of the IOC | It can be beneficial to store the full IOC with the original "format" for later | 
| threat | object | Optional addition of [threat](https://www.elastic.co/guide/en/ecs/current/ecs-threat.html) fields | IOC can be directly related to specific threats making them mappable to MITRE ATT&CK. Where possible these fields should be populated so triggered IOC's can be correlated properly by analysts |
| rule | object | Optional addition of [rule](https://www.elastic.co/guide/en/ecs/current/ecs-rule.html) fields | This would allow for relating an IOC to any monitoring rule's |
| vulnerability | object | Optional addition of [vulnerability](https://www.elastic.co/guide/en/ecs/current/ecs-vulnerability.html) fields | This makes it possible to relate an IOC to a vulnerabitly if wanted | 
 
_The `threat`, `vulnerability` and `rule` fields are explicitly mentioned to provide context on how information can be combined_

**Comment by ebeahan** [comment]
Hi @SHolzhauer! A very timely subject as a threat intel RFC is being driven by @shimonmodi and which I believe will include modeling IOCs. @shimonmodi feel free to correct me if that's inaccurate 🙃 

Feel free to take a look and leave feedback: https://github.com/elastic/ecs/pull/986 . This PR is for stage 0 ([RFC stages](https://elastic.github.io/ecs/stages.html) detailed here), but as it progresses through the RFC process, it'll become more fleshed out.

**Comment by shimonmodi** [comment]
@ebeahan - you are absolutely correct, the current proposal includes modeling IOC's by reusing our existing ECS fields for IP, file hashes etc and nesting them under threat.*

@SHolzhauer - thanks for the detailed table. There are definitely a few fields that need to be added to the overall list of ECS threat intel fields. i believe we are converging on having full coverage of threat intel fields - the next steps will be to finalize how we represent it in ECS.

**Comment by ebeahan** [comment]
Linking the Stage 1 PR for Threat Intel: https://github.com/elastic/ecs/pull/1037

**Comment by ebeahan** [comment]
Let's continue the discussion in the latest RFC PR for Threat Intel: https://github.com/elastic/ecs/pull/1037
