### ISSUE TITLE
[docs] Link documentation to the generated index template in Github

### ISSUE THREAD

**Issue by a03nikki** [elastic/ecs#1030]
**Summary**:

It is not easy to discover the index template for ECS from the [documentation](https://www.elastic.co/guide/en/ecs/current/index.html).

**Motivation**:

After going through the work of matching log fields to the ECS fields for a "custom" data sources, the next step is to load an index template into Elasticsearch.  In order to avoid mapping conflicts in Kibana's index patterns, Elasticsearch searches, and unexpected errors in the curated Kibana UIs, the same mappings as other ECS content needs to be used.

**Detailed Design**:

Add a link from the documentation to the generated index template at https://github.com/elastic/ecs/blob/master/generated/elasticsearch/7/template.json.  The only reference to template is at [Elastic Common Schema (ECS) Reference [1.6] » Using ECS » Conventions](https://www.elastic.co/guide/en/ecs/1.6/ecs-conventions.html#_default_elasticsearch_convention_for_indexing_text_fields).

**Comment by ebeahan** [comment]
Thanks @a03nikki for opening the issue and providing this feedback.

I wonder if moving some or all the ECS tooling usage and developer docs to also being on elastic.co could be help with these type of discovery issues, similar to what's done with [Beats](https://www.elastic.co/guide/en/beats/devguide/current/index.html) and [Kibana](https://www.elastic.co/guide/en/kibana/current/development.html).

One item to note - if we start simple by adding the link to the index templates, we'll need to link to the correct version branch depending on which version of the docs we're linking from (e.g. 1.6 links to https://github.com/elastic/ecs/tree/1.6/generated/elasticsearch, 1.5 links to https://github.com/elastic/ecs/tree/1.5/generated/elasticsearch, etc.)
