### ISSUE TITLE
Extend file.pe

### ISSUE THREAD

**Issue by peasead** [elastic/ecs#1039]
**Summary**

The Portable Executable (PE) sub-field, of the `file` top-level fieldset, can be updated to include more file attributes to aid in malware analysis.

Because this is extending an existing sub-field vs. creating a top-level fieldset, I wanted to make an Issue first to determine if this required an RFC.

**Motivation**:

In creating a VirusTotal Filebeat module, we identified opportunities to extend the `file.*` top-level fieldset.

**Detailed Design**:

```
- name: file.pe
  type: group
  fields:
    - name: flattened
      release: beta
      type: group
      fields:
        - name: debug
          default_field: false
          description: >
            Debug information, if present
          type: flattened
        - name: import_list
          default_field: false
          description: >
            List of all imported functions
          type: flattened
        - name: sections
          default_field: false
          description: >
            Data about sections of compiled binary PE
          type: flattened
        - name: resource_details
          default_field: false
          type: flattened
          description: >
            If the PE contains resources, some info about them
        - name: resource_languages
          default_field: false
          type: flattened
          description: >
            Digest of languages found in resources. Key is language (as string) and
            value is how many resources there are having that language (as integer)
        - name: resource_types
          default_field: false
          type: flattened
          description: >
            Digest of resource types. Key is resource type (as string) and value
            is how many resources there are of that specific type (as integer)
        - name: packers
          default_field: false
          type: flattened
          description: >
            Identifies packers used on Windows PE files by several tools and AVs.
            Keys are tool names and values are identified packers, both strings.
            see `file.pe.packers` for merged list of packers from all tools.
      overwrite: true
    - name: exports
      type: keyword
      description: >
        List of symbols exported by PE

    - name: creation_date
      default_field: false
      description: >
        extracted when possible from the file's metadata. Indicates when it was
        built or compiled. It can also be faked by malware creators.
      type: date
    - name: authentihash
      description: >
        Authentihash of the PE file.
      type: keyword
    - name: compile_timestamp
      description: >
        Compile timestamp of the PE file.
      type: date

    - name: packers
      type: keyword
      description: >
        Merged list of all detected packers by all tools used. See `file.pe.flattened.packers`.

    - name: main_icon.hash
      type: group
      description: >
        Hashes of embedded program icon
      fields:
        - name: dhash
          description: >
            Difference Hash for a given PE file.
          type: keyword
          release: beta
        - name: md5
          type: keyword
          description: >
            MD5 hash of raw icon data
          release: beta
    - name: compiler_product_versions
      type: keyword
      description: >
        Version of the compiler.
    - name: rich_pe_header_hash
      type: keyword
      description: >
        Hash of the PE header.
    - name: entry_point
      description: >
        Entry point of the PE file.
      format: string
      type: long
    - name: machine_type
      description: >
        Machine type of the PE file.
      type: keyword
    - name: overlay
      description: >
        Overlay information of the PE file.
      release: beta
      type: group
      fields:
        - name: chi2
          description: >
            Chi2 information of the PE file.
          type: float
        - name: entropy
          description: >
            Entropy information of the PE file.
          type: float
        - name: filetype
          description: >
            Filetype of the PE file.
          type: keyword
        - name: md5
          description: >
            Overlay MD5 hash of the PE file.
          type: keyword
        - name: offset
          description: >
            Offset of the overlay information of the PE file.
          type: long
        - name: size
          description: >
            Size of the PE file.
          format: bytes
          type: long
        - name: rich_pe_header_hash
          description: >
            Hash of the header for the PE file.
          type: keyword
```

**Comment by peasead** [comment]
cc @dcode @devonakerr

**Comment by andrewstucki** [comment]
This seems extensive enough where I would imagine that it'd be worth creating an RFC for to hash out the details, in case you wanted this in a slightly easier to read format with the most important details:

| Name | Type | Description |
| ---- | ---- | ----------- |
| file.pe.authentihash | keyword | Authentihash of the PE file. |
| file.pe.compile_timestamp | date | Compile timestamp of the PE file. |
| file.pe.compiler_product_versions | keyword | Version of the compiler. |
| file.pe.creation_date | date | Extracted when possible from the file's metadata. Indicates when it was built or compiled. It can also be faked by malware creators. |
| file.pe.entry_point | long | Entry point of the PE file. |
| file.pe.exports | keyword | List of symbols exported by PE |
| file.pe.flattened.debug | flattened | Debug information, if present |
| file.pe.flattened.import_list | flattened | List of all imported functions |
| file.pe.flattened.sections | flattened | Data about sections of compiled binary PE |
| file.pe.flattened.resource_details | flattened | If the PE contains resources, some info about them |
| file.pe.flattened.resource_languages | flattened | Digest of languages found in resources. Key is language (as string) and value is how many resources there are having that language (as integer) |
| file.pe.flattened.resource_types | flattened | Digest of resource types. Key is resource type (as string) and value is how many resources there are of that specific type (as integer) |
| file.pe.flattened.packers | flattened | Identifies packers used on Windows PE files by several tools and AVs. Keys are tool names and values are identified packers, both strings. See `file.pe.packers` for merged list of packers from all tools. |
| file.pe.machine_type | keyword | Machine type of the PE file. |
| file.pe.main_icon.hash.dhash | keyword | Difference Hash for a given PE file. |
| file.pe.main_icon.hash.md5 | keyword | MD5 hash of raw icon data |
| file.pe.overlay.chi2 | float | Chi2 information of the PE file. |
| file.pe.overlay.entropy | float | Entropy information of the PE file. |
| file.pe.overlay.filetype | keyword | Filetype of the PE file. |
| file.pe.overlay.md5 | keyword | Overlay MD5 hash of the PE file. |
| file.pe.overlay.offset | long | Offset of the overlay information of the PE file. |
| file.pe.overlay.size | long | Size of the PE file. |
| file.pe.overlay.rich_pe_header_hash | keyword | Hash of the header for the PE file. |
| file.pe.packers | keyword | Merged list of all detected packers by all tools used. See `file.pe.flattened.packers`. |
| file.pe.rich_pe_header_hash | keyword | Hash of the PE header. |
