### ISSUE TITLE
network.iana_number as type long

### ISSUE THREAD

**Issue by wowditi** [elastic/ecs#1054]
**Summary**

According to the ECS field reference https://www.elastic.co/guide/en/ecs/current/ecs-network.html the network.iana_number field has as type keyword, which is a strange type for a field which has number in its name. I believe this should have the type long instead. 

**Motivation**:

Simply noticed a strange type while going through our own index types to try and match them to the ECS.

**Detailed Design**:

The field name is: network.iana_number
An example value is: 6
The appropriate data type is: long
I suspect there are already tests included for this variable since it is not new. 

<br>
This is my first time opening an issue here so I hope I've provided all the necessary information. 

Regards,
Niels

**Comment by ebeahan** [comment]
Thanks for opening the issue @wowditi. 

While fields for numeric identifiers, like the IANA protocol number, contain integer values, `keyword` is often the better data type to use. Elasticsearch optimizes numeric field types for `range` queries and math operations. Many identifiers, such as IANA protocol numbers, are rarely used in `range` queries or with math operators.

However, identifiers are frequently searched using term-level queries. Term query searches on `keyword` fields are usually faster than `term` searches on numeric fields, so there's a performance gain. Keyword is also more forgiving if, for any reason, a data source starts populating the field with a non-integer value.

For these reasons, we'll plan on leaving the `network.iana_number` field as `keyword`.
