### ISSUE TITLE
Logstash User Agent Filter vs. ECS Fields

### ISSUE THREAD

**Issue by ave19** [elastic/ecs#112]
Just a place holder for future discussion.  I feel like the plugin doesn't parse out what we need to fill in the `user_agent` information and maybe it should?  Obviously, that's a battle for another time, though.

**Comment by ruflin** [comment]
Good point. user_agent was initially fully inspired by what the ingest processor in Elasticsearch does but I'm not too happy anymore with the object. We definitively should look into what LS does.

**Comment by webmat** [comment]
This will be resolved by https://github.com/logstash-plugins/logstash-filter-useragent/issues/66

See also https://github.com/logstash-plugins/logstash-filter-useragent/issues/66 and https://github.com/elastic/logstash/issues/11635 for a higher level overview of what's coming in Logstash.
