### ISSUE TITLE
Document various options to adding non-ECS fields to a stream that wants to conform to ECS

### ISSUE THREAD

**Issue by webmat** [elastic/ecs#114]
There have been some discussions about how to add non-ECS fields to a stream that users want to conform to ECS. ECS being a general purpose schema, this situation will happen often.

The current thinking is outlined in [this comment of issue 101](https://github.com/elastic/ecs/issues/101#issuecomment-421425708).

We need to document these guidelines in the repo. The gist:

1. You're free to add other top level objects or even keys under ECS objects, at the risk of having a breaking change eventually, if 1) ECS adds the exact same field and 2) we pick a different datatype (e.g. `keyword` vs `long`).
2. If you want to ensure you never experience a breaking change because of a clash with ECS, you can nest your custom data under `custom`, `cust` or `c` at any level (top level or under existing ECS objects). We want ECS to reserve `custom` and its shorthands for user's custom needs.
  * Note that we cannot guarantee that various third party integrations using ECS will not clash between one another under the `custom` namespace. In that sense, custom integrations may actually prefer to go with option 1 and use their product name for their custom nesting.

In the process of documenting this, we may also publish a temporary short list of top level objects that are coming to ECS but haven't made it to the repo yet. Here's a list of actual pending TLOs coming to ECS:

- `related`
- `threat`
- `vulnerability`

@MikePaquette @ruflin Please don't hesitate to add to this, if I forgot anything

**Comment by ruflin** [comment]
Let's not have three option for `custom` but just one: `custom`. 

A general recommendation for third party fields should be using your company name as prefix or the service name which reduces the likelyhood of a conflict. So if your company or service is called `fizzbuzz` move all the fields under this prefix. Conflicts may still happen if there is a popular service with the same name.

**Comment by webmat** [comment]
Well given the following point about `custom`:

> Note that we cannot guarantee that various third party integrations using ECS will not clash between one another under the custom namespace. In that sense, custom integrations may actually prefer to go with option 1 and use their product name for their custom nesting.

should we even suggest using `custom`? Perhaps we should not.

**Comment by ruflin** [comment]
Agree, product / company name prefix should be enough but adding the warning it should not conflict with any popular service / protocol / name.

**Comment by webmat** [comment]
@ruflin I'd like to have your thoughts on this documentation on using non-ECS fields, when you have a minute.

https://github.com/webmat/ecs/blob/5a53e01/docs/3-implementing.md#using-non-ecs-fields-in-your-event-stream

Right now I'm adding it all at the end of the readme. But it's gearing up to be on the long-ish side. Perhaps it'll end up being a short and to the point recommendation in the readme + a distinct file that goes into all of the thinking / discussion / considerations...

I think it's important to lay this out clearly. I feel like 50% of the discussions in GH issues would benefit from people looking at this, and feeling more confident to do their thing, even if ECS doesn't include the fields for their specific use case :-)

**Comment by webmat** [comment]
https://www.elastic.co/guide/en/ecs/current/ecs-custom-fields-in-ecs.html addresses this
