### ISSUE TITLE
ECS Component Template 

### ISSUE THREAD

**Issue by mbudge** [elastic/ecs#1161]
Hi, 

An ECS component template would be useful, as it would save having to define ECS fields every time we create a new non-beats index. The ECS component template would be the first in the list of "composed_of" templates in the index template.

https://github.com/elastic/ecs/blob/master/generated/elasticsearch/7/template.json

I've got a python script to convert explicit mappings to dynamic templates, so the fields will only be defined in the new index mapping when data is indexed into them.

https://github.com/mbudge/dynamic-template-generator

Thanks

**Comment by ebeahan** [comment]
@mbudge There's been some recent discussion in #961 if you have any thoughts or additional feedback, and implementation work is underway in #1156.

**Comment by mbudge** [comment]
Thanks I'll close the ticket.
