### ISSUE TITLE
Create Threat Fieldset

### ISSUE THREAD

**Issue by peasead** [elastic/ecs#1216]
**Summary**

Create a threat fieldset for the ingestion of threat data and information.

**Motivation**:

Comparing threat data with environmental data is paramount to traditional security operations as well as threat hunting and intelligence analysis.

To do that, there needs to be a uniform way to describe this data within ECS so that it can be compared to other ECS compliant data.

**Detailed Design**:

Provide additional details around the design of the proposed changes.

Field | Type | Example | Description
--- | --- | --- | ---
threat.indicator.first_seen | date | 2020-12-01 | The date and time when intelligence source first reported sighting this indicator
threat.indicator.last_seen | date | 2020-12-02| The date and time when intelligence source last reported sighting this indicator.
threat.indicator.sightings | long | 20 | Number of times this indicator was observed conducting threat activity
threat.indicator.type | keyword | ipv4-addr, domain-name, email-addr | Type of indicator as represented by Cyber Observable in STIX 2.0
threat.indicator.description | wildcard | 201.10.10.90 was seen delivering Angler EK | Describes the type of action conducted by the threat
threat.indicator.dataset | keyword | theatintel | Identifies the name of specific dataset from the intelligence source.
threat.indicator.module | keyword | threatintel.{abusemalware,abuseurl,misp,otx,limo} | Identifies the name of specific module where the data is coming from.
threat.indicator.provider | keyword | Abuse.ch | Identifies the name of intelligence provider.
threat.indicator.confidence | keyword | High, 10, Confirmed by other sources, Certain, Almost Certain / Nearly Certain | Identifies the confidence rating assigned by the provider using STIX confidence scales (N/H/M/L, 0-10, Admirality, WEP, or DNI).
threat.indicator.ip | ip | 1.2.3.4 | Identifies a threat indicator as an IP address (irrespective of direction).
threat.indicator.domain | keyword | evil.com | Identifies a threat indicator as a domain (irrespective of direction).
threat.indicator.port | long | 443 | Identifies a threat indicator as a port number (irrespective of direction).
threat.indicator.email.address | wildcard [] | phish@evil.com | Identifies a threat indicator as an email address (irrespective of direction).
threat.marking.tlp | keyword | RED | Data markings represent restrictions, permissions, and other guidance for how data can be used and shared. Examples could be TLP (White, Green, Amber, Red).
threat.indicator.scanner_stats | long | 4 | Count of Anti virus/EDR that successfully detected malicious file or URL. Sources like VirusTotal, Reversing Labs often provide these statistics.

**CC:**
@shimonmodi

**Comment by peasead** [comment]
Current ECS RFC
https://github.com/elastic/ecs/pull/1480

**Comment by ebeahan** [comment]
[RFC 0008](https://github.com/elastic/ecs/blob/master/rfcs/text/0008-threat-intel.md) is now finished: https://github.com/elastic/ecs/pull/1480
