### ISSUE TITLE
New field to differentiate events that are triggered by root causes vs. symptoms

### ISSUE THREAD

**Issue by nnovaes** [elastic/ecs#1221]
**Summary**

New field to differentiate events that are triggered by root causes vs. symptoms

**Motivation**:

The current ECS fields do not contemplate an use case where events are categorized as root cause or if the event detected is a symptom of an actual root cause. This would allow better correlation and prioritization of events. i.e. consider a system that stablishes a vpn connection. if the physical interface on that connection goes down, then you could have multiple events, one for the physical interface being down and one for the vpn connections. so in that sense, the event for the physical connection would be considered a **root cause** and other events **symptoms**. 

**Detailed Design**:

Provide additional details around the design of the proposed changes.

* Field names: event.trigger
* Example values for the fields: root, symptom, unknown
* Suggested appropriate datatypes: keyword
* Any example events that map to the proposed use case(s)

Below are two examples from Versa Networks SDWAN appliances

**event.trigger = root** mapped from alarmKind
`alarmLog, applianceName=host1, tenantName=abc, alarmType=ipsec-tunnel-down, alarmKey=10.1.2.3|2, generateTime=1610552362, applianceId=1, vsnId=0, tenantId=1, alarmCause=causeOther, alarmClearable=yes, alarmClass=new, alarmKind=root, alarmEventType=communicationsAlarm, alarmSeverity=major, alarmOwner=provider, alarmSeqNo=9050, alarmText="IPSEC tunnel with peer 10.1.2.4 (routing-instance xyz-VR) is down", siteName=, serialNum=`

**event.trigger = symptom** mapped from alarmKind
`alarmLog, applianceName=host2, tenantName=abc, alarmType=sdwan-datapath-sla-not-met, alarmKey=host1|inet-pri-1|host2|inet-pri-1|fc_ef, generateTime=1610552362, applianceId=1, vsnId=0, tenantId=2, alarmCause=performanceDegraded, alarmClearable=yes, alarmClass=new, alarmKind=symptom, alarmEventType=equipmentAlarm, alarmSeverity=major, alarmOwner=host1/inet-pri-1 for fwdClass fc_ef, KPI delay:306 msec fwdLoss:3.54% revLoss:2.74% pduLoss:6.38% fwdDelayVar:48 msec revDelayVar:10 msec cktRxUtil:0% cktTxUtil:0%", siteName=host2, serialNum=`

**Comment by ebeahan** [comment]
I agree it would be useful to improve the correlation and filtering for all events associated with some activity when data sources provide it. Though, I see a wider need to search for both a root event and its related events in one query, instead of searching only for the root events or only for symptom events. Or do you imagine using this type of field in a different way?

**Comment by dainperkins** [comment]
I like the general idea (both from a root-cause analysis, and potentially an alert filtering mechanism - e.g. don't send me alerts for 50 system outages at site xyz if the connection to xyz is down) but...

1) I wonder how possible it will be to accurately identify root causes (as a perfect example, ipsec tunnel is down is likely not the root cause in the above example - likely the root cause is the native connection between the ipsec peers being down) 

2) Could we tweak this idea to provide a network map / dependancy type functionality (like the Observability Service Map)?

**Comment by djptek** [comment]
@nnovaes could you provide some more context on this?

**Comment by nnovaes** [comment]
> @nnovaes could you provide some more context on this?

some issues generate anything from 10s to 100s or 1000s log entries. there are certains cases that applying some logic (i.e. at parsing) we can easily differentiate log messages that were generated as symptoms of another failure versus log messages that show the root cause. 

in the example i provided, the only reason why we got a log with sdwan-datapath-sla-not-met for appliance=host2 was because the IPSEC tunnel was down. so it would be interesting to see ECS take that into account. there's no complex logic happening here tough. for this log source, every time we get a log about a SLA not being met, this is a symptom of a an issue for which we may have a log or not (i.e. SLAs can't be rebooted, suffer failures, etc). the same goes for IPSEC up/down tunnel messages. these are root causes, meaning they are a problem that need to be solved.

obviously, it would be up to people implementing the fields on how sophisticated they want to get in order to populate them (simple vs. advanced logics, analyze-and-reingest, etc) but there's a need for the field

**Comment by ebeahan** [comment]
This context is useful if the data source is providing it, but at this time, this isn't something we plan to add under `event.*`.

Feel free to reopen the discussion if there are additional points to consider or discuss.
