### ISSUE TITLE
Indexing performance and storage regression due to wildcard fields

### ISSUE THREAD

**Issue by epixa** [elastic/ecs#1233]
Since the wildcard RFC reached stage 3, the changes were made to the schema and due to roll out in ECS 1.8, however we discovered some notable performance issues related to storage size and indexing throughput that we must have time to review and address in a comprehensive way. The true scope of the problem and the extent to which we can roll out wildcard fields safely is not yet clear, but the best immediate course of action is to roll back these wildcard changes before they get released and then to iterate on the proposal going forward until we land at a place we're comfortable.

- [x] https://github.com/elastic/ecs/pull/1235 Rollback wildcard schema changes
- [x] https://github.com/elastic/ecs/pull/1237 Downgrade wildcard RFC to stage ~2~ 1 (draft)

**Comment by ebeahan** [comment]
@epixa Any objection to closing this out?

We can continue further discussion moving forward in the current `wildcard` RFC PR: https://github.com/elastic/ecs/pull/1247

**Comment by epixa** [comment]
None! Feel free to just close this sort of thing proactively with a comment. We can always reopen if it is closed erroneously.
