### ISSUE TITLE
Data/Object Sensitivity Fields

### ISSUE THREAD

**Issue by nwaringa** [elastic/ecs#124]
**The Who/What/Where/When/How Exists:**
- to/from general descriptors (numerous)
- device descriptors (numerous)
- location descriptors (numerous)
- human descriptors (numerous)
- file descriptors (numerous)
- event descriptors with disposition actions (numerous)

**But the Why is lacking (Why do I care about this):**
- A limited set of risk descriptors (event.risk_score, event.risk_score_norm, event.severity)

The limited **Why** descriptors do not address a core fundamental concern in analysis... data and object sensitivity. 

It may be worth adding rudimentary elements to build on a foundation later. 

```
event.data.sensitivity  // Contextually aware data classification 
host.sensitivity // Permitting asset classifications based on sensitivity 
source.sensitivity // See above
destination.sensitivity // See above
user.sensitivity // What the individuals normative highest data sensitivity trust level is
network.sensitivity // Beginning to acknowledge boundary definitions on sensitivity
```
are examples. 

If added... these open up opportunities:

- Data leakage identification of boundary breaking data travel amongst low sensitivity to high sensitivity networks
- Execution of automated actions with SOAR or other toolsets
- Identification of users attempting to break trust boundaries (Zero Trust Uses)
- Sorting 5,000 "High Risk" risk ranked items, with "Low" Source/Destination sensitivity... from 1 event with "High"

**Comment by webmat** [comment]
This is a very interesting idea, thanks for sharing. We'll consider this in future design sessions.

Have you seen this implemented anywhere? Can you give some examples of values you would put in these sensitivity fields (e.g. a discrete list of words, an increasing numeric value)?

**Comment by dainperkins** [comment]
I think this is one of the things that almost every security company seems to miss, and is an absolute must for good prioritization of alerts .  Playing recently I was thinking of how this could be accomplished in a logstash pipeline (e.g. elastic lookup for "asset valuation" from ip / domain / user / group etc. or  Translate to a configured file in the same vein.

**Comment by dainperkins** [comment]
The models I've put fwd to previous PMs has been 0-9, with no specific requirement for any number of groupings so that various governance / regulatory requirements can be easily used, and growing from a basic 3 criticality system to the full 10 would be a relatively easy process
