### ISSUE TITLE
Add 2 fields to code signature

### ISSUE THREAD

**Issue by Trinity2019** [elastic/ecs#1249]
**Summary**

Add following fields to [code_signature](https://www.elastic.co/guide/en/ecs/current/ecs-code_signature.html):
```
code_signature.team_id
code_signature.signing_id
```

**Motivation**:

performance enhancement: Collecting the team id and signing id can be done very fast whereas the signer name can be slow so there are cases where a data shipper may not want to report the signer name and just report the team id and signing id.

Need to point out team id and signing id are *OS(including macOS) specific and important for *OS. Combined together they are enough for *OS to identify/verify the origin and authenticity of a software vendor's code. Apple takes care of the uniqueness of team id and also checks the reputation of the team/company. Signing id is also important for *OS to identify applications from a software vendor.

Other big venders uses team id and signing id(a.k.a. bundle id) for profiling/whitelisting/etc. purpose: 
https://docs.microsoft.com/en-us/mem/intune/configuration/kernel-extensions-settings-macos
https://derflounder.wordpress.com/2018/04/12/whitelisting-third-party-kernel-extensions-using-profiles/
https://www.jamf.com/jamf-nation/discussions/28183/configure-apple-team-id-in-mdm-profile

**Detailed Design**:

* example team_id: 
  `EQHXZ8M8AV` // which is a team id for Google
  `UBF8T346G9` // which is a team id for Microsoft
  suggested datatype for team id will be string
* example signing_id:
  `com.apple.xpc.launchd` // which is the signing id for `/sbin/launchd`
  `com.apple.xpc.proxy` // which is the signing id for `/usr/libexec/xpcproxy`
  suggested datatype for signing id is string

**Comment by ebeahan** [comment]
Thanks for the detailed write-up, @Trinity2019! Would you be willing to open a PR for these changes?

I'm not familiar with code signing between different OSs, so the answer to the following may be a simple "no". 😅 

Are there similar values/IDs provided by different OSs that would ever be relevant values for these fields, in addition to macOS/OSX?

**Comment by ebeahan** [comment]
Closed via #1269

**Comment by Trinity2019** [comment]
Thank you @ebeahan for all the help! and thanks @rw-access for the PR review!
