### ISSUE TITLE
error.code in ECS vs error.code in Beats

### ISSUE THREAD

**Issue by jcallaha** [elastic/ecs#128]
I've been cross-referencing ECS against existing beats (based on their documentation) looking for collisions and gaps, and I noticed that **error.code** is a keyword in ECS but is a _long_ in all the beats except packetbeat where it isn't defined.

I assume it would be easier at this point to change ECS to match beats than the other way around?

**Comment by ruflin** [comment]
Good catch. The argument for long would be that it's sortable. For keyword that it can also contain non long values.

In general I would say the error.code is less for sorting but more for doing aggregations on it and I would expect error codes to no always be a long. Sometimes it could also be a string and is why I would prefer keyword. But really curious to hear other thoughts.

**Comment by webmat** [comment]
I also agree it should be `keyword`. `error.code` needs to be able to hold error codes from systems that use non numeric codes.

The only example I could come up with at the moment is [COM error codes](https://docs.microsoft.com/en-us/windows/desktop/com/com-error-codes) LOL. Maybe not the most bleeding edge ;-) But this is just to make the point that some systems use other identifiers than integers for their error codes, so we need to be able to support them.

It's also important to note that keyword indexing is extremely performant. It's not as heavy as indexing for full text search (`text`).

You can still sort `keyword` fields, by the way. It's just that integers will be sorted lexically, not numerically (i.e. 100 will come before 20).

**Comment by andrewkroh** [comment]
We have a PR open already that changes it from long to keyword. https://github.com/elastic/beats/pull/8313

**Comment by webmat** [comment]
Solved by updating the Beats side
