### ISSUE TITLE
Adding more HTTP info

### ISSUE THREAD

**Issue by blookot** [elastic/ecs#136]
Starting with http.response.time that all HTTP logs provide, as well as http.request.xff for instance...

**Comment by webmat** [comment]
@blookot Thanks for the suggestions.

* For your HTTP response time, you should use `event.duration`
* For the forwarding IPs, you should use `network.forwarded_ip`.  Any field in ES can be a single value or an array of values. So in the case of X-Forwarded-For, you can cram the whole array of IPs (if you have more than one proxy) in this field.

Things are a bit more broken up under ECS. So when looking at the `http` section, you'll find less fields than you usually do in most existing setups. Some of them will be under `url`, for example.

Let us know if you see anything else that's missing :-)
