### ISSUE TITLE
Move `message` fields to `match_only_text`

### ISSUE THREAD

**Issue by jpountz** [elastic/ecs#1377]
7.14 is introducing a new field type called `match_only_text` which is meant as a more space-efficient variant of the `text` field type. Its only downsides are the following:
 - no support for scoring: queries ignore index statistics and produce constant scores,
 - span queries are unsupported,
 - phrase and intervals queries run slower.

Other than that, this field supports the same feature set as `text`, and like `text` it doesn't support aggregations. See https://www.elastic.co/guide/en/elasticsearch/reference/master/text.html#match-only-text-field-type if you would like to know more.

We are in the process of changing our built-in templates in Elasticsearch so that `message` fields get mapped as `match_only_text` rather than `text`. I think we should do the same in ECS as of Elasticsearch 7.14 (when this field gets released)?

Please let me know if there's anything I can do to help.

**Comment by ebeahan** [comment]
Thanks, @jpountz! We had been excitedly following the progress of `match_only_text` to see where we could adopt it once it was ready. 😄  

I agree with looking to update `messages` in ECS as well, and I think we may even consider additional fields within ECS where it makes sense.

**Comment by djptek** [comment]
@jpountz we'll aim to open an RFC to move this forward, watch this space

**Comment by ebeahan** [comment]
Stage 0 RFC PR: https://github.com/elastic/ecs/pull/1396

**Comment by ebeahan** [comment]
Stage 1 RFC PR: https://github.com/elastic/ecs/pull/1415

**Comment by ebeahan** [comment]
[RFC 0023](https://github.com/elastic/ecs/blob/master/rfcs/text/0023-match_only_text-data-type.md) is finished and the changes implemented in https://github.com/elastic/ecs/pull/1584

**Comment by jpountz** [comment]
Thank you @ebeahan for moving this forward!
