### ISSUE TITLE
Add field for process owner to `Process` schema

### ISSUE THREAD

**Issue by matt-moses** [elastic/ecs#1380]
Running processes on a system have an owner - whether that be a `uid` like 0 in Linux for root or `SYSTEM` on Windows. I don't currently see a way to represent process ownership in ECS. I'm proposing that the following fields or something similar be added to ECS:

`process.uid` and/or `process.owner_name`

Thoughts?

**Comment by kgeller** [comment]
Hi @matt-moses ! 

Re `process.owner_name`

This can exist now by utilizing field set reuse see [here](https://github.com/elastic/ecs/blob/master/schemas/README.md#field-set-reuse) . We can reuse process within itself, but for the parent process. That combined with the existing `name field`, gets us `process.parent.name`. (There's an example for exactly that in the readme I linked above.

Re `process.uid`

This would be an excellent addition to the schema. I think naming it `user` might be nice. Our [endpoint schema](https://github.com/elastic/endpoint-package/blob/master/custom_schemas/custom_process.yml#L74) does as such.

**Comment by matt-moses** [comment]
Thank you for the information!

What would be the next steps for getting `user` added. Do you want me to put together a PR? Or is there something else? Or is this issue sufficient?

Let me know!  Happy to do whatever. Thanks!

**Comment by kgeller** [comment]
The [contribution guide](https://github.com/elastic/ecs/blob/master/CONTRIBUTING.md) should have some good info for you if you haven't seen it yet. You are welcome to put together a PR, or you can leave it and we will (in respect to priorities). 

You'll see mention of the RFC process in that doc, and this change is straightforward enough that you won't need to go through that.

**Comment by matt-moses** [comment]
Sounds good. I will put a PR together!

**Comment by matt-moses** [comment]
Opened a PR as noted above: https://github.com/elastic/ecs/pull/1387

Quick question ... added field as `extended` is that correct? Or should it have been `core`?

**Comment by kgeller** [comment]
Yes, `extended` is correct. [Here](https://www.elastic.co/guide/en/ecs/current/ecs-guidelines.html#_ecs_field_levels) the documentation is a bit better at explaining it than we have in the ecs repo.

**Comment by ebeahan** [comment]
Hey, @matt-moses! Sorry for joining the discussion late.

User details can be captured under the `user.*` fieldset for process events. You can see examples populated from `postgres` logs [here](https://github.com/elastic/beats/blob/23e4403ae093fcc8f7905345cad2c7ad256976d8/filebeat/module/postgresql/log/test/postgresql-13-log-statement-all.log-expected.json#L27) to give you some idea of what usage looks like.

The recently introduced field reuses of `user.*` also open up some nice capabilities within ECS to capture privileges changes. More detail and examples [here](https://www.elastic.co/guide/en/ecs/current/ecs-user-usage.html#ecs-user-usage-privilege-changes). The type of detail covered in the linked `user.*` usage doc is something we're working on for additional fieldsets (like `process.*`) to demonstrate better the combined use of the different field sets.

We think it's best to hold off on introducing a new `process.user` field to avoid confusion right now, and we'll revert the commit merged from #1387. If `process.user` makes better sense for your use case, feel free to leverage a [custom field](https://www.elastic.co/guide/en/ecs/current/ecs-custom-fields-in-ecs.html).

**Comment by matt-moses** [comment]
That all sounds good to me. Thanks for chiming in. I always appreciate feedback and a good discussion.

Follow up question then: The reason I went this route is that it looks like `user` isn't allowed to be nested under `process` per this section of the `process` schema page: https://www.elastic.co/guide/en/ecs/current/ecs-process.html#ecs-process-nestings Would it make sense to update this section and add `user`?

**Comment by ebeahan** [comment]
The top-level `user.*` fields can be used for process events. The `user.*` fields are intended to capture details of the user relevant to the event including if it's the user associated with a process.

Here's an example ECS event using top-level `user.*` fields, `user.domain`, `user.name`, and `user.id` (SID),  from a Sysmon process creation event:

```json
   "process": {
      "args": [
        "C:\\Windows\\system32\\notepad.exe"
      ],
      "command_line": "\"C:\\Windows\\system32\\notepad.exe\" ",
      "entity_id": "{9f32b55f-7c4e-5f98-5803-000000000500}",
      "executable": "C:\\Windows\\System32\\notepad.exe",
      "hash": {
        "sha1": "b6d237154f2e528f0b503b58b025862d66b02b73"
      },
      "name": "notepad.exe",
      "parent": {
        "args": [
          "C:\\Windows\\Explorer.EXE"
        ],
        "command_line": "C:\\Windows\\Explorer.EXE",
        "entity_id": "{9f32b55f-6fdf-5f98-7000-000000000500}",
        "executable": "C:\\Windows\\explorer.exe",
        "name": "explorer.exe",
        "pid": 4212
      },
    "related": {
      "hash": "b6d237154f2e528f0b503b58b025862d66b02b73",
      "user": "vagrant"
    },
    "user": {
      "domain": "VAGRANT",
      "id": "S-1-5-18",
      "name": "vagrant"
    }
```

**Comment by matt-moses** [comment]
Ah interesting. Thanks! That makes sense. I think this issue has been resolved then.

Thanks @kgeller  and @ebeahan for your help!!
