### ISSUE TITLE
[Tooling] Add a Flag in the ECS Generator to explicitly exclude one or more fields from the generated artifacts

### ISSUE THREAD

**Issue by djptek** [elastic/ecs#1403]
**Summary**

Add a Flag in the ECS Generator to explicitly exclude one or more fields from the generated artifacts
 
**Motivation**:

Simplify Testing of Deprecation/Removal of Fields, avoiding need to generate a subset of e.g. all but one field 

**Detailed Design**:

Add a flag "--excludeset" e.g.

```
python scripts/generator.py --ref v1.6.0 \
  --exclude-set       ../my-project/fields/exclude-set.yml \
  --include           ../my-project/fields/custom/ \
  --mapping-settings  ../my-project/fields/mapping-settings.json \
  --out               ../my-project/ \
  --subset            ../my-project/fields/subset.yml \
  --template-settings ../my-project/fields/template-settings.json
```

* Field names

To be defined ad-hoc
 
* Example values for the fields

```
---
- name: log
  fields:
    - name: original
```

* Suggested appropriate datatypes

n/a

* Any example events that map to the proposed use case(s)

See:
https://github.com/elastic/ecs/blob/master/rfcs/text/0017-remove-log-original.md
https://github.com/elastic/ecs/blob/master/rfcs/text/0022-remove-process-ppid.md

**Comment by kgeller** [comment]
@djptek is this good to close?

**Comment by djptek** [comment]
Thanks for the reminder @kgeller this is addressed by merged PR https://github.com/elastic/ecs/pull/1411, closing
