### ISSUE TITLE
[Tooling] Check hard-coded category fields in asciidoc_fields.page_field_values don't conflict with custom schemas

### ISSUE THREAD

**Issue by djptek** [elastic/ecs#1426]
**Description of the problem including expected versus actual behavior**:

asciidoc_fields.py fails if hard-coded category fields in asciidoc_fields.page_field_values were removed by e.g. a custom schema 

**Steps to reproduce**:

```
python scripts/generator.py --exclude=schemas/event.yml
Loading schemas from local files
Running generator. ECS version 2.0.0-dev
Traceback (most recent call last):
  File "scripts/generator.py", line 107, in <module>
    main()
  File "scripts/generator.py", line 66, in main
    asciidoc_fields.generate(nested, ecs_generated_version, docs_dir)
  File "/Users/djptek/git/ecs/scripts/generators/asciidoc_fields.py", line 13, in generate
    save_asciidoc(path.join(out_dir, 'field-values.asciidoc'), page_field_values(nested))
  File "/Users/djptek/git/ecs/scripts/generators/asciidoc_fields.py", line 94, in decorated_function
    ctx = func(*args, **kwargs)
  File "/Users/djptek/git/ecs/scripts/generators/asciidoc_fields.py", line 175, in page_field_values
    nested_fields.append(nested['event']['fields'][cat_field])
KeyError: 'event'
``` 

**Provide logs (if relevant)**:

n/a

**Any additional context:**

moot while [--exclude PR](https://github.com/elastic/ecs/pull/1411) not merged

**Comment by ebeahan** [comment]
We skip the docs when either the `--subset` and `--include` arguments are used, with the AsciiDoc generator being particular to generating the ECS docs. 

We could handle this the same way  as `--subset` or `--include`: exiting out early if the `--exclude` arg is used:

https://github.com/elastic/ecs/blob/master/scripts/generator.py#L60

**Comment by djptek** [comment]
Thanks, I'll give it a try soon as I'm done with test updates
