### ISSUE TITLE
Typo in the @timestamp example?

### ISSUE THREAD

**Issue by justmike** [elastic/ecs#1462]
**Description of the issue:**
In **[docs/using-getting-started.asciidoc](https://github.com/elastic/ecs/blob/23c95be31028a8d5db977f7304c00195921d7619/docs/using-getting-started.asciidoc#translating-data-sources)** under **Translating Data Sources**, the date/time in the example Apache web server log event:
> [15/Jul/2020:20:48:32 +0000]

does not match the @timestamp value in the table:
> 2020-07-15T20:20:48.000Z

because the "32" for seconds is missing. I think there were just too many "20" pairs and it's a typo?

Maybe to make it more clear, use different values for each pair of numbers? Perhaps:
> [15/Jul/2021:14:13:12 +0000]

so the @timestamp value would be:
> 2021-07-15T14:13:12.000Z

Hope I didn't just misunderstand something.

**Comment by djptek** [comment]
Thanks @justmike I've opened a PR https://github.com/elastic/ecs/pull/1463 to fix this

**Comment by ebeahan** [comment]
Hi, @justmike! Good catch! 👀 

This also brings to attention something I didn't consider before about that example:

The original date value from the Apache server log is being changed to a format supported by [`strict_date_optional_time`](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html#strict-date-time) in the table. This probably deserves mention to avoid confusion of why the timestamp format changed between the original log and the ECS mapped `@timestamp` value.

**Comment by justmike** [comment]
Looks good. Thanks for the quick fix!
