### ISSUE TITLE
asset id

### ISSUE THREAD

**Issue by robellison** [elastic/ecs#148]
is there any chance of getting an assetid field in this spec?
we assign assetids to assets to uniquely identify them
also serial number might be useful in some cases

**Comment by webmat** [comment]
Thanks for the suggestion, Rob.

ECS already defines `host.id`. Your comment made me realize we don't yet have `device.id`, however (I could have sworn we had that already). Perhaps `device.id` can partly fit your need?

If neither sounds suitable, what else would you like to be able to track with the more generic concept of an asset id?

Note that ECS is not like most other security schemas. Adhering to ECS means using as many ECS fields as possible, but **you are free to add your own fields** for any given use case, in addition to ECS fields.

We've been working to document how to approach this in a way to reduce chances of conflicts with future versions of ECS, but that documentation is not out yet.

**Comment by webmat** [comment]
And I'll be adding `asset.id` as well. It's a straightforward change :-)

**Comment by ruflin** [comment]
@webmat you mean `device.id`?

**Comment by webmat** [comment]
Yes, I meant adding `device.id` :-)

**Comment by webmat** [comment]
Just to loop back on this, I haven't added `device.id` after all, because we already have `device.serial_number`. It's a bit less flexible than `device.id`, but until there's a concrete need otherwise, I think it's ok to leave it at `device.serial_number`.
