### ISSUE TITLE
Review & Archive google doc Brainstorm on ECS Documentation

### ISSUE THREAD

**Issue by djptek** [elastic/ecs#1484]
We have a google doc [Brainstorm on ECS Documentation](https://docs.google.com/document/d/1zIpQG8Flq1pVpV4TOGYolGfqP2lTGeVrxCbZkZsfmeo/edit)

that contains some great ideas many of which were perhaps generated when the ECS docs were in an earlier evolution. 

Now that ECS docs are more stable (and have more inertia), I think it would be beneficial to set this read-only and review the google doc, creating or archiving issues where appropriate, to avoid technical debt/inherent risk of having multiple task queues

**Comment by ebeahan** [comment]
I reviewed the brainstorming doc. I feel confident that everything mentioned is addressed, outdated, or captured elsewhere. 

I set the doc to read-only and left the redirect to GitHub at the top.
