### ISSUE TITLE
Clarify mapping related to logging

### ISSUE THREAD

**Issue by bmagistro** [elastic/ecs#153]
Hello,

For logging from some of our applications we produce a log line that is `ISO8601 Date (microsecond + tz), log level, thread id/name, file, function, line number, message`.  This provides information about where in our code the log message originated, any thoughts on where/how to map these items into ecs?

From this line it seems like the mapping would be as follows optionally logging the original to log.original.
date/time to @timstamp
log level (think syslog facility) to log.level
thread id/name to ??
file to ??
function to ??
line number to ??
message to message

If `process.tid` and `process.thread` (or equivalent) are added, I can see those being used for thread id/name.

Thanks!

**Comment by bmagistro** [comment]
Thanks for the suggestions.  Will see where things go, the bigger concern I had with adding/changing the template for our use was compatibility with future changes.  Ideally we can map the items we want into existing/planned fields to minimize those impacts.

I did mean severity and not facility...too many things going on.

For these messages, they may not be errors (entries in application log file as opposed to stack trace/thrown exceptions).  If this was just a log file coming up from beats, I'm assuming the "message" component would map to "message"?

**Comment by webmat** [comment]
Yes, the work on #130 is about documenting how to avoid these clashes as best as possible. It's a tricky nut to crack, without getting very deep into details :-)

Note that if you map your event information to fields that end up not being the official field in ECS, you should be able to gradually move to ECS by using Elasticsearch' `alias` field type or `copyTo`. The bigger concern would be if you end up using the same field name with a conflicting field type. This would be the more painful situation.

Typically most messages go to `message`, you are correct. And in that vein, I've actually raised the question (internally) whether we should even have `error.message` on an event. The main message should always be in `message`. Other error details could be broken out in the `error` field set, whether it's exceptions or simpler error events, though.

**Comment by bmagistro** [comment]
Thanks for the input.  I think I have gotten our common logs (auditd, secure, messages, nginx, apache, and some of our apps) mapped in at a very basic level.
With in the log section, we added path that would map to filebeat "source".  For the app log described above, leveraging error.function and adding a "line" to file seemed to make the most sense.  I would like to get a little more run time but would be happy to share the logstash filter file for this if anyone is interested.  I am very certain that we can be doing MUCH more parsing than we are in some logs.

**Comment by webmat** [comment]
Hey @bmagistro, I'll close this for the time being, as it looks like everything has been answered.

Please open other issues if you have further questions, or if you've faced problems and would like to contribute ideas to ECS.

Thanks for getting in touch!
