### ISSUE TITLE
Add service.address field to ECS

### ISSUE THREAD

**Issue by mtojek** [elastic/ecs#1534]
**Summary**

* while performing cleanup of ECS fields in Integrations/Beats we noticed that `service.address` is not present there.

**Motivation**:

* The field is a relatively common across different Integrations ([search results](https://github.com/elastic/integrations/search?q=service.address)). Do you think we should include it in the ECS repository?

**Related**:

https://github.com/elastic/integrations/issues/1021
https://github.com/elastic/integrations/pull/1340

cc @djptek

**Comment by mtojek** [comment]
Thanks, @kgeller, for driving this. Would you mind describing what are the next steps to get it versioned and released?

**Comment by kgeller** [comment]
Absolutely @mtojek ! I am backporting it right now to ECS 1.12 , which will be FF in a couple weeks and then released a couple weeks after that.

**Comment by kgeller** [comment]
Implemented for ECS 1.12 , closing this issue
