### ISSUE TITLE
Add support for the reuseable objects in template.json

### ISSUE THREAD

**Issue by webmat** [elastic/ecs#155]
PR #152 introduces the concept of reuseable field sets in the YML files and renders them in the readme.

What's still missing is for the `template.json` to represent these field sets in the places where they are expected to be nested. #152 describes a few problems I'm having at this time, to do this.

There are two solutions I see, how we can approach the representation of these reuseable field sets in the `template.json`:

1. Use globs to define the field sets. E.g. `"path_match": "*.geo.country_code"`
2. Duplicate the whole field set in each expected location

I would like to gather people's opinions on which of these two approaches they prefer (or if I've missed another option).

**Comment by ruflin** [comment]
I prefer option one as it will work in all cases and not only our recommended once. I wonder if the above also works for `a.b.geo.country_code` or only `a.geo.country_code`. I think it's both but we should test.

**Comment by webmat** [comment]
I actually prefer option 2. I would rather not automatically support usages that are not expected. I prefer being a bit more explicit, and generate an index template that support what's expected. 

Since people will already not use the ECS index template as is anyway -- because they'll be adding their own fields around it -- I think it's fine to be strict. If they need a reuseable object in one place, they'll just define that as well.

**Comment by ruflin** [comment]
The nice part about option 1 is that it reduces the template size as we would use dynamic templates. I'm also fine with option 2.

**Comment by webmat** [comment]
Yeah I worded the options incorrectly.  We can totally declare once and use matching in both cases (to reduce template size).

What I meant was more along the lines of:

1. Set the mapping types via unbounded patterns
2. Set the mapping type via more specific pattern, where only "expected" fields will match

By the way the glob-based approach doesn't seem to support multiple patterns (can't do `"path_match" : "user,*.user"`). So we'll have to define them via [match_pattern](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html#match-pattern).

Do you know if regexes in dynamic templates can be a performance problem? I would assume as soon as a new field gets instantiated based on a match, the same field in subsequent documents will match the existing mapping without having to go through that regex?

**Comment by ruflin** [comment]
I don't expect the dynamic templates to have any performance problems.

For the path_match: I would just define the "global" field and as a normal field and all the others as dynamic fields with path_match.

**Comment by webmat** [comment]
In other words option 1, unbounded ;-)

Unbounded looks simpler at first because it's just one simple `path_match`. However if we change our mind and want to tighten it down because we realize there are problems, it's a breaking change: reusable objects in unexpected places would no longer match the tighter matching.

I don't terribly mind going unbounded, as I don't foresee problems at this time.

But let's just make sure we're on the same page and agree on the details:

1. Field sets not expected at the top level: display them at the top level in schema.csv?
2. Field sets not expected at the top level: have them match at the top level in template.json?
3. Nested field sets: only put them in the expected nested places schema.csv.
4. Nested field sets: unbounded match (`*.field`) in template.json?

I think there's no choice to be made for 3. It would be a huge mess to include all nested fields everywhere.

You're pushing for 4 to be unbounded. As I said, I can go with that. It makes me a bit uncomfortable, but I don't expect concrete problems, because the matching will still be pretty precise, e.g.: `*.geo.city_name` (2 levels), so it shouldn't match totally unexpected fields.

My opinion on 1 and 2 is to no to both. What's your take @rulfin?

**Comment by ruflin** [comment]
* 1: Depends on what we do in the readme. For me the csv is only a more compact variant of the readme.
* 2: I would prefer yes to make sure they are "reserved" and nobody uses them in a different way. Both works for me
* 3: Like 1, depends on readme
* 4: Both options work for me.

No strong preference on all the above. As I would go first with what is easiest to implement and then iterate on top of it. At the moment I would not consider a template change a breaking change as long as the field names don't change.

**Comment by webmat** [comment]
Solved a long time ago :-)
