### ISSUE TITLE
New top field "backend"

### ISSUE THREAD

**Issue by vbohata** [elastic/ecs#158]
I am going to set up logging from several reverse proxy servers. Currently it seems there is no top field for reflecting the backend servers. I need to log backend response time, ... I can not call it source, destination, client or server, it is just backend.
I think this should be added as a top level field because it has many use cases.

**Comment by webmat** [comment]
The reverse proxy (TCP and HTTP) is indeed a very common use case. Looking at various existing field sets, I think it's also relatively close to the caching proxies, and CDN & DDoS protection services.

Your situation is purely setting up proxies to do some typical load balancing?

What kind of things would you want to track?

Some thoughts:

* Response time can be broken down into origin/upstream response time vs proxy's response time itself.
* Your log's destination IP / ports would be the public values that got this request to hit your proxy. The IP / port of the backend should also be nested under that new object.
* Status code can be different between backend and final response code. Just like the previous point, I'd put everything that's client-facing into the existing / main ECS fields. The backend's status code should be nested in backend.

Here's some field sets for various proxy logs, for reference:

* [HAProxy](https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#8.2.4)
* [NGINX upstream module](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#variables), possible stuff you can cram in NGINX logs is spread over all their module's documentation, but the upstream module is the most relevant for this discussion.
* [Varnish](https://varnish-cache.org/docs/6.1/reference/varnishncsa.html#format)
* [AWS ALBs](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html#access-log-entry-format)
* [AWS Classic ELBs](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/access-log-collection.html#access-log-entry-format)
* [Traefik](https://docs.traefik.io/configuration/logs/#list-of-all-available-fields)
* [Cloudflare](https://support.cloudflare.com/hc/en-us/articles/216672448-Enterprise-Log-Share-REST-API), scroll down to "Currently available fields"

**Comment by vbohata** [comment]
We are using some basic proxy servers like HAProxy, but with more features, for each incoming request it performs some deeper security checks and forwards it to predefined set of servers (build as a HA solution). We are also using more clever proxies which are made of several distributed components and in logs we are receiving the total time it taken to preceed the request and the total time it took all the backend layers to proceed it. The total time is always a higher value. For this proxy we also receive the status of the backend layers.

Yes, the backend response status code could be different than client-facing. In practice it is the same or none - the proxy even do not have to contact the backends if could answer by itself. For everything client-facing it is fine to use the ECS fields which are also used for HTTP web servers.

Yes, it is close to forward/caching proxies but there is one field which could cause confusion. For forward proxies it is commonly fine to use "destination" prefix, it is more clear which is destination for caching proxy than for reverse proxy. So thats why the "backend" or "upstream" or ... field would help a lot.

**Comment by webmat** [comment]
@vbohata Our community team will be reaching out to a few people who have been helping flesh out ECS. I definitely consider you one of them :-) If you're interested in receiving some Elastic swag as a small gift, could you reach out to me at my work email? `firstname.lastname@elastic.co` :-)

**Comment by webmat** [comment]
We created meta-issue #938 to add proxy support in ECS. Closing in favor of the meta issue. Stay tuned :-)
