### ISSUE TITLE
schema/README `accepted_values` inconsistent with `allowed_values` in use

### ISSUE THREAD

**Issue by ChrisHines** [elastic/ecs#1589]
**Description of the issue:**

The `schema/README.md` document specifies `accepted_values` as one of the allowed entries for an ECS field definition in the YAML files of the directory. However, the YAML files (see `event.yml`) actually use `allowed_values` instead.

**Comment by ebeahan** [comment]
Good catch, @ChrisHines! 👀 

Looks like the docs weren't updated when changing from `accepted_values` to `allowed_values`: https://github.com/elastic/ecs/pull/692/commits/91aec05e512e1314e2beb98a78329dc6bc850175

I'll create a PR to address it.
