### ISSUE TITLE
Inconsistency in documentation of network.protocol

### ISSUE THREAD

**Issue by andrewthad** [elastic/ecs#1609]
The documentation for `network.protocol` reads:

> L7 Network protocol name. ex. http, lumberjack, transport protocol.

Why is "transport protocol" mentioned as a possibility? The transport layer is L4, and ECS makes it clear that that belongs in `network.transport`:

> `network.transport`: Same as network.iana_number, but instead using the Keyword name of the transport layer (udp, tcp, ipv6-icmp, etc.)

I think the phrase "transport protocol" should just be dropped from `network.protocol`'s documentation.

**Comment by ebeahan** [comment]
Addressed in #1645
