### ISSUE TITLE
ECS - Missing fields, possible nesting issue

### ISSUE THREAD

**Issue by dstepanic17** [elastic/ecs#1620]
**Summary**

There are some missing ECS fields related to the threat intelligence features in Elastic Stack.  Is it possible to add these into ECS? I believe it might be related to a previous issue around grouping and ordering that was recently fixed.  Since the packages map fields to the generated ECS, the CI components are failing.  

```
threat.indicator.file.x509.*

threat.indicator.file.hash.sha384
threat.indicator.file.hash.tlsh
threat.indicator.file.hash.pehash
```

**Comment by kgeller** [comment]
@dstepanic17 thanks so much for adding this! 

I will work on getting the `x509` field set corrected. In regards to `threat.indicator.file.hash.sha384` and `threat.indicator.file.hash.tlsh` , I don't see those two fields in the hash field set, are you sure they are formally in ECS? [schema for hash](https://github.com/elastic/ecs/blob/master/schemas/hash.yml)

**Comment by dstepanic17** [comment]
Thanks, I guess those two fields are not currently in ECS.  Is it possible to add those two fields in? Should I create a PR to do that?  They would mimic the other hash [entires](https://github.com/elastic/ecs/blob/master/schemas/hash.yml), but with their own respective names.

**Comment by kgeller** [comment]
Can absolutely get those added.

Normally for schema changes, we recommend going through the [RFC process](https://github.com/elastic/ecs/tree/master/rfcs) as it allows us to fully vet the proposal. However these fields appear straightforward, so I am inclined to say we can simply add them via a PR. What do you think?

**Comment by dstepanic17** [comment]
Thanks, yeh I was thinking the same thing. The additions seem clear-cut so if it's possible to skip the RFC process that would be great.

**Comment by P1llus** [comment]
threat.indicator.file.hash.pehash also seems to be missing @dstepanic17

**Comment by kgeller** [comment]
Awesome @dstepanic17 , I think we can move forward with those 3 new field additions (counting in the additional from @P1llus ). 

I will separately correct the nesting for `x509`.

**Comment by rylnd** [comment]
Just updating with notes from today's CTI Initiative sync: if `pehash`, `tlsh` and `sha384` are being populated by threatintel modules, we shouldn't add mappings for `threat.indicator` until these fields are part of ECS. If the aforementioned PR isn't merged when those modules ship, we should either:

* populate `threat.indicator.file.hash.{pehash,tlsh,sha384}` without a corresponding mapping
* populate `[module].file.hash.{pehash,tlsh,sha384}` with mappings (outside of ECS)

or we could do both, I suppose. cc @P1llus

**Comment by dstepanic17** [comment]
@kgeller Hey, following up on this.  What do you think from your perspective is the best path forward? These hashes exist already in both the integrations and the filebeat modules with their respective mappings.  I think at the end of the day, there will need to be place to put these hashes in so either a new approach is needed or we need to keep extending the support.  This will likely come up again in the future.

**Comment by kgeller** [comment]
@dstepanic17 I think the next step would be to open that PR adding in those three missing fields, as they already exist in beats/integrations.

**Comment by dstepanic17** [comment]
FYI @kgeller, a [PR](https://github.com/elastic/ecs/pull/1678) has been created for this. Thanks.

**Comment by dstepanic17** [comment]
Closing, these fields have now been added to ECS schema.  Thanks for all the help @kgeller!
