### ISSUE TITLE
ECS as a dependency

### ISSUE THREAD

**Issue by djptek** [elastic/ecs#1630]
@ebeahan @andrewstucki 

https://github.com/elastic/ecs/issues/630#issuecomment-866327493

>> If future versions of Packetbeats will rely on newer versions, we can figure out how to best continue maintaining the library

https://github.com/elastic/ecs/issues/630#issuecomment-866329287

>> as it is there are already some missing things in the current structures that we're actually working around to begin withh

Registering interest in any future discussion of how to avoid workarounds & maintain the library

**Comment by ebeahan** [comment]
Removed golang deps in https://github.com/elastic/ecs/pull/1585
