### ISSUE TITLE
Generated ECS templates for Elasticsearch 6.x vs "flattened" field type

### ISSUE THREAD

**Issue by yaauie** [elastic/ecs#1649]
**Description of the issue:**

Since v1.11.0, the [generated ECS templates for Elasticsearch 6 include fields of type `flattened`](https://github.com/elastic/ecs/blob/v1.11.0/generated/elasticsearch/6/template.json#L917-L919), which was not introduced until Elasticsearch 7.3 and was never made available on the 6.x series of Elasticsearch. When attempting to install these templates on Elasticsearch 6.8.19, they are rejected:

~~~
{
  "error" : {
    "root_cause" : [
      {
        "type" : "mapper_parsing_exception",
        "reason" : "No handler for type [flattened] declared on field [imports]"
      }
    ],
    "type" : "mapper_parsing_exception",
    "reason" : "Failed to parse mapping [_doc]: No handler for type [flattened] declared on field [imports]",
    "caused_by" : {
      "type" : "mapper_parsing_exception",
      "reason" : "No handler for type [flattened] declared on field [imports]"
    }
  },
  "status" : 400
}
~~~

**Any additional context or examples:**

The Elasticsearch Output Plugin for Logstash vendors the generated ECS templates and uses them (with modified index pattern) when a user has the plugin configured to `manage_template => true` (on by default) and the plugin is running in ECS compatibility mode (`ecs_compatibility => v1` in the plugin, or `pipeline.ecs_compatibility: v1` in their `logstash.yml`). We depend on the templates to be installable.

**Comment by djptek** [comment]
Thanks @yaauie I'll take a look

**Comment by djptek** [comment]
Hi @yaauie sorry for the delayed response, would your expectation be that those fields be of type `keyword` for Elasticsearch version < 7 ?

**Comment by djptek** [comment]
if you are not actually leveraging those fields, there are a couple of ways to work with the tooling to avoid these being included in the template:

- you can check out an older version of ECS from Github and use the corresponding generator
- you can use the `--exclude` flag to prevent those fields being included in the generated templates, see https://github.com/elastic/ecs/blob/main/USAGE.md#exclude

**Comment by ebeahan** [comment]
> Hi @yaauie sorry for the delayed response, would your expectation be that those fields be of type keyword for Elasticsearch version < 7 ?

I think `object` would be the appropriate fallback for `flattened`.

This behavior is a bug in how the ES 6.x template is generated, and we can resolve it by adding a fallback [here](https://github.com/elastic/ecs/blob/main/scripts/generators/es_template.py#L11-L16) (similar to how `wildcard` fields fall back to `keyword`).

Like @yaauie pointed out, we should go back and patch the bug in the 1.11 and 1.12 branches to avoid the `mapper_parsing_exception` error for anyone attempting to use those templates with ES 6.x.

**Comment by yaauie** [comment]
I don't have any expectation about what types those fields should fall back to on ES 6, and am not involved enough with the options available to have an informed opinion.

My hope is that the templates explicitly generated for ES 6 be of a shape that does not get an exception when installed in the latest ES 6.

**Comment by djptek** [comment]
Hi @yaauie that should be in the `main` branch now (note, we renamed `master` to `main` recently), thanks for finding this
