### ISSUE TITLE
Expanding`interface.*`

### ISSUE THREAD

**Issue by kgeller** [elastic/ecs#1668]
A number of open questions surrounding ECS' fieldset `interface` were surfaced https://github.com/elastic/ecs/issues/226. 

- Should we add resuses for `interface` at the following locations?
  - source
  - destination
  - client
  - server
  - observer
- Should we allow for reuse (self or external) at the following locations?
  - in/out (or inbound/outbound or ingress/egress)
- Should we add additional fields to the fieldset?
  - description

**Comment by ebeahan** [comment]
> Should we add resuses for interface at the following locations?

ECS does have `observer.egress.interface.*` and `observer.ingress.interface.*` which, I think, does a decent job of covering the firewall, router, and IDS use cases.

The current description for the `interface.*` fields does limit use by an observer, so in considering any other field sets, the field set's description would need to be revisited.

---

> Should we add additional fields to the fieldset?

While `alias` is an overloaded term (for example, a [textual interface description](https://www.juniper.net/documentation/us/en/software/junos/interfaces-fundamentals/topics/ref/statement/alias-edit-interfaces.html) or [assigning more than one IP to an interface](https://en.wikipedia.org/wiki/IP_aliasing)), I think adding a `description` field in addition to `alias` could create confusion over which field to place a text description into. So, I'd vote not to add `description` and instead continue using `alias`.

**Comment by kgeller** [comment]
Thanks @ebeahan . I think I'll go ahead and close this issue for the time being since it seems like everything is addressed!
