### ISSUE TITLE
Allow regex pattern to be specified in schema to improve data consistency

### ISSUE THREAD

**Issue by andrewkroh** [elastic/ecs#1741]
**Summary**

Add information to the schema to support automated data validation. I propose allowing a regular expression field that tools can use to validate a value.

For example `source.mac` would give a pattern that checks for RFC 7042 format in uppercase.

```yaml
- name: source.mac
  pattern: '^[A-F0-9]{2}(-[A-F0-9]{2}){5,}$'
```

[JSON schema](https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.7.3.8) has a similar concept and supports many more validation types, but I think have a regular expression would be a good place to start.

**Motivation**:

https://github.com/elastic/elastic-package/issues/615

I'm trying to improve the consistency of values contained in ECS fields through automated tests.

**Detailed Design**:

It would be good to go through the schema and see how many places this could be applied.

**Comment by ebeahan** [comment]
I agree this would be useful. Additionally, some sort of `enum` would also be helpful for fields with "allowed values."

Would `elastic-package` be looking for this value in the [generated ECS YAML files](https://github.com/elastic/ecs/tree/main/generated/ecs)?

**Comment by andrewkroh** [comment]
That correct, it would reading from the generated files. Here's where it looks: 

https://github.com/elastic/elastic-package/blob/8d9732d0c4364d28ba1c34f2ad7fe91dfc7d2785/internal/fields/dependency_manager.go#L28-L29

**Comment by andrewkroh** [comment]
The allowed_values appear to [already be](https://github.com/elastic/elastic-package/blob/8d9732d0c4364d28ba1c34f2ad7fe91dfc7d2785/internal/fields/dependency_manager.go#L28-L29) machine readable. It just takes a bit more work to interpret the data than a straight `enum` string array.

**Comment by andrewkroh** [comment]
Another use would be for validating fields that say they should be lowercase like network.protocol and network.transport.
