### ISSUE TITLE
Generated Elasticsearch 7 Index Template cannot be used

### ISSUE THREAD

**Issue by fgierlinger** [elastic/ecs#1754]
**Description of the issue:**
When generating an ecs index template for elasticsearch 7, it is put under `generated/elasticsearch/7/template.json`. I expected to take this json and put it as body for the `POST _index_template/<index template>` request.

The API call fails with the following message: `[index_template] unknown field [mappings]` . Indeed, when inspecting the `generated/elasticsearch/7/template.json` file the `mappings` section is in root instead of being under `template` (`template.mappings`). The template that uses components (`generated/elasticsearch/template.json`) is not affected from this error.

**Steps to reproduce**
1. Checkout ecs git repo
2. Create a `myproject/subset.yml`
```
---
name:my-ecs
fields:
  base:
    fields: '*'
```
3. Create index templates with `scripts/generator.py`
```
python ./scripts/generator.py --ref v1.12.2 --subset myproject/subset.yml --out out/
```
4. Load generated index template into elasticsearch
```
$ curl -u password -X POST https://elasticsearch:9243/_index_template/my-template -d @out/generated/elasticsearch/7/template.json -H 'Content-Type: application/json' --silent | jq
{
  "error": {
    "root_cause": [
      {
        "type": "x_content_parse_exception",
        "reason": "[1:44] [index_template] unknown field [mappings]"
      }
    ],
    "type": "x_content_parse_exception",
    "reason": "[1:44] [index_template] unknown field [mappings]"
  },
  "status": 400
}
```
Using the index template with component templates leads to no error:
```
$ curl -u password -X POST https://elasticsearch:9243/_component_template/ecs_1.12.2_base -d @out/generated/elasticsearch/component/base.json -H 'Content-Type: application/json' --silent | jq
{
  "acknowledged": true
}
$ curl -u password -X POST https://elasticsearch:9243/_index_template/my-template -d @out/generated/elasticsearch/template.json -H 'Content-Type: application/json' --silent | jq
{
  "acknowledged": true
}
```

**Actual behaviour**
Using generated templates for elasticsearch 7 fails because the `mapping` attribute is not under `template`.

**Expected behaviour**
All generated templates should be usable with the respective elasticsearch version.

**Environment information**
ECS 1.12.2
Elasticsearch 7.16.2

**Comment by kgeller** [comment]
Hi @fgierlinger !

When you're working with our 'legacy' index templates (the non-composable templates), you're going to want to use the [`_template` API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates-v1.html) as opposed to the [`_index_template` API](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-templates.html). 

Following along your example scenario, my results with each of the APIs:
### _template

```
{
  "acknowledged" : true
}
```

### _index_template

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "x_content_parse_exception",
        "reason" : "[5:3] [index_template] unknown field [mappings]"
      }
    ],
    "type" : "x_content_parse_exception",
    "reason" : "[5:3] [index_template] unknown field [mappings]"
  },
  "status" : 400
}
```

**Comment by fgierlinger** [comment]
@kgeller Thank you for your explanation. That totally makes sense that the legacy templates only work with the legacy API call.
