### ISSUE TITLE
Add `agent.hostname`

### ISSUE THREAD

**Issue by webmat** [elastic/ecs#178]
In cases where an agent is not running on a host generating an event (e.g. APM server), it's useful to track where the agent is running without touching `host.hostname`.

Beats has already replaced `beat.hostname` with `agent.hostname` here https://github.com/elastic/beats/pull/8873.

So the relationship between the two fields is:

- `host.hostname` should be populated with the hostname of the node generating the event
- `agent.hostname` should be populated with the hostname of the node where the agent is running, if different than the source of the event.
  - Question: should we always populate it, even if it's the exact same value?

**Comment by ruflin** [comment]
+1 on this proposal. For the population of the fields: Undecided but I think for now I would leave it out of scope of ECS to define it.

**Comment by ave19** [comment]
I think one of my analysts just had an aneurism. :)

**Comment by webmat** [comment]
I get the joke vs your feedback from yesterday ;-) I think we could do a better job of highlighting which fields are the "main" field (hostname is a good example), and which ones are to be used for secondary situations, like the `agent.hostname` above.

Does this make sense, though? Imagine you're using [Filebeat's syslog input](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-syslog.html) to act as a sink for an area of your network. `agent.hostname` is that sink's hostname, where `host.hostname` is the hostname of the source of the event.

Does that make sense? Is there anything about it that we're missing?

**Comment by MikePaquette** [comment]
Sorry for overlooking this issue forever :-(

ECS should not have a field `agent.hostname`  as this breaks the entity relationship implicit in the fact that an agent is a software entity, if any, that collects, detects, or observes events on a host, or takes measurements on a host.  Therefore an agent cannot have a hostname associated with it.

In the case where an agent is not running on a host generating an event (e.g. APM server),  the APM server is considered the `observer`, and its hostname should be populated in the `observer.hostname` field.  

The APM Server example is explicitly documented in the ECS documentation [here](https://www.elastic.co/guide/en/ecs/current/ecs-observer.html).

> Examples include firewalls, intrusion detection/prevention systems, network monitoring sensors, web application firewalls, data loss prevention systems, and APM servers.

**Comment by ppf2** [comment]
Given the note above, should filebeat (and other beats) have made the [breaking change](https://www.elastic.co/guide/en/beats/libbeat/current/breaking-changes-7.0.html#_field_name_changes) in 7.0 to rename `beat.hostname` to `agent.hostname`?

**Comment by ebeahan** [comment]
Per reasoning laid out in https://github.com/elastic/ecs/issues/178#issuecomment-512586064, not moving forward adding `agent.hostname`.
