### ISSUE TITLE
Any fields to describe a mobile app?

### ISSUE THREAD

**Issue by al-stefanitsky-mozdor** [elastic/ecs#1799]
Is there any field to describe the user version of mobile app?

**Comment by ebeahan** [comment]
Without more context, I'd suggest [`package.version`](https://www.elastic.co/guide/en/ecs/current/ecs-package.html#field-package-version).

Feel free to ask general ECS questions over in our [Discuss forums](https://discuss.elastic.co/tag/ecs-elastic-common-schema).
