### ISSUE TITLE
Add support for version breakdown fields

### ISSUE THREAD

**Issue by webmat** [elastic/ecs#186]
Breaking up version fields into their components is a common practice. It allows grouping into bigger buckets for analysis (e.g. "get all the Windows 7, regardless of minor/patch level").

We currently have a few version fields in ECS:

- `agent.version`
- `device.version`
- `ecs.version`
- `os.version` (note: nestable under `user_agent` & a few other places)
- `user_agent.version`
- `service.version`

## Possibilities

There are a few ways we could add them, and each has issues.

So let's hear opinions. Which option do you prefer? Are there other options you see?

### Add fields at the same level

Example:

- `(parent).version` already exists
- `(parent).major`
- `(parent).minor`
- `(parent).patch`

Pros:

- Not a breaking change
- Short field names

Cons:

- Field names for the version breakdown may conflict with other concepts we're trying to support in these filesets
- Future additions to version parsing keep adding to many filesets
  - Adding field for prerelease (e.g. `beta1`)
  - Adding field for a 4th numeric position (like Chrome's `70.0.3538.102`)

### Turn `version` into a reusable field set

Example:

- `(parent).version` becomes an object
- `(parent).version.full` what used to be in `(parent).version`
- `(parent).version.major`
- `(parent).version.minor`
- `(parent).version.patch`

Pros:

- No conflict with other field set's fields, it's all neatly tucked under `version.*`
- The breakdown field names make more sense in this context, especially to non-developers.  Scenario:
  - Bob: "What's this `service.patch: 0`? Don't we patch our systems?"
  - Alice: "Oh, that's the patch level of the version."
  - Bob: "What?"

Cons:

- It's a breaking change
- Slightly longer field names, but manageable.

### Create a field set named differently than `version`

Could be `v`, `ver`, something else. Let's illustrate with `ver`:

Example:

- `(parent).version` as it already exists, it's the full version field
- `(parent).ver.major`
- `(parent).ver.minor`
- `(parent).ver.patch`

Pros:

- It's not a breaking change
- No conflict with other field set's fields, it's all neatly tucked under `ver.*`
- The breakdown field names also make more sense in this context
- If we pick a name that starts with `v`, the full version and version breakdown will be close by in alphabetical listings

Cons:

- Feels slightly weird to break it down into a second different field
- Doesn't respect guideline "Do not use abbreviations"
- Slightly longer field names, but manageable.

## Out of scope

Once we figure out the strategy we prefer, major/minor/patch are straightforward. They're standard terms for these concepts.

I would keep the following out of scope for now, however:

- Field for pre-release: `7.0.0-beta1`
- 4th numeric version field: `70.0.3538.102` (Chrome version)
- Nested versions: `0.9.8e-29.el7.centos.3` (Redhad security backports on top of OpenSSL 0.9.8e)

**Comment by ruflin** [comment]
We had this discussion in the early days of ECS and decided to go only with a version string. The reason is that most of the above things Elasticsearch can do without the split up based on prefix queries. I would rather see that in the long term Elasticsearch would support a semantic version type and then allow all the fancy queries which are possible on versions.
