### ISSUE TITLE
Add New ECS Fields For Filebeat Module Fields That Lack Existing Fields

### ISSUE THREAD

**Issue by mr1716** [elastic/ecs#1890]
**Summary**
For the Filebeat modules that lack ECS mappings for existing base fields, such as panw.panos.source.interface, there should be a source.interface field created. For Filebeat module fields that lack an existing ECS base field, there should be a way to group these together, such as o365.audit.AlertType, elasticsearch.elastic_product_origin, and rsa.internal.audit_class.

**Motivation**:
Help make the Filebeat modules more ECS compliant.

**Detailed Design**:
To design this, the goal and the process is to bring the Filebeat module fields into alignment with ECS. Therefore, the process will be to rectify issues accordingly.

**Comment by ebeahan** [comment]
> For the Filebeat modules that lack ECS mappings for existing base fields, such as panw.panos.source.interface, there should be a source.interface field created.

Firewalls, like Palo Alto, are considered an [`observer`](https://www.elastic.co/guide/en/ecs/current/ecs-observer.html) and use the `observer.*` fields. In [this example,](https://github.com/elastic/beats/blob/v8.1.3/x-pack/filebeat/module/panw/panos/test/pan_inc_traffic.log-expected.json#L52) from Beats, `ethernet1/2` is populated in both `observer.ingress.interface.name` and `panw.panos.source.interface`.

> For Filebeat module fields that lack an existing ECS base field, there should be a way to group these together, such as o365.audit.AlertType, elasticsearch.elastic_product_origin, and rsa.internal.audit_class.

All Filebeat modules are ECS-compliant, but many data sources will have some data that doesn't map into existing ECS fields. Creating a custom namespace under [proper names](https://www.elastic.co/guide/en/ecs/current/ecs-custom-fields-in-ecs.html#_proper_names), like `o365` or `rsa`, provides a place to capture those values and avoids potential collision with future ECS field names.

If a concept frequently repeats across different sources, it may make sense to define ECS fields around it. Teams maintaining Beats and Elastic Agent regularly revisit integrations to adopt relevant ECS changes. However, custom fields may be left in place, so modules/integrations remain backward-compatible.

**Comment by mr1716** [comment]
@ebeahan thanks for the information as the description helps clear things up. However, is there a threshold that says, "well, we've seen 3 modules work this way and use this type of field, then we should create a base field" or is it just like after like 5 or 7 or whatever, there's a base field? Trying to determine when and how new fields gets created

**Comment by ebeahan** [comment]
No, there's not a specific threshold. Some new fields are introduced through community contributions, user discussions in GitHub issues, integration needs, etc.

Small schema additions (like adding one or two fields to an existing field set) happen via PRs, but more substantial changes go through an [RFC process](https://github.com/elastic/ecs/tree/main/rfcs).

**Comment by mr1716** [comment]
Thanks. So that means if I wanted to add a new field to the URL base, such as URL.action, then I would simply submit a new PR and then we would be good to go for that new field??

**Comment by ebeahan** [comment]
Yes, but any proposed changes must be reviewed and understood before being approved and merged. Some proposed fields fill apparent gaps, but others may require more discussion.

If a PR proposed an `url.action` field, these types of questions would need answers:

* What values would go into an `url.action` field?
* What use cases would an `url.action` field help support?
* Could the existing `event.action` field be used instead of adding a new field?

**Comment by mr1716** [comment]
@ebeahan Thanks for the information. It sounds like as long as there is a good usecase and a good description/valid reason for creating a new base field and/or base subfield, it would be taken into consideration and might be approved if the proposed change were seen in X number of modules for example and didnt fit into an existing base field.

**Comment by ebeahan** [comment]
@mr1716 I'm going to close this issue. If you have other questions, please open a thread in the [ECS discuss forum](https://discuss.elastic.co/tag/ecs-elastic-common-schema).
