### ISSUE TITLE
related.ip example in docs should be an array

### ISSUE THREAD

**Issue by andrewkroh** [elastic/ecs#1918]
The `related.ip` example in the docs should be an array. https://www.elastic.co/guide/en/ecs/8.2/ecs-principles-implementation.html#_related_fields

<img width="765" alt="Screen Shot 2022-05-18 at 09 56 58" src="https://user-images.githubusercontent.com/4565752/169058548-afc43c7b-9392-43c9-92b6-8a0fad0182fc.png">

**Comment by ebeahan** [comment]
Resolved in #1922
