### ISSUE TITLE
fass.trigger.type should specify 'allowed_values'

### ISSUE THREAD

**Issue by andrewkroh** [elastic/ecs#1925]
**Description of the issue:**

`fass.trigger.type` defines a set of expected values in its `description`, but it does not populated the schema's `allowed_values` attribute. This makes it difficult to implemented schema validation for the field's values.

My ask is that the schema add an allowed_values attribute to `fass.trigger.type` so that [`elastic-package`](https://github.com/elastic/elastic-package) can validate usages of the field in Fleet integrations. We should also check if other fields define "expected values" in the description and not in an structured format that can be used programmatically and fix those too.

**Any additional context or examples:**

https://github.com/elastic/ecs/blob/a230fa36e10127fdcfba11c56534ad63de6eaf32/generated/ecs/ecs_flat.yml#L3470-L3471

**Comment by ebeahan** [comment]
++ to standardize expected values. There are other fields that will benefit, like `network.direction`.

The existing `allowed_values` used in `event.yml` attribute is purpose-specific to event categorization and generating ECS docs. It'd be simpler to create a new parameter, maybe `expected_values`.

**Comment by ebeahan** [comment]
> It'd be simpler to create a new parameter, maybe expected_values.

Tracking this effort in https://github.com/elastic/ecs/issues/1951

**Comment by ebeahan** [comment]
Implementing `expected_values` into the field defs in #1962

**Comment by ebeahan** [comment]
Implemented in #1962
