### ISSUE TITLE
`service.node.role` should be `service.node.roles` and support multiple keywords

### ISSUE THREAD

**Issue by lukeelmers** [elastic/ecs#1965]
I'm working on adding a `node.roles` configuration to Kibana, and discovered some discrepancies in the spec that was merged in https://github.com/elastic/ecs/pull/1916 and the use case we had envisioned for this in Kibana.

In our configuration, we want to allow nodes to have _multiple_ roles. So for example, the following would be a valid value for the field:
```
node.roles: ['ui', 'background-tasks']
```

The PR that was merged only allows for a single item (not normalized as an array) and is also named `service.node.role` (singular).

Looking for advice on what to do here, since this was merged for 8.3. It is almost certainly too late to do anything about it, but unfortunately it means we won't be able to adhere to this spec in Kibana based on the technical needs of our project.

Should we leave the field as-is and just not use it? Deprecate it? Something else?

FWIW, we won't be actually introducing usage of this field in Kibana until at least 8.4.

cc @kobelb @matschaffer @ebeahan

**Comment by matschaffer** [comment]
🤦🏻 if only we had an easy way to upgrade fields from old to new versions (string to list should be one of the easy ones).

Deprecation of the old field and introduction of a new field make sense to me.

**Comment by kgeller** [comment]
@lukeelmers @matschaffer I'd say that since 8.3 hasn't been released, we can just go ahead and fix this now (`role` -> `roles` and single value -> array).

@ebeahan does that seem reasonable to you?

**Comment by ebeahan** [comment]
Integrations (and potentially elsewhere) have already adopted ECS 8.3. I did a brief review and not seeing any active use of `service.node.role`, but I agree with @lukeelmers that it's too late to adjust for 8.3.

Not ideal, we could keep the name `node.role` and update from a single value to expecting an array. An event's `_source` may not match, but Elasticsearch indexing wouldn't be affected .

**Comment by lukeelmers** [comment]
> we could keep the name `node.role` and update from a single value to expecting an array

Is that a breaking change though? If so, I'd just as soon rename the field as well for clarity: `service.node.roles`

**Comment by ebeahan** [comment]
ECS 8.3 hasn't released yet, so changing either the field name or single/array expectation is still non-breaking in the spec itself. But, stack/solutions/integrations already adopted 8.3 changes. Renaming or removing a field may create issues downstream.

Changing single => array has no effect on ES indexing or querying, so for a new, unreleased field the change carries little risk. On the small chance any sources are already populating `service.node.role`, only an event's `_source` needs adjusting.

**Comment by lukeelmers** [comment]
Ah, makes sense. If you think that's the best path forward, then we will stick with using `node.roles` for the Kibana-side configuration (to match [what ES does](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html)), but will use `service.node.role` in the Kibana logs so we can still have consistency with ECS.

**Comment by matschaffer** [comment]
I'm mildly saddened my miss will now live on indefinitely and create cognitive dissonance between config & logs. But if it's the best we can do, so be it. :(

**Comment by matschaffer** [comment]
Thanks @kgeller - that definitely sounds better :)

**Comment by kgeller** [comment]
Deprecation notice and new field have been added.
