### ISSUE TITLE
Mapping OS fields for mobile devices (e.g. Android, iOS)

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/ecs#1995]
**Summary**
For the APM Mobile agents we would like to properly populate the Operating System Fields. 
What is not clear to me is what we would set for `os.type`  and `os.platform` in case of iOS and Android. 

Let's take the example of iOS. According to [the description of ](https://www.elastic.co/guide/en/ecs/current/ecs-os.html#field-os-type)`os.type` there is no allowed value that would be valid (because `Macos` is not `iOS`and `ios` is not allowed as a value). Also, in this case, `os.platform` would have the value `darwin` (since iOS is based on Darwin). But `darwin` could also mean that it's a MacOS device (not mobile). So, there is no field where we could put the value `ios` in to properly categorize the operating system in this case.

**Motivation**:
Capture and categorize the operating system of mobile devices properly.

**Detailed Design**:
Does it make sense to add the following values as valid values for `os.type`?:
* `ios`
* `android`

Or are there other ideas how we could handle the scenario described above?

**Comment by kgeller** [comment]
I think that it does make sense to add `ios` and `android` to acceptable values for `os.type`, and I'd invite you to open a PR to do that.
