### ISSUE TITLE
Field sets split over files

### ISSUE THREAD

**Issue by phil-dotchon** [elastic/ecs#2060]
I'm new to ECS and still finding my way; I have successfully created some custom fields, including adding 'serial' to the 'hosts' field set by copying the base schema host.yml file into my own directory, removing all of the existing field definitions and adding just a single field called 'serial'. I then used --include with generator.py and it happily merged the contents of both 'host' files under the host object.
I also tried to break up my other custom field set into multiple files and include the containing directory, but this failed with errors about duplicate keys- the name of the containing object. So, for some reason, I could do this with host but not with my custom field set?
I was trying to do this because I have created a single custom field set but I would like to only use subsets of that for different index templates. Initially I thought I could achieve that by generating different templates using a variety of --subset files, but the problem is that the component template files are shared (have the same names) across multiple composable templates, directly related to the source field set file.
At the moment it seems my only option is to have separate field set files, and therefore different top level object names. Is there a way to break up a field set into multiple files?

**Comment by phil-dotchon** [comment]
For example, if I create the following file and save it in my own schema directory, I can --include that directory and the custom fields are added:
`---
- name: test1
  title: Test1
  group: 2
  short: Fields 
  description: >
    A Test 1
  type: group
  fields:
    - name: actrlPfxEntry_count1
      level: extended
      type: unsigned_long
      short: ACL prefix entry count.
      description: >
        ACL prefix entry count.

`
If I then add another file in the same directory as follows:

`---
- name: test1
  title: Test1
  group: 2
  short: Fields 
  description: >
    A Test 1
  type: group
  fields:
    - name: actrlPfxEntry_count2
      level: extended
      type: unsigned_long
      short: ACL prefix entry count.
      description: >
        ACL prefix entry count.

`
I get an error:

`Traceback (most recent call last):
  File "./scripts/generator.py", line 133, in <module>
    main()
  File "./scripts/generator.py", line 68, in main
    fields: dict[str, FieldEntry] = loader.load_schemas(ref=args.ref, included_files=args.include)
  File "/home/lc5648734/ecs/scripts/schema/loader.py", line 100, in load_schemas
    custom_fields: Dict[str, FieldEntry] = deep_nesting_representation(load_schema_files(custom_files))
  File "/home/lc5648734/ecs/scripts/schema/loader.py", line 109, in load_schema_files
    fields_nested = ecs_helpers.safe_merge_dicts(fields_nested, new_fields)
  File "/home/lc5648734/ecs/scripts/generators/ecs_helpers.py", line 107, in safe_merge_dicts
    raise ValueError('Duplicate key found when merging dictionaries: {0}'.format(key))
ValueError: Duplicate key found when merging dictionaries: test1`

This happens even if I put the second file into a different directory and --include them both. If, however, I move the second file into the standard ECS schema folder instead, then the two files are successfully merged and my (legacy) schema files looks like this:
`      "test1": {
        "properties": {
          "actrlPfxEntry_count1": {
            "type": "unsigned_long"
          },
          "actrlPfxEntry_count2": {
            "type": "unsigned_long"
          }
        }
      }`

**Comment by phil-dotchon** [comment]
Although, now I check, I see that the composable template still only has the 'test1' file listed in the 'composed_of' array, so the above didn't really work

**Comment by kgeller** [comment]
@phil-dotchon Currently we only have support for 1 file per fieldset. Is there a reason for wanting the same fieldset name duplicated? 

Also, just in case you haven't seen it, we have some [guidelines for custom fields](https://www.elastic.co/guide/en/ecs/current/ecs-custom-fields-in-ecs.html).

**Comment by kgeller** [comment]
@phil-dotchon I see. As far as I know, our tooling doesn't currently support that kind of usage.
