### ISSUE TITLE
host vs obsever

### ISSUE THREAD

**Issue by anubisg1** [elastic/ecs#2126]
This wants to be a follow up to https://github.com/elastic/ecs/issues/607

to summarize the following pictures help understand the difference between host/agent/observer

![image](https://user-images.githubusercontent.com/4518931/209944323-6428bf08-be71-4a8f-aff6-2589e4976207.png)

![image](https://user-images.githubusercontent.com/4518931/209944341-8923159c-9eb2-4781-9939-5d89a8c762e2.png)

unfortunately a lot of confusion.. for example...

If a device like firewalls, switches, routers, LoadBalancers and more send syslog messages directly to logstash, what will those devices be? Host, observer, maybe actually both?

also, looking at firewalls... they generate traffic logs and system logs...
in that case then what? the firewall is the host for system logs? (i.e logs related to the firewall itself, for example psu failures, login activities, policies changes) but and observer for traffic logs ?

finally why would an observer have a type and vendor while a host does not?

**Comment by MikePaquette** [comment]
Hi @anubisg1 thanks for the questions and feedback.  Please let me try to provide some clarification.

> If a device like firewalls, switches, routers, LoadBalancers and more send syslog messages directly to logstash, what will those devices be? Host, observer, maybe actually both?

The proper ECS field sets into which to populate the device details depends upon the class of event that is being sent.

If the event is something that the firewall/switch/router/loadbalancer _observes_, (e.g., a network event that is seen, allowed, or blocked, a routing table that is updated, a switch that enforces an 802.1x failure, an LB that drops a back-end connection, etc.) then the firewall/switch/router/loadbalancer is the _observer_.

If the event is describing something that happens _on_ the firewall/switch/router/loadbalancer itself, (e.g., high-CPU on the device, management configuration changed on the device, over-temp sensor on the device, etc.) then the firewall/switch/router/loadbalancer is the _host_.

> also, looking at firewalls... they generate traffic logs and system logs...
> in that case then what? the firewall is the host for system logs? (i.e logs related to the firewall itself, for example psu failures, login activities, policies changes) but and observer for traffic logs ?

Yes, exactly.

> finally why would an observer have a type and vendor while a host does not?

Good question. ECS does define a `host.type` field [here](https://www.elastic.co/guide/en/ecs/current/ecs-host.html#field-host-type) that is used to track the type of host, but there is not a `host.vendor` field.  

One idea for the future (NOT yet part of ECS) is to create a set of `asset.*` fields that could be applied to every kind of system/device/host/asset that would include an `asset.vendor` field.  

However, for common network observers like firewalls/switches/routers/loadbalancers, it is quite common for analysts to want to sort/filter logs based on the vendor (e.g., "show only Cisco Firewall logs",  "don't show my Palo Alto logs", etc.) so we included the `observer.vendor field` already.

Hope this makes sense for you.

**Comment by anubisg1** [comment]
> Hope this makes sense for you.

Yes it does, thank you.

**Comment by ebeahan** [comment]
Thanks for the detailed response, @MikePaquette!
