### ISSUE TITLE
`log.level` field description should have better examples

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/ecs#2128]
**Kibana version:**  8.0 beta-1 BC-2 Kibana Cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
BUILD: 47855
COMMIT: e620fec0876b012b86bff0c7f8588a3a5e5bf8b6
```

**Preconditions:**
1. 8.0 beta-1 BC-2 Kibana Cloud environment should be available.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Nginx integration overview page.
3. Observe `Exported fields`- log.level description is incomplete.

**Expected Result:**
Description should be for `Exported fields`- log.level under Nginx integration overview page.
- `Some examples are warn, err, i, informational.` would be better as `warn, error, info, debug` as that is more commonly used.

The description for this field is defined at:
https://github.com/elastic/ecs/blob/4b3fe9a6db948b2e06b3968007bf0ba690ee02b4/generated/beats/fields.ecs.yml#L4350

**Screenshot:**
![4](https://user-images.githubusercontent.com/77374876/140723150-378c98ac-64f3-44bc-91ea-a930cd7fb908.JPG)

**Comment by kgeller** [comment]
The description in question is simply a list of examples for the `log.level` field, so I don't believe we have a bug here.

Feel free to re-open if we think there is more discussion to be had here.
