### ISSUE TITLE
Adding timezone support in ECS

### ISSUE THREAD

**Issue by webmat** [elastic/ecs#213]
ECS is currently missing timezone support.

We used to have fields where the value should be defined as a differential in seconds, which we agreed to [remove](https://github.com/elastic/ecs/pull/134), as it was not very friendly (`device.timezone.offset.sec` and `host.timezone.offset.sec`).

In order to re-introduce the timezone, we need to pick a field name, and what values we support in there.

Fun facts:

- Beats can either output:
  - a time differential in hh:mm format (e.g. `-05:00`)
  - or in abbreviated form (e.g. `EST`).
- Ingest Node supports at least 3 input formats:
  - time differentials in hh:mm format
  - abbreviated timezones
  - canonical timezones (e.g. `Europe/Amsterdam`)
- Logstash's date filter supports 2 formats, according to the docs:
  - time differentials in hh:mm format
  - canonical timezones (e.g. `Europe/Amsterdam`)

Here are a few questions that could help shape the direction here:

- [ ] Can someone confirm whether Beats emits the correct time differential immediately after DST changes?
- [x] Should we limit which format goes into the timezone field to only one format, or let people use their preferred format, as long as it's one of the 3?
- [x] What field name(s) seem more appropriate?

@MikePaquette @ruflin @andrewkroh

**Comment by webmat** [comment]
My thoughts on the questions:

- Field name: `host.timezone` and `device.timezone` (soon likely to become `observer.timezone`) right now. We may have to define `container.timezone` as well.
- Format:
  - I think limiting to one makes for better looking data in general, but I'm worried the various sources will not necessarily support our arbitrary pick out of the box, which may complicate adoption outside of Beats. Although we can always compensate with a small Ingest Node pipeline.
  - My favourite is the abbreviated format, if we are to pick only one.

I'm not the right person to figure out the time differential adjustment on DST change.

**Comment by webmat** [comment]
Well Ingest Node supports the 3 formats, so perhaps we can leave this open ended for now.

Actually, would people care if their event stream has a mix of timezone formats? I think they're useful mostly to adjust timestamps. I don't think people do aggregations on them or visualize them. It's just a low level bit of information meant for the pipeline to interpret the date correctly.

**Comment by ruflin** [comment]
If it's mainly for the pipeline, should we even have it in ECS?

**Comment by webmat** [comment]
Well in some pretty big use cases like default syslog messages, you don't get a full timestamp that includes the timezone.

So we've come up with workarounds like combining Beats' `add_locale` ([example](https://github.com/elastic/beats/blob/master/filebeat/module/system/syslog/config/syslog.yml#L10-L13)) processor and using that field in Ingest Node ([example](https://github.com/elastic/beats/blob/master/filebeat/module/system/syslog/ingest/pipeline.json#L37-L39)) to properly interpret the timestamp. I'd say it's pretty important that we support it in ECS. I'm sure there's more cases that would benefit from having the timestamp.

It doesn't need to be a core field, though. Most modern solutions don't make that mistake and have complete timestamps.

**Comment by webmat** [comment]
What do you think about this, @MikePaquette ?

**Comment by webmat** [comment]
Awesome. Will get that going shortly. I agree with `event.timestamp`
