### ISSUE TITLE
Question: How do we put the ECS “Lego Blocks” together? 

### ISSUE THREAD

**Issue by MikePaquette** [elastic/ecs#218]
You’ve got all these interesting and useful “lego blocks” (aka "field groups"? Probably worth coming up with a defined term for this concept, in order to avoid confusion), but from the documentation, it’s not clear how they will all be put together.  We could see a number of ways they could be constructed, but I’m sure the designers have specific ways in mind, here.   What is the hierarchy of “field groups” - how are they related?  We’re missing a complete example JSON documents which show how the sections are related together.

No. 1 of 16.  This question was asked by a new ECS user,  who is familiar with mapping IT events to data models and use cases in other schemas.  These questions are being posted as a GitHub issue, because a) they may offer valuable insights.  b) we expect that many new users will have similar questions.

**Comment by MikePaquette** [comment]
See #219 for some definitions to get started.

If you are implementing a transformation from an existing event format to ECS, the high-level:

1. Identify the Log type
2. Get the spec
3. Understand the closest ECS scenario (TBD)
4. Perform the logical field mappings
- Map your log fields to ECS core fields
- Populate other ECS core fields
- Map your log fields to ECS extended fields
6. Write your transform function (e.g., Logstash, Ingest Node, etc.)
7. Create your Index Templates
8. Get example Logs
9. Run through transform
10. Search, visualize, analyze

**Comment by ebeahan** [comment]
Field sets have become a defined concept in ECS, and these general concepts are better defined now that ECS has matured.
