### ISSUE TITLE
Remove mapping for field `faas.trigger`

### ISSUE THREAD

**Issue by gsantoro** [elastic/ecs#2192]
**Summary**

I would like to remove the mapping for the field `faas.trigger` of type `nested`.

**Motivation**:

- The field faas.trigger can only accept a single object like you can see in the apm code at [here](https://github.com/elastic/apm-agent-java/blob/be3870b03e33e670edaaae35ba0f3584ff3984f2/apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Faas.java#L41)
- Nested documents and queries are typically expensive
- the field `faas.trigger` is an object in ECS but it maps to a single string in Otel like documented at [issue](https://github.com/elastic/ecs/issues/1516#issuecomment-904365116) and in the Otel [docs](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/faas.md#incoming-invocations)
- Avoiding unnecessary `nested` fields should make it easier to support `subobjects: false` in the project Logs+ for default o11y mappings. 

**Detailed Design**:

Provide additional details around the design of the proposed changes.

* Field names: `faas.trigger`
* Example values for the fields

```json
"trigger": {
          "request_id": "10",
          "type": "http"
      }
  }
```

* Suggested appropriate datatypes

suggested mapping. Notice the change 

```json
{
    "mappings": {
        "properties": {
            "faas": {
                "type": "object"
            },
            "mappings": {
                "properties": {
                    "trigger": {
                        "type": "object"
                    },
                    "mappings": {
                        "properties": {
                            "request_id": {
                                "type": "keyword"
                            },
                            "type": {
                                "type": "keyword"
                            }
                        }
                    }
                }
            }
        }
    }
}
```

* Any example events that map to the proposed use case(s)

```json
{
    "faas": {
        "trigger": {
            "request_id": "10",
            "type": "http"
        }
    }
}
```

or 

```json
{
    "faas.trigger.request_id": "10",
    "faas.trigger.type": "http"
}
```

**Comment by ebeahan** [comment]
Can we incorporate this change and feedback into a Stage 3 PR for the [`faas.*` RFC](https://github.com/elastic/ecs/blob/main/rfcs/text/0027-faas-fields.md)? Seems like a sensible change we want to incorporate before making the `faas.*` fields GA in the schema, and it'd be great to advance and finalize that RFC.

**Comment by gsantoro** [comment]
hello @ebeahan , after a discussion with @AlexanderWert we are thinking to add the change into stage 2 still to prevent to go GA yet.

**Comment by felixbarny** [comment]
After the ECS changes get merged, please also adjust the dynamic ECS mappings in elastic-package: https://github.com/elastic/elastic-package/blob/6904fbc9f58d4f967819d09f71675637e47391a6/internal/builder/_static/ecs_mappings.yaml#L450-L453
