### ISSUE TITLE
Question: Can Elasticsearch notify sender when new data arrives?

### ISSUE THREAD

**Issue by MikePaquette** [elastic/ecs#221]
When new records are “mapped” to ECS, can we have ElasticSearch make a web hook call to be notified that new data has arrived?  Or would we have to poll periodically, when new data is correctly mapped?  (In the call, you mentioned Elastic has an alerting mechanism we could use for this -- if you have a link to this documentation, we'd appreciate it.)

No. 4 of 16.  This question was asked by a new ECS user,  who is familiar with mapping IT events to data models and use cases in other schemas.  These questions are being posted as a GitHub issue, because a) they may offer valuable insights.  b) we expect that many new users will have similar questions.

**Comment by MikePaquette** [comment]
We need to define what is meant by "new data has arrived."  This could be:

- new documents in an existing Elasticsearch Index
- a new Index was created
- a new index was created with an new index mapping template
- a non-confirming (definition TBD) document or index has been ingested

**Comment by ebeahan** [comment]
Outside of ECS scope.

**Comment by jamiehynds** [comment]
@mostlyjason may be an interesting ER for Fleet - notifying a user if an empty datastream suddenly begins populating, or a new datastream is created.
