### ISSUE TITLE
Typo in changelog for 8.8.0

### ISSUE THREAD

**Issue by wallrik** [elastic/ecs#2214]
I would submit a PR, but I'm not sure which files and asciidocs and such you would want changed.

I was struggling a lot to understand the first bullet point in the changelog until I realized it was written incorrectly.

https://github.com/elastic/ecs/blob/462b9e5ba80a38d48e5a4a5e14d65726956e512d/CHANGELOG.md?plain=1#L12

The referenced PR was titled: Permit `event.type: access` for `event.category: file` events 😊

**Comment by kgeller** [comment]
A fix was merged in the PR linked above, so I am closing this issue. Feel to re-open if you think there's more to discuss here.
