### ISSUE TITLE
Question: Datatypes defined?

### ISSUE THREAD

**Issue by MikePaquette** [elastic/ecs#222]
What are all the possible “datatypes” defined?

No. 5 of 16.  This question was asked by a new ECS user,  who is familiar with mapping IT events to data models and use cases in other schemas.  These questions are being posted as a GitHub issue, because a) they may offer valuable insights.  b) we expect that many new users will have similar questions.

**Comment by MikePaquette** [comment]
The Elasticsearch field datatypes are defined in Elasticsearch documentation at:
https://www.elastic.co/guide/en/elasticsearch/reference/6.5/mapping-types.html

**Comment by ebeahan** [comment]
Covered in the schema spec and the docs: https://www.elastic.co/guide/en/ecs/current/ecs-faq.html#type-interop
