### ISSUE TITLE
Question: how do we tag users with org or business unit? 

### ISSUE THREAD

**Issue by MikePaquette** [elastic/ecs#224]
user.tag is missing? (to describe organization or business unit) — maybe part of the “organization” building block?

No. 7 of 16.  This question was asked by a new ECS user,  who is familiar with mapping IT events to data models and use cases in other schemas.  These questions are being posted as a GitHub issue, because a) they may offer valuable insights.  b) we expect that many new users will have similar questions.

**Comment by MikePaquette** [comment]
The `organization.*` field are intended to be used for the organization associated with the event, not specifically the user.

Would the `user.group` field be sufficient for your purposes?

**Comment by webmat** [comment]
I'm thinking we could come up with guidance on how to represent organizational details.

However different orgs may have different enough requirements to make it near impossible to cover all use cases. Think the amounts of levels and business units in the largest orgs, the strategy to perform segregation of rights per users (which likely varies per business unit), etc.

For this reason, I'm not sure we can come up with a set of fields that can capture all scenarios. We are likely missing a few basic fields, so we could do a bit more. But I think a big part of capturing organizational details will have to be left to the users, hopefully with some guidance from ECS.

**Comment by djptek** [comment]
We'd recommend this to be achieved using out toolset for adding custom tools, since every org may have their own unique means of identifying entities within their organisational structure, closing
