### ISSUE TITLE
Question: Is there a network.duration field?

### ISSUE THREAD

**Issue by MikePaquette** [elastic/ecs#225]
network.duration field missing?  Or is that considered part of event.duration?

No. 8 of 16.  This question was asked by a new ECS user,  who is familiar with mapping IT events to data models and use cases in other schemas.  These questions are being posted as a GitHub issue, because a) they may offer valuable insights.  b) we expect that many new users will have similar questions.

**Comment by MikePaquette** [comment]
Yes, our thinking so far is that event.duration would be populated with the network duration for network flow/session events.

**Comment by webmat** [comment]
I also tend to think that the standard "response time" metric when analyzing HTTP access logs should map to `event.duration`.
