### ISSUE TITLE
Need related event field?

### ISSUE THREAD

**Issue by MikePaquette** [elastic/ecs#228]
Need an event.related_id, which would include a pointer to earlier related events for an issue (ex. Windows Event Logs).

No. 11 of 16.  This question was asked by a new ECS user,  who is familiar with mapping IT events to data models and use cases in other schemas.  These questions are being posted as a GitHub issue, because a) they may offer valuable insights.  b) we expect that many new users will have similar questions.

**Comment by MikePaquette** [comment]
This is a good idea.
We should discuss whether this fits better under the `related.*` [fields](https://github.com/elastic/ecs/blob/master/README.md#related), where it could be an array that would allow for multiple related events.
Perhaps as `related.event_id`

This might be more consistent with the other uses of `related.*`

**Comment by webmat** [comment]
In my mind, the `related.*` field set is specifically to group all values of one event in one field, to make sure it's easy to find "any event involving a given IP/username/hostname/..."

I would tend to think that the semantics of referring to a previous event are different, however. I think I'd rather see previous events referred to as a field on `event`. Perhaps `event.previous_id` or `event.related_id`. I would love to hear more about the scenario(s) in question where this happens, the semantics of this relationship, see what the data looks like, etc.

For example: is it a chain of relations to the previous event (and the previous event may also optionally point to one previous event)? Is it a growing array of all the previous related events?

I could see partial and final network flows needing this. I wonder if this comes up in other situations as well.

**Comment by djptek** [comment]
This is being discussed here: https://github.com/elastic/ecs/issues/1547 under correlated events, closing
