### ISSUE TITLE
Support for calculated fields

### ISSUE THREAD

**Issue by MikePaquette** [elastic/ecs#229]
Supporting calculated fields would be helpful, like event.read_skew = event.created - @timestamp (in milliseconds)

No. 12 of 16.  This question was asked by a new ECS user,  who is familiar with mapping IT events to data models and use cases in other schemas.  These questions are being posted as a GitHub issue, because a) they may offer valuable insights.  b) we expect that many new users will have similar questions.

**Comment by MikePaquette** [comment]
Generally, ECS does not specify "how" its defined fields are populated.  Producing an ECS-compliant event may require one or more transformations of event fields which can be performed during the ingestion process (at the shipper, ETL, or Ingest node) or subsequently by modifications to documents in Elasticsearch.  At any of these points, a "calculation" may be done to derive the optimal value of the field.
So i would say that ECS today supports (or at least does nothing to exclude the use of) calculated fields.

All that said, the specific calculated field `event.read_skew`  sounds like a useful idea, and I wouldn't be opposed to adding this as an "extended" field.

What other "calculated" fields are important?

**Comment by djptek** [comment]
Calculating fields using an existing data item as input can be achieved downstream in index nodes &/or using runtime fields, so this data can be generated ad-hoc after the fact.

Closing please feel free to reopen
