### ISSUE TITLE
How to represent Auth Logs in ECS?

### ISSUE THREAD

**Issue by MikePaquette** [elastic/ecs#230]
How would you represent Authentication logs in ECS?  What would that look like?  Perhaps as an “event”? (According to the call, this seems correct.)

No. 13 of 16.  This question was asked by a new ECS user,  who is familiar with mapping IT events to data models and use cases in other schemas.  These questions are being posted as a GitHub issue, because a) they may offer valuable insights.  b) we expect that many new users will have similar questions.

**Comment by MikePaquette** [comment]
Exactly how to represent "authentication logs" is currently undefined, but the general direction is to represent auth log entries as events by populating appropriate values in `event.*` fields, for example:

- event.kind: "event"
- event.category:  TBD
- event.action: TBD
- event.outcome: "success"
- and other event.* fields, as appropriate

For example: Linux auth logs (/var/log/auth.log)
`Feb 24 09:19:55 precise32 groupadd[7996]: group added to /etc/group: name=mysql, GID=111`

**Comment by kgeller** [comment]
We think this is well captured in ECS today. Closing this issue for now.
