### ISSUE TITLE
How are changes represented in ECS?

### ISSUE THREAD

**Issue by MikePaquette** [elastic/ecs#231]
How would you represent “changes” in ECS?  Like file changes, registry changes, infrastructure changes?  Perhaps as an “event”?

No. 14 of 16.  This question was asked by a new ECS user,  who is familiar with mapping IT events to data models and use cases in other schemas.  These questions are being posted as a GitHub issue, because a) they may offer valuable insights.  b) we expect that many new users will have similar questions.

**Comment by MikePaquette** [comment]
Exactly how to represent "changes" is currently undefined, but the general direction is to represent change events by populating appropriate values in:
`event.category`  (for example, there could be a "changes" category defined)
`event.action`
`event.outcome`

and other `event.*` fields.

**Comment by djptek** [comment]
Where we record state, the change is implicit in an update to this state 

Where we record events, the change is recorded in the event

Closing, please feel free to reopen.
