### ISSUE TITLE
Question: Where to map process image path?

### ISSUE THREAD

**Issue by MikePaquette** [elastic/ecs#233]
Where would the process image path (absolute) be stored?  (e.g., "C:\path\to\foo.exe" or "/opt/bin/foo")

No. 16 of 16.  This question was asked by a new ECS user,  who is familiar with mapping IT events to data models and use cases in other schemas.  These questions are being posted as a GitHub issue, because a) they may offer valuable insights.  b) we expect that many new users will have similar questions.

**Comment by andrewkroh** [comment]
There is a `process.executable` field for this.

**Comment by latundetoks** [comment]
Some events have the notion of `source.process` and `destination.process` within the same events.
`process.executable` alone would not be sufficient here.

Would suggest, 
`source.process.executable`
`destination.process.executable`

**Comment by webmat** [comment]
@latundetoks You're seeing this in which scenarios? What event sources?

**Comment by d-almeida** [comment]
McAfee DLP also has this similar behavior. For example:

`"sourceprocessname": "c:\program files (x86)\microsoft office\office15\outlook.exe"`
`"targetprocessname": "c:\program files (x86)\microsoft office\office15\outlook.exe"`

**Comment by ebeahan** [comment]
There is another discussion (#809) for adopting nesting to the `user.*` field set (e.g. `user.target.*`) that could be investigated for the source/target process use case mentioned here. If we imagine adopting the same approach applying to `process.*`, the proposed `source.process.*` could become the top-level `process.*` and `process.target.*` could be a nested process object to represent `destination.process.*`:

```json
{
  "process": {
    "name": "svchost.exe",
    "target": {
      "name": "WerFault.exe"
    }
  }
}
```

There's no active effort on adopting these `process` nesting into ECS, but we'd welcome an issue or an [RFC proposal](https://github.com/elastic/ecs/blob/master/rfcs/README.md) to start the discussion :-)

**Comment by ebeahan** [comment]
> There's no active effort on adopting these process nesting into ECS, but we'd welcome an issue or an RFC proposal to start the discussion :-)

ECS [RFC 0016](https://github.com/elastic/ecs/blob/main/rfcs/text/0016-target-process.md) was opened a while back to pursue this idea of `process.target.*` reuses to model one process targeting another.

However, the work has [paused](https://github.com/elastic/ecs/pull/1666) for now. If there's any interest to continue, let's discuss this through the RFC process.
