### ISSUE TITLE
ECS Tooling - Mapping & Template Settings

### ISSUE THREAD

**Issue by daniel-rhoades** [elastic/ecs#2342]
Within [USAGE.md (line 402 - Mapping & Template Settings)](https://github.com/elastic/ecs/blob/4b2c7c6c4596b8d4acdd420907952a04e20c8c23/USAGE.md?plain=1#L402), it describes how to specify a template file:

> The `--template-settings-legacy` argument defines [index level settings (https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#index-modules-settings) that will be applied to the legacy index template in the generated artifacts. The `--template-settings` argument now defines those same settings, but for the composable template in the generated artifacts.
>
>This is an example `template.json` to be passed with `--template-setting-legacy`:
>
>
> ```json
> {
>   "index_patterns": ["mylog-*"],
>   "order": 1,
>   "settings": {
>     "index": {
>       "mapping": {
>         "total_fields": {
>           "limit": 10000
>         }
>       },
>       "refresh_interval": "1s"
>     }
>   },
>   "mappings": {}
> }
> ```
>
> 
> [...]
> 
> For `template.json`, the `mappings` object is left empty: `{}`. Likewise the `properties` object remains empty in the `mapping.json` example. This will be filled in automatically by the script.

However, using the example (given for `--template-setting-legacy`) for `--template` causes the ECS Tooling to error:

```
...
 File "[...]/ecs/scripts/generators/es_template.py", line 263, in finalize_template
    template['template']['mappings'] = mappings_section
KeyError: 'template'
```

Wrapping `settings` within a `template` element resolves the issue, since this would then be compliant with the standard index template schema.

If this behaviour is expected, perhaps the documentation just updating.

**Comment by mjwolf** [comment]
Hi @daniel-rhoades, thanks for finding this. The given example in the documentation is incorrect, [this](https://github.com/elastic/ecs/pull/2412) will fix it
