### ISSUE TITLE
LogsDB compatibility: specify if the ordering of arrays needs to be preserved

### ISSUE THREAD

**Issue by felixbarny** [elastic/ecs#2372]
We're about to roll out LogsDB for all integrations. LogsDB uses synthetic _source. The result is that _source may differ from the original one in [several ways](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-source-field.html#synthetic-source-modifications). For example, the ordering of arrays is not preserved and values in an array are de-duplicated (internally arrays are stored in a sorted set).

I'd like to propose that ECS defines which for which fields the ordering is important, so that [`store_array_source`](https://github.com/elastic/elasticsearch/pull/108417) should be enabled. This comes with a storage overhead but allows us to return the original values.

An example for a field where the ordering is important is `process.args`:

https://github.com/elastic/ecs/blob/53765702d7036414a520b87bbe7b8a12b1e7be30/schemas/process.yml#L143-L153

The ordering isn't always important. For example, I'd consider the storage tradeoff for `process.thread.capabilities.permitted` to not be worth it. What matters here is the set of capabilities a thread permits, not in which order.

https://github.com/elastic/ecs/blob/53765702d7036414a520b87bbe7b8a12b1e7be30/schemas/process.yml#L205-L215

**Comment by ruflin** [comment]
++ on the idea that Elasticsearch is smart about if a field contains an array or not and how to store it. If you send an array, ordering is preserved without having to specify any special mappings. This also ensures users don't have to learn about any new concept.

**Comment by andrewkroh** [comment]
> ++ on the idea that Elasticsearch is smart about if a field contains an array or not and how to store it. If you send an array, ordering is preserved without having to specify any special mappings. This also ensures users don't have to learn about any new concept.

👍 

I like this approach. Then we turn the question around, and ask which ECS array fields can we optimize by never storing source because they are truly sets.

**Comment by andrewkroh** [comment]
Closing in favor of https://github.com/elastic/ecs/issues/2376 because the approach changed to opt-in.
