### ISSUE TITLE
Non-indexed fields should show they are not indexed in the readme

### ISSUE THREAD

**Issue by webmat** [elastic/ecs#250]
We just noticed that fields like `event.original`, which is set to `index: false` still renders as `type: keyword` in the readme.

We must fix this rendering issue for Beta 2.

**Comment by MikePaquette** [comment]
+1 to making indexing status clear in the readme. Not sure I'd burn a column for this though, since there will be very few fields with this setting.  Are you thinking just a text note added to the description?
