### ISSUE TITLE
Fields that contain protocol names like should have normalized capitalization

### ISSUE THREAD

**Issue by webmat** [elastic/ecs#251]
I think lowecase would make sense. Thoughts?

Fields in question:

- network.transport
- network.type
- network.application
- network.protocol

**Comment by webmat** [comment]
Ping @andrewkroh @adriansr

**Comment by adriansr** [comment]
+1 to lowercase

**Comment by MikePaquette** [comment]
+1 for normalizing case of these fields to lowercase.  This is related to https://github.com/elastic/ecs/issues/220 where this restriction could be included in a validation column in the ECS specification, perhaps with Regex for the check.

**Comment by andrewkroh** [comment]
Applying a normalizer in the generated template would be a nice addition because it would normalize both the ingested data and the search queries from users.

**Comment by ruflin** [comment]
I like this idea. We could make this as part of our template.

**Comment by andrewkroh** [comment]
I created https://github.com/elastic/ecs/issues/260.
