### ISSUE TITLE
Introduce a field for the domain without subdomains

### ISSUE THREAD

**Issue by webmat** [elastic/ecs#267]
This issue is meant to replace a pretty old PR (#163) based on an outdated version of ECS.

**Comment by dainperkins** [comment]
so going thru this with url.domain - it doesn't really make sense as domain is a thing (a little ambiguous given sub domains, etc) but the url.domain is specifically referencing the fully qualified domain name of a give host (blah.sub.domain.tld).  Its also very interesting to analyse hostname metrics, domain metrics, etc discreetly...

how about something like (and as a reusable class this might make the most sense to be able to assign naming structures to source, dest, client, server, host, etc.
fqdn   fully qualified hostname  e.g. www.dev.part.google.co.uk
tld:     top level domain                   e.g. co
ccd:   country code domain           e.g. uk
sld:     second level domain .          e.g. google
subdomains: array                         [dev,part] . (maybe easier to deal with as multiple discrete fields)
hostname: hostname                    www

used when logging any url access (e.g. proxy or fw...) or for enrichment (likely specifically to internal hosts)

**Comment by neu5ron** [comment]
so here is an example I had for mappings for domain additions.
https://github.com/rocknsm/rock-dashboards/blob/ecs-bro_and_suricata/ecs-configuration/elasticsearch/ecs-custom-field-domain.json
https://github.com/rocknsm/rock-dashboards/blob/ecs-bro_and_suricata/ecs-configuration/logstash/conf.d/logstash-816-filter-destination_domain-enrich.conf

splits each level into its own name field and length.
ex: sample.www.google.com
domain.level_1.name:com
domain.level_1.length:3
domain.levele_2.name:google
and so on

combines 1st+2nd and 1st+2nd+3rd:
domain.1n2name:google.com
domain.1n2n3name:www.google.com

I know tld has always been a thing, but it just doesn’t allow to create many levels after the 3rd. ie: really only have tld and stld that are commonly used, and that leaves all the other domains out to dry :)

**Comment by dainperkins** [comment]
I had to nest a few ifs getting tld to handle more than (tld, sld,3rd,
4th.....plus hostname), which was a pain!

I like the idea of including length as it can be useful for ML and probably
a whole lot more, but I'd prefer to see the data named by standard
reference (fqdn, hostname, tld, sld, 3ld, 4ld... maybe numbered
subdomains?) tho that might be the sort of thing defined under a separate
re-useable header (Features?) . (length, digit ratio, levenstein dist
memchached computed against specific dictionaries, etc)

wish I'd have thought of just splitting the 5 or 6 level AV domains with
"."s . :)

**Comment by dainperkins** [comment]
One thing that comes to mind from e.g. security analysis & ML perspectives is the idea of cutting up the domains and adding features that can be analyzed to identify anomalous domains.  tld / eld ( length / digit ratio, etc)  Could be useful for urls as well as domains (from e.,g. firewall /proxy / dns logs)

**Comment by dainperkins** [comment]
I just deleted the wrong comment... oh well

TLD was a pain (had to nest a few ifs to make it work)

The only real issue I see with the naming is not referencing actual domain levels (country code, tld, sld, etc) e.g. mixing country code (.uk) with .com/edu/net) will sku analysis

**Comment by webmat** [comment]
Just went to the attic, looking for something, and I found this opened issue.

This has been solved in ECS 1.2 with https://github.com/elastic/ecs/pull/533

Closing.
