### ISSUE TITLE
WIP: Convert ECS doc from MD to asciidoc guide

### ISSUE THREAD

**Issue by karenzone** [elastic/ecs#276]
Convert ECS readme.md file to asciidoc to be published at https://www.elastic.co/guide/index.html.

Moving ToDo items out of PR #266 into a new issue
- [ ] Move existing content and fix formatting (WIP)
- [ ] Add new content
- [ ] Figure out `make` content generation from schema files

WIP: https://ecs-simple.firebaseapp.com/

**Comment by webmat** [comment]
Closing this, as we completed this migration in April 2019 :-)
