### ISSUE TITLE
Align ECS fields.yml structure and Beats fields.yml structure

### ISSUE THREAD

**Issue by ruflin** [elastic/ecs#292]
The ECS fields.yml structure is almost identical to the Beats fields.yml structure. There is one hack we introduce for the base fields to also have there some documentation headers. The two file structures should be unified and we should get rid of the current `base` hack.

**Comment by ruflin** [comment]
@webmat I remember you aligned these?

**Comment by webmat** [comment]
Not sure what this alignment thing is about.

If the file as it is in `generated/beats/` and in the Beats repo is fine, I guess we can close it.
