### ISSUE TITLE
Improve handling of array fields

### ISSUE THREAD

**Issue by webmat** [elastic/ecs#297]
Some fields should always be arrays, such as `process.args`.

We should add support for this in the field definitions files and identify whether other fields should be flagged as arrays as well.

Finally, we should determine which generated file will use this information. At first glance, I would say potentially the readme, definitely gocodegen, and potentially the schema.json file.

**Comment by ebeahan** [comment]
Addressed in https://github.com/elastic/ecs/pull/727
