### ISSUE TITLE
`user.group` should not be a keyword field, but a place where we can nest the `group` field set

### ISSUE THREAD

**Issue by webmat** [elastic/ecs#304]
The current definition of the field `user.group` is problematic, in that it's a place to put a textual group name. This doesn't leave room for other bits of metadata related to a group (the most obvious one being group.id).

The `user.group` field actually goes against our principle of not reusing the name of a field set (`group`) as a field with a different meaning (`user.group` being a string, rather than the nested field set). 

This issue came up while working on the right way to represent the various users/groups that went into determining effective rights: https://github.com/elastic/beats/pull/10192, https://github.com/elastic/beats/pull/9963 and https://github.com/elastic/beats/issues/10111.

I would like to suggest we make this change for ECS 1.0.0 GA.

Discuss ;-)

cc @ruflin @MikePaquette @cwurm @andrewkroh

**Comment by willemdh** [comment]
Seems perfectly reasonable to make group a reusable object so it can be nested under user.*
```
user.group.name
user.group.id
```
