### ISSUE TITLE
Add field format information to schema

### ISSUE THREAD

**Issue by andrewkroh** [elastic/ecs#305]
It would be nice to supply additional information about formatting that can be used as a hint to anything that renders that field. For example indicate that `client.bytes` is bytes and could be formatted as 10KB or 100GB. Or indicate that `event.duration` is a time value given as nanoseconds.

```
- name: client.bytes
  format: bytes

- name: event.duration
  format: duration
  input_format: nanoseconds
```

Relates: https://github.com/elastic/beats/pull/10184

**Comment by webmat** [comment]
Yes, agreed.

Pretty sure we can include in GA too. It's not a breaking change, just an enhancement.

**Comment by ruflin** [comment]
++ on adding it now and backport.

**Comment by jamiehynds** [comment]
Closing this as was added to ECS.
