### ISSUE TITLE
Allowing bool and numbers for `labels`

### ISSUE THREAD

**Issue by simitt** [elastic/ecs#310]
The current description of `labels` states that the values need to be `keywords`:

> Key/value pairs. Can be used to add meta information to events. Should not contain nested objects. All values are stored as keyword.

Can we extend this to also allow at least `boolean` and `number` values? APM uses labels to allow setting user defined information about events. We already allow keywords, numbers and booleans. Numbers could be used for aggregations on these fields. (see https://github.com/elastic/apm-server/issues/828 for more background).

**Comment by ebeahan** [comment]
I've opened an RFC to start a discussion around this topic: https://github.com/elastic/ecs/pull/1341

Let's capture any new thoughts or feedback in that conversation.
