### ISSUE TITLE
Add fields for the IPv6 Zone ID

### ISSUE THREAD

**Issue by webmat** [elastic/ecs#314]
For reasons discussed in https://github.com/elastic/elasticsearch/issues/38064, the `ip` indexing cannot be adjusted to include support for the Zone ID. Stripping it out is a lossy option, which people are free to do.

But we need to add support for the cases where we want to retain the Zone ID information.

[Section 11.3 of RFC 4007](https://tools.ietf.org/html/rfc4007#section-11.3) shows a few example of the kind of data that can be expected in a Zone ID. It's mostly likely integers ("1" here: `fe80::1234%1`), or network device names ("interface10" here `ff08::9abc%interface10`).

So I suggest we add a sister `.ip_zone` field everywhere we support an `.ip` field. This field should be of datatype `keyword`, and I would have it be an extended field.

**Comment by webmat** [comment]
@randomuserid Would this solve what you were mentioning yesterday?

**Comment by djptek** [comment]
Closing as there has been no recent discussion of this topic, please feel free to reopen
