### ISSUE TITLE
pipeline object?

### ISSUE THREAD

**Issue by willemdh** [elastic/ecs#315]
Atm I'm using an on_failure processor on pipeline filters, which logs errors to `pipeline_error`.

Wouldn't it be useful to have an ecs object pipeline which could hold:

```
pipeline.name
pipeline.error
pipeline.type (logstash|ingest)
```

or is there already a place in ecs for these kind of data?

**Comment by webmat** [comment]
I totally agree!

I see a bigger discussion that needs to happen for this. Here's some things I want to look into:

- Pipeline errors (as opposed to "userland" errors), make sure Ingest Node pipelines don't overwrite legit error.message fields :-) And of course additional metadata as you suggest here.
- Better support for complex pipeline metadata (multiple agents: syslog => beats => logstash => es). Right now I think agent/observer is too rigid
- Pipeline step timings. The "seen" timestamp of everyone in the chain, in an example like above.
- Looping back on the first point: do we need the ability to track pipeline errors for the various steps in the pipeline?

There's likely other things I'm forgetting as well :-)

**Comment by MikePaquette** [comment]
@willemdh @webmat Is it the general rule that the pipeline info is piggybacked onto an existing event, rather than included in a separate out-of-band event?

**Comment by webmat** [comment]
So what I'm outlining above is that I want to make it clearer where pipeline metadata should go, vs the original event's data.

**Comment by MikePaquette** [comment]
Yep, I agree with the approach.  Sounds like a pipeline field set could be a good solution.

**Comment by webmat** [comment]
We created meta-issue #940 to discuss capturing pipeline details in ECS. Closing in favor of the meta issue.
