### ISSUE TITLE
cloud.provider example under Cloud fields

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/ecs#317]
My understanding of cloud.provider should be the name of different cloud providers, like `aws`, `azure` or `gcp`. Under https://github.com/elastic/ecs#cloud, `ec2` is one of the examples for cloud.provider.

**Comment by ruflin** [comment]
For the service part we have `service.type` I think?

**Comment by webmat** [comment]
Good point 🤔

**Comment by ansoni** [comment]
+1 cloud.service

I couldn't find a cloud.type in the yaml file, but personally I think "service" is more concrete.
