### ISSUE TITLE
add file.name 

### ISSUE THREAD

**Issue by bgewin** [elastic/ecs#322]
ECS has a lot of great file fields but one that's very important but seems to be missing is file.name.

Thanks.

**Comment by andrewkroh** [comment]
The `file.path` value includes the name. Or are you asking for a field that is only the last element of path?

**Comment by bgewin** [comment]
Correct.

**Comment by hookhax** [comment]
Yes, please add file.name, the name of the file without the path prepended.

**Comment by ave19** [comment]
I agree, being able to find all the `foo.txt` files regardless of full path is important.  Especially when you're comparing the name to its cryptographic value.

**Comment by webmat** [comment]
I like the idea, I agree this is missing. Noted for the next batch of small tweaks. Of course, a PR is always welcome too :-)

**Comment by webmat** [comment]
Coming shortly. #441 👀
