### ISSUE TITLE
Ability to handle pre-aggregated/coalesced events (event.count)

### ISSUE THREAD

**Issue by zlammers** [elastic/ecs#335]
I believe it is necessary to include a field 'event.count' (or log.count, though I think it fits better in event)

The purpose of this field is simple:  Events can be representative of multiple logs/events.  For example, if you take CEF from ArcSight, you can have a single post-aggregated FW event, which could contain a "aggregatedEventCount" value from ArcSight representing the total count of multiple firewall events aggregated/coalesced into one document in Elasticsearch.

This field could also be used in conjunction with taking alerts from systems (like SIEMs) that generate rule-based alerts off many events, they generally have a count of events that triggered the alert (e.g., count of events related to event.kind:alarm)

Not having this field will throw off any dashboard/visualization that uses a simple doc_count return, instead of a metrics aggs on sum(event.count).  event.count would always be >= 1, so sum(event.count) is always greater than or equal to the doc_count from any aggs.

**Comment by webmat** [comment]
Interesting. We will indeed need to work on support for aggregated events. Although my sense is that this is a little bit ahead from where we are right now, in the development of ECS. We'll keep in mind, for when we get there, however.

Funny enough, another proposal for `event.count` came up very recently. The idea was to use it for event deduplication. E.g. when syslog reports that the previous message was repeated X times. I think using `event.count` for deduplication would be more in line with what people expect.

I also see coalesced events perhaps needing a little more support than adding a single field. What structural support do you typically see for these events? There's a count, but is there also an array of event IDs that made up the coalesced event?

I would assume these coalesced events are typically a different kind of event, like an "alert", which is not in the same event stream as the original events?

**Comment by webmat** [comment]
Actually just making sense of logs in the context of logins requires events to be coalesced, so never mind the last paragraph above :-)

**Comment by zlammers** [comment]
The proposal for `event.count` for deduplication (with your example of syslog 'previous message repeated x times') is the same as mine, at the core - a way to have a single document represent multiple events that are identical [enough] to be considered an additional 'count'.

But, you do bring up an interesting point, as back to my example with ArcSight, it is possible to specify the fields to consider and timing for aggregation to actually occur.  In those cases though, generally the fields that do not contain the same values are lost in the aggregation, though I believe it may be possible to retain the 'first event' values.  So, to answer your question, we do not maintain arrays of coalesced values where they differ - for all intents and purposes, the singular values exported from the SIEM are considered to have been identical across the `event.count` value.

We rely on this functionality quite heavily in our current schema (which is fairly similar to ECS).  I would imagine we save a bit over 2 billion documents a day by storing events with an `event.count > 1` rather than multiple events - which at our current schema is roughly ~2TB of storage per day (and with 90 days retention, that's ~180TB, so quite significant).

The primary difference 'in the end' is that one can never rely fully on `doc_count` to provide an accurate representation of data processed by upstream systems - it's generally enough to get a rough idea, but depending on your level of deduplication/aggregation/coalescing, it's some percentage less - and that means every visualization/dashboard will have to be modified for a `sum(event.count)`, instead of relying on `doc_count`.

**Comment by webmat** [comment]
Ah, thanks for clarifying! I thought you were talking about a rules engine that can detect an event (e.g. "an ssh login") based on multiple different types of events (e.g. ssh logs, pam logs, etc).

If your need is more in line with straightforward deduplication of identical events, then this isn't as far off :-)

**Comment by vbohata** [comment]
+1 for event.count. We need this also for sampled data from Azure app insights (multiple events of the same meaning) and for throttled syslog events.

**Comment by homerjonathan** [comment]
This is a very common field value.  So the alarm could be more serious because the count is high.  Especially if you have pre-processed the data and aggregated the results.  So event.count > 100 is likely more serious then event.count: 1.

**Comment by andrewkroh** [comment]
PAN-OS has a "repeat count" (`repeatcnt`) field that would map nicely to this `event.count` field.

> Number of sessions with same Source IP, Destination IP, Application, and Content/Threat Type seen within 5 seconds.

Relates to https://github.com/elastic/beats/issues/15113.
