### ISSUE TITLE
Root mapping definition has unsupported parameters

### ISSUE THREAD

**Issue by jdoles** [elastic/ecs#337]
I'm not sure if this belongs here or in elasticsearch.
When adding the ECS template.json (version 1.0.0 beta 2) to version 7.0.0 beta 1 of Elasticsearch, I get the following message:

`[2019-02-22T09:57:42,224][DEBUG][o.e.a.a.i.t.p.TransportPutIndexTemplateAction] [SERVER] failed to put template [ecs]
org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [doc : {_meta={version=1.0.0}, dynamic_templates=[{strings_as_keyword={mapping={ignore_above=1024, type=keyword}, match_mapping_type=string}}], date_detection=false, properties={container={properties={image={properties={name={ignore_above=1024, type=keyword}, tag={ignore_above=1024, type=keyword}}}, name={ignore_above=1024, type=keyword}, runtime={ignore_above=1024, type=keyword}, id={ignore_above=1024, type=keyword}, labels={type=object}}}, server={properties={address={ignore_above=1024, type=keyword}, port={type=long}, bytes={type=long}, domain={ignore_above=1024, type=keyword}, ip={type=ip}, mac={ignore_above=1024, type=keyword}, packets={type=long}}}, agent={properties={name={ignore_above=1024, type=keyword}, id={ignore_above=1024, type=keyword}, ephemeral_id={ignore_above=1024, type=keyword}, type={ignore_above=1024, type=keyword}, version={ignore_above=1024, type=keyword}}}, log={properties={original={ignore_above=1024, index=false, type=keyword, doc_values=false}, level={ignore_above=1024, type=keyword}}}, destination={properties={address={ignore_above=1024, type=keyword}, port={type=long}, bytes={type=long}, domain={ignore_above=1024, type=keyword}, ip={type=ip}, mac={ignore_above=1024, type=keyword}, packets={type=long}}}, source={properties={address={ignore_above=1024, type=keyword}, port={type=long}, bytes={type=long}, domain={ignore_above=1024, type=keyword}, ip={type=ip}, mac={ignore_above=1024, type=keyword}, packets={type=long}}}, error={properties={code={ignore_above=1024, type=keyword}, id={ignore_above=1024, type=keyword}, message={norms=false, type=text}}}, network={properties={community_id={ignore_above=1024, type=keyword}, forwarded_ip={type=ip}, protocol={ignore_above=1024, type=keyword}, application={ignore_above=1024, type=keyword}, bytes={type=long}, name={ignore_above=1024, type=keyword}, transport={ignore_above=1024, type=keyword}, type={ignore_above=1024, type=keyword}, iana_number={ignore_above=1024, type=keyword}, packets={type=long}, direction={ignore_above=1024, type=keyword}}}, cloud={properties={availability_zone={ignore_above=1024, type=keyword}, instance={properties={name={ignore_above=1024, type=keyword}, id={ignore_above=1024, type=keyword}}}, provider={ignore_above=1024, type=keyword}, machine={properties={type={ignore_above=1024, type=keyword}}}, region={ignore_above=1024, type=keyword}, account={properties={id={ignore_above=1024, type=keyword}}}}}, geo={properties={continent_name={ignore_above=1024, type=keyword}, region_iso_code={ignore_above=1024, type=keyword}, city_name={ignore_above=1024, type=keyword}, country_iso_code={ignore_above=1024, type=keyword}, country_name={ignore_above=1024, type=keyword}, name={ignore_above=1024, type=keyword}, location={type=geo_point}, region_name={ignore_above=1024, type=keyword}}}, observer={properties={hostname={ignore_above=1024, type=keyword}, vendor={ignore_above=1024, type=keyword}, ip={type=ip}, serial_number={ignore_above=1024, type=keyword}, type={ignore_above=1024, type=keyword}, version={ignore_above=1024, type=keyword}, mac={ignore_above=1024, type=keyword}}}, file={properties={owner={ignore_above=1024, type=keyword}, extension={ignore_above=1024, type=keyword}, gid={ignore_above=1024, type=keyword}, mtime={type=date}, type={ignore_above=1024, type=keyword}, target_path={ignore_above=1024, type=keyword}, inode={ignore_above=1024, type=keyword}, mode={ignore_above=1024, type=keyword}, path={ignore_above=1024, type=keyword}, uid={ignore_above=1024, type=keyword}, size={type=long}, ctime={type=date}, device={ignore_above=1024, type=keyword}, group={ignore_above=1024, type=keyword}}}, ecs={properties={version={ignore_above=1024, type=keyword}}}, related={properties={ip={type=ip}}}, host={properties={hostname={ignore_above=1024, type=keyword}, ip={type=ip}, name={ignore_above=1024, type=keyword}, id={ignore_above=1024, type=keyword}, type={ignore_above=1024, type=keyword}, mac={ignore_above=1024, type=keyword}, architecture={ignore_above=1024, type=keyword}}}, client={properties={address={ignore_above=1024, type=keyword}, port={type=long}, bytes={type=long}, domain={ignore_above=1024, type=keyword}, ip={type=ip}, mac={ignore_above=1024, type=keyword}, packets={type=long}}}, event={properties={severity={type=long}, original={ignore_above=1024, index=false, type=keyword, doc_values=false}, risk_score={type=float}, created={type=date}, kind={ignore_above=1024, type=keyword}, timezone={ignore_above=1024, type=keyword}, module={ignore_above=1024, type=keyword}, start={type=date}, type={ignore_above=1024, type=keyword}, duration={type=long}, risk_score_norm={type=float}, action={ignore_above=1024, type=keyword}, end={type=date}, id={ignore_above=1024, type=keyword}, category={ignore_above=1024, type=keyword}, dataset={ignore_above=1024, type=keyword}, hash={ignore_above=1024, type=keyword}, outcome={ignore_above=1024, type=keyword}}}, user_agent={properties={original={ignore_above=1024, type=keyword}, name={ignore_above=1024, type=keyword}, device={properties={name={ignore_above=1024, type=keyword}}}, version={ignore_above=1024, type=keyword}}}, group={properties={name={ignore_above=1024, type=keyword}, id={ignore_above=1024, type=keyword}}}, process={properties={args={ignore_above=1024, type=keyword}, name={ignore_above=1024, type=keyword}, start={type=date}, pid={type=long}, working_directory={ignore_above=1024, type=keyword}, thread={properties={id={type=long}}}, title={ignore_above=1024, type=keyword}, executable={ignore_above=1024, type=keyword}, ppid={type=long}}}, os={properties={kernel={ignore_above=1024, type=keyword}, name={ignore_above=1024, type=keyword}, family={ignore_above=1024, type=keyword}, version={ignore_above=1024, type=keyword}, platform={ignore_above=1024, type=keyword}, full={ignore_above=1024, type=keyword}}}, message={norms=false, type=text}, url={properties={path={ignore_above=1024, type=keyword}, fragment={ignore_above=1024, type=keyword}, password={ignore_above=1024, type=keyword}, original={ignore_above=1024, type=keyword}, scheme={ignore_above=1024, type=keyword}, port={type=long}, domain={ignore_above=1024, type=keyword}, query={ignore_above=1024, type=keyword}, full={ignore_above=1024, type=keyword}, username={ignore_above=1024, type=keyword}}}, labels={type=object}, tags={ignore_above=1024, type=keyword}, @timestamp={type=date}, service={properties={name={ignore_above=1024, type=keyword}, id={ignore_above=1024, type=keyword}, state={ignore_above=1024, type=keyword}, ephemeral_id={ignore_above=1024, type=keyword}, type={ignore_above=1024, type=keyword}, version={ignore_above=1024, type=keyword}}}, organization={properties={name={ignore_above=1024, type=keyword}, id={ignore_above=1024, type=keyword}}}, http={properties={request={properties={referrer={ignore_above=1024, type=keyword}, method={ignore_above=1024, type=keyword}, bytes={type=long}, body={properties={bytes={type=long}, content={ignore_above=1024, type=keyword}}}}}, response={properties={status_code={type=long}, bytes={type=long}, body={properties={bytes={type=long}, content={ignore_above=1024, type=keyword}}}}}, version={ignore_above=1024, type=keyword}}}, user={properties={full_name={ignore_above=1024, type=keyword}, name={ignore_above=1024, type=keyword}, id={ignore_above=1024, type=keyword}, email={ignore_above=1024, type=keyword}, hash={ignore_above=1024, type=keyword}, group={ignore_above=1024, type=keyword}}}}}]`

This was after I removed the included ECS template that was included with 7.0.0.  I was able to verify that this same template.json works on 6.6.1 without issue.  I can get around this by changing `"doc":` to `"_doc":` and including `?include_type_name=true` with the request.

**Comment by webmat** [comment]
Thanks for reporting, @jdoles. The way the sample template is generated is changing, and I'll have the new generator create one for 6 and one for 7 👍 

While you're playing around with this sample template, I suggest you try out the one you can find in https://github.com/elastic/ecs/pull/336 instead. This one includes definitions for all of the reusable fields. It doesn't include the fix for 6v7 yet, though.

**Comment by jdoles** [comment]
Thanks @webmat .  I'll play around the sample you mentioned.

**Comment by webmat** [comment]
Closing, as the referenced PR has been merged, and the old template has been put in the attic.

Also, short instructions for people keen to play around with the new sample templates for 6 and 7 are on he way in https://github.com/elastic/ecs/pull/346
