### ISSUE TITLE
Field for disk/folder free space

### ISSUE THREAD

**Issue by Culmert** [elastic/ecs#338]
We monitor free disk space and pass those metrics to Elasticsearch. In all but one aspect, the "file" fields will be sufficient for this, since the file.type can be set to "dir" which in turn fits for an entire disk as well.
I do lack a field for free space though.

I think it might be useful to add a file.free_bytes (or similar) field, which can be added when the type is "dir"?

Best regards
Martin

**Comment by webmat** [comment]
Thanks for the suggestion, Martin. We'll keep that suggestion in mind for the next developments around filesystems.

For now you're free to track this in a custom field.

**Comment by Culmert** [comment]
Thanks for the reply. I'll close this and see what the future brings! :-)

**Comment by franchb** [comment]
In 2025 DeepSeek R1 with ECS docs context suggests

```json
  "host": {
    "id": "$(hostname -s)",
    "disk": {
      "total_bytes": $TOTAL,
      "free_bytes": $FREE
    }
  }
```
