### ISSUE TITLE
`body.content` fields should be text instead of keyword

### ISSUE THREAD

**Issue by flexoid** [elastic/ecs#340]
Why `http.request.body.content` and `http.response.body.content` was introduces as `keyword` fields? 

Should they be `text` instead to allow full text search over request and response content? It looks a lot more useful to me.

**Comment by webmat** [comment]
Hey @flexoid I agree full text search is very useful on big fields like the body content of a request.

You should add your `text` datatype as a mutifields. E.g. for `http.request.body.content.text`:

```JSON
```

**Comment by webmat** [comment]
Sorry, I accidentally posted my answer without the example. Check it out on GitHub :-)

The gist is that with very few exceptions, we're going for `keyword` across the board for text, and if we (the ECS team) or users need text indexing on some of these fields, adding it as a nested multi-fields is never a breaking change.

This is a change from:

1. The Elasticsearch default. Elasticsearch being a search engine at its heart, it makes sense to default to full text search indexing. But ECS being for monitoring use cases, it makes sense to always start with `keyword` for aggregations & fast exact matches for filtering & so on.
2. The Beats default was to use `keyword` in as many places as possible, and try to guess which would need `text`, and use that for those fields. This created a situation where a change in needs (from keyword to text or vice versa), would be a breaking change. We wanted to avoid that with ECS.

Hope this makes sense :-)

**Comment by flexoid** [comment]
@webmat thanks for the detailed answer, it definitely makes sense in terms of standardized approach. Now I understand the motivation behind this solution.

Still, I can't imagine the case when request and response body will be used for exact matching or filtering by exact value in real systems. It's not a problem since there will be `body.content.text`, but does it add additional overhead for storing this "useless" keywords, isn't it? Or is it possible to store and index only for example `http.request.body.content.text`, not `http.request.body.content`? I'm not very experienced with ES yet.

**Comment by webmat** [comment]
The overhead is really small, for a few reasons.

For keyword matching, the `keyword` indexing will not happen for anything that's longer than the `ignore_above` parameter. The information will be in your document, but searching for a 1500 char long value via the keyword field (if the cut off is at 1024) would not yield a result. So big HTTP bodies will not be a problem there.

In terms of storage efficiency, the information is compressed in your document bodies, as well as in the mappings. The `keyword` indexing is more lightweight than the `text` indexing in terms of resources, so having it in addition to `text` makes a negligible difference.

But in closing, remember that filtering for something (e.g. the body of a search form or any single field form) will benefit from `keyword` indexing. And if you think about API calls, the HTTP bodies can also be very regular, benefiting from exact match / filtering or even from aggregations.

**Comment by flexoid** [comment]
@webmat well, you convinced me. Having a strong convention is more important and useful then insignificant optimization.

We're started using Elastic Cloud and I'm trying to bring our app logs (Rails, golang, nodejs) to some standard format, and I think I can use ECS as a reference and a starting point for it.

Thanks again. Probably, the issue can be closed.

**Comment by webmat** [comment]
Excellent. Good luck :-)
