### ISSUE TITLE
syslog PRI

### ISSUE THREAD

**Issue by willemdh** [elastic/ecs#36]
Is syslog program is meant for process.name, is there a field for the PRI syslog field (which I used to name syslog_pri). This allows for calculation of facility and severity:

https://gist.github.com/marvin/1017480

**Comment by praseodym** [comment]
There is `event.severity`, but only as a `long`. I don't see a good way to map facility and severity labels from the [syslog_pri filter](https://www.elastic.co/guide/en/logstash/current/plugins-filters-syslog_pri.html).

**Comment by willemdh** [comment]
Most syslog sources have a PRI field. A dedicated syslog object could also contain syslog.facility and syslog.severity.

**Comment by ruflin** [comment]
I would prefer to not have service specific fields in the generic objects. I tempted to say at the moment because of it would belong under `syslog.pri` but not sure if it should be part of ECS. At the same time syslog is very popular.

**Comment by willemdh** [comment]
A dedicated syslog object is ok for me. So is this mapping what we need?

```
"syslog": {
  "properties": {
    "pri": {
      "type": "long"
    },
    "severity": {
      "ignore_above": 1024,
      "type": "keyword"
    },
    "facility": {
      "ignore_above": 1024,
      "type": "keyword"
    }
  }
}
```

**Comment by ruflin** [comment]
I'm working on extending our use cases here: https://github.com/elastic/ecs/pull/55 This would allow us to have a fields.yml for syslog in the use cases and then decide later if it makes sense in ECS directly or not but have it there for others to share (and comment).

**Comment by willemdh** [comment]
This will soon be resolved, see https://github.com/elastic/ecs/pull/525
Thanks all!
