### ISSUE TITLE
event.risk_score

### ISSUE THREAD

**Issue by willemdh** [elastic/ecs#38]
Hello,

Coud someone please elaborate on the event.risk_score field?

`Risk score value of the event.	float`

In what format should the values be? What range? Score from 1 to 10?1 to 100? With decimals?

I will need to assign a risk score to F5 related security events.

Grtz

Willem

**Comment by ruflin** [comment]
@MikePaquette Could you comment on this one?

**Comment by willemdh** [comment]
Just an fyi, the

**Comment by willemdh** [comment]
Just an fyi, the violation rating of F5 BIG-IP ASM 11.6.0 and later rating goes between 1 and 5.  1 is most likely a false positive and 5 is most likely an attack.

**Comment by MikePaquette** [comment]
@willemdh @praseodym thanks for the question.  The intent of `event.risk_score` is to hold values of a risk score or priority associated with the event which is based on more than just the `event.severity` field, and thus represents a higher level indicator upon which to decide further action.  Mapping to this field may take some additional processing work, as this value is defined as being normalized to a 0-100 scale.   Fields mapped to `event.risk_score` may be related to event.severity, but may also include other factors as part of a calculation, and may be related to a specific entity, such as user [via UBA], system, or threat indicator [IOC], etc.) 

As an example, the ArcSight Threat Level Formula produces a `priority` output, which is a number between 0-10.  To map to ECS, the `priority` value would be normalized to the 0-100 scale by multiplying it by 10.  

In your example of the F5 ASM rating,  the value could be normalized to the 0-100 scale by multiplying the value by 20.  

A third example would be a Securonix user risk score, which could have values in excess of 100, say 110.67, which would be normalized to a 0-100 scale based on the max risk score possible, and mapped to this ECS `event.risk_score` field.

Please let me know if this makes sense.

**Comment by MikePaquette** [comment]
@ruflin given the above, do you have a recommendation of float vs. half_float vs. scaled_float for `event.risk_score` ?

**Comment by ruflin** [comment]
What is the granularity we need on this field? Are 100 values enough so we don't need any digits after the comma or do we need 1-2? If yes, scaled_float would be best here.

More general questions: Are the risk_scores comparable from the different systems if they are normalised? In the above example does `4` in F5 mean the same as an `8` in Arcsight? Do we expect people to correlate the risk_scores from the different services? If yes definitively +1 on normalising, if not we might over define it an instead just let users use the value from their systems.

**Comment by willemdh** [comment]
`Do we expect people to correlate the risk_scores from the different services? If yes definitively +1 on normalising`

I'm all +1 on the correlation. But we would need a field to get the original risk score to imho?

So maybe better to ceate 1 `event.risk_score` and 1 `event.risk_score_norm` (or sth similar)

**Comment by webmat** [comment]
I would be in favour of having the "straightforward" field name (event.risk_score) be the original value, so someone filtering for stuff about one device type would get what they expect there.

The value of normalizing is clearly there too, but may be less obvious at first, or may even have some weird behaviours, depending on arbitrary scales defined by the various vendors & systems. For this reason I would have this one use the more convoluted field name (event.risk_score_norm or similar).

**Comment by ruflin** [comment]
+1 on proposal from @webmat @willemdh

**Comment by ave19** [comment]
I think there always needs a place to store the original value.  It helps a lot when tracking back to the source.  

Give up normalizing between different tools' interpretations of risk.  "Your medium is my low!"  There's no winning that.

**Comment by ruflin** [comment]
It seems we are all on the same page. Anyone wants to open a PR?

**Comment by ruflin** [comment]
@webmat Do you want to open a PR for this one?

**Comment by webmat** [comment]
Yes I'll do that next week

**Comment by webmat** [comment]
I've submitted PR #90 for this. I didn't change the field type (premature optimization?).

Let me know your thoughts. Does this clarify enough? Should I clarify more in the doc `severity` vs `risk_score`? Any other feedback welcome as well.
