### ISSUE TITLE
New field request: cloud.instance.tags (or, cloud.instance.labels) of type object

### ISSUE THREAD

**Issue by justinwalz** [elastic/ecs#384]
It would be nice for beats running on an instance to also collect instance tags. For Amazon EC2, this would require `ec2:DescribeTags`, and would be up to the operator to set. For other clouds, similar access would be required.

However, I believe it would add valuable metadata to the ES documents, and allow greater ability to filter, aggregate, etc for dashboards and alerts.

From the `base` fields spec, it looks like `labels` might be preferred. I'm okay with either tags or labels, as type object. Following the same rules too (no nesting, key/value pairs only, etc).

Best, Justin

**Comment by webmat** [comment]
Thanks for your suggestion, Justin.

Yes, for now if you want to gather them in an ECS field, you can use the base field `labels`, which is for KV.

Adding it to cloud instances in the schema also makes sense. Your suggestion is noted.

**Comment by jamiehynds** [comment]
Closing this for now as it isn't something we've seen demand for and labels are a workaround for now.
