### ISSUE TITLE
hashes ie: file hashes

### ISSUE THREAD

**Issue by neu5ron** [elastic/ecs#388]
Would like to discuss hashes, specifically the one that quickest comes to mind is file hashes.

I found some things with [auditbeat](https://github.com/elastic/ecs/blob/54f600d76cebcfcf121e1666a2ea8f2c72c6b892/use-cases/auditbeat.md) that have md5, sha1, etc.
I am thinking that we could use hash as a nested similar to how [Geo fields](https://github.com/elastic/ecs#-geo-fields) are being used.

File hashes would then be something like:
```
file.hash.md5
file.hash.sha1
file.hash.sha256
```
Going on something like x509/SSL/TLS certificates, would then be something like:
```
tls.certificate.hash.md5
tls.certificate.hash.sha1
tls.certificate.hash.sha256
```

Going on something like processes, example [sysmon event id 1](https://docs.microsoft.com/en-us/media/landing/sysinternals/event-screen-optimized.png), would then be something like:
```
process.hash.md5
process.hash.sha1
process.hash.sha256
process.hash.imphash
```

This would then keep searching hashes across disparate log sources like:
`*.hash.md5:60b725f10c9c85c70d97880dfe8191b3`

Especially, if/when, start adding source and destination file when doing more things from Sysmon/endpoint/EDR.

Excuse me if I am missing an open issue, I performed some searches in this repo and didn't find much in the issues.

**Comment by webmat** [comment]
I don't think it's addressed clearly in any issues or PR. Thanks for submitting this.

Yes, adding hash support as a reusable field set makes sense, IMO.

**Comment by neu5ron** [comment]
yep, I will take a stab.
also wil add;
- the other hashes that the auditbeat link had (like sha512 and such)
- ssdeep
- ja3
- ja3s
- whatever else I can find

**Comment by webmat** [comment]
Awesome, thank you!

Don't sweat any missing hashes. We can add them over time if any big ones are missing.

**Comment by webmat** [comment]
@neu5ron Colleague is tackling the hashes in ECS, if you want to take a look & comment: #426
