### ISSUE TITLE
network.bytes/packets adding sent and received

### ISSUE THREAD

**Issue by vertsaf** [elastic/ecs#408]
Currently using network.bytes and network.packets in the ECS schema.  What about adding sent and received options to both?  Or is there a way to do that otherwise? I have a ton of directional fields I would like to put in ECS like source user, source country, etc.

**Comment by webmat** [comment]
Hi @vertsaf the directional bytes and packets are available in the field sets that represent each side of the communication:

For source/destination: source.bytes, source.packets, destination.bytes and destination.packets

For client/server it's the same as well :-)

In all cases, the meaning is "sent by". So for example, source.bytes is amount of bytes sent by the source.

**Comment by vertsaf** [comment]
thanks that make sense, i missed that.

what about source user and source country?

**Comment by webmat** [comment]
It's also there. Scroll down a bit, on the "source" page https://www.elastic.co/guide/en/ecs/current/ecs-source.html#ecs-source-nestings

This is a list of field sets that can be nested under source. So this means you can have all of the "user" fields at source.user.*, like source.user.name. The same goes for locations: source.geo.country_name as well as the rest.

I'm curious about how clear this section is. First of all, did you see this section at all, when looking at the docs? If so, did it make sense to you?

**Comment by vertsaf** [comment]
I missed the stacking I think i just needed more caffeine this morning.  Makes sense.  And, thanks for the direction.
