### ISSUE TITLE
url method

### ISSUE THREAD

**Issue by willemdh** [elastic/ecs#41]
Is there already a place for GET, POST, HEAD, PUT. I was looking for something like url.method. Checked hte http object and the url object, but didn't found anything suitable at first sight?

I hope it's not meant to be in event.action, because for me event.action is already occupied by the action done on the event (Request blokced or passsed)

For example

`<155>Jul 10 12:32:17 slot1/acff5 err dcc[13819]: 01310039:3: [SECEV] Request violations: Attack signature detected. HTTP protocol compliance sub violations: N/A. Evasion techniques sub violations: N/A. Web services security sub violations: N/A. Virus name: N/A. Support id: 629814446755358496, source ip: 10.12.149.61, xff ip: 10.12.149.61, source port: 51779, destination ip: 10.12.1.138, destination port: 443, route_domain: 0, HTTP classifier: /Common/F5_External_Policy, scheme HTTPS, geographic location: <N/A>, request: <POST /Sched.aspx?viewGuid=cbeb7-fdc0-4687-a961-d28 HTTP/1.1\r\nHost: vlootbeheer.osjoemboera.be\r\nConnection: keep-a>, username: <N/A>, session_id: <f725ad3311df19ad>`

So I get this:

`POST /Sched.aspx?viewGuid=cbeb7-fdc0-4687-a961-d28 HTTP/1.1\r\nHost: vlootbeheer.osjoemboera.be\r\nConnection: keep-a`

But in what field should I put POST  (or GET or PUT)? Where should I put the http version?

**Comment by ruflin** [comment]
I think the method belongs to the http request, so I would put this under `http.request.method`. I planned to expand the http fields with some more request fields but didn't get to it yet.

For the http version I would suggest `http.version`. 

Do you want to open a PR?

**Comment by willemdh** [comment]
@ruflin Please double check my PR, as I never did a PR to elastic before
