### ISSUE TITLE
Command Line - Source/Destination

### ISSUE THREAD

**Issue by neu5ron** [elastic/ecs#415]
Looking into the ECS documentation I don't see a command line schema/category, unless its the args field under process. However more importantly I would like to discuss and propose adding or documenting a schema for `source` and `destination` command line/arg.

This is especially useful in endpoint data. Parent/Child process command line or a source using psexec for spawning a process with command line parameters on another device (destination).

### CLI Parameters
this is a pretty underwhelming example. but I hope conveys my point.
`cmd.exe` with the `/K` cli/arg for spawning `ping.exe` with `127.0.0.1 -c 3` as the cli/arg.
##### example:
```
"source.process.name": "cmd.exe",
"source.process.command_line": "/K",
"destination.process.name": "ping.exe",
"destination.process.command_line": "127.0.0.1 -n 3"
```

**Comment by webmat** [comment]
@neu5ron We've actually been discussing making the `process` field set nestable at `process.parent`. Would that be a good way to solve the spawning aspect of this, for you?

Is there anything else I'm missing here?

**Comment by neu5ron** [comment]
that would be great! Essentially what I was thinking, then possibly some guidance on possibility to use it under source/destination?
I think the guidance is critical (along with the route you all are already going with nesting) on where somone places a source/destination process - because this is going to affect the programmability of things like the SIGMA framework.

**Comment by jamiehynds** [comment]
Closing this for now as the `process.parent` field partially addresses the use case, but may revisit the source/destination concept in the future.
