### ISSUE TITLE
ECS version question

### ISSUE THREAD

**Issue by willemdh** [elastic/ecs#428]
So in https://github.com/elastic/ecs/blob/master/generated/elasticsearch/6/template.json I can find:

```
  "mappings": {
    "_doc": {
      "_meta": {
        "version": "1.1.0-dev"
      },  
```

But isn't the latest released ECS version 1.0.0?

Am I missing something?

**Comment by webmat** [comment]
@willemdh You're seeing this because you're on master, which is for latest developments. If you want the template (or any generated file) as of a specific version, you should check out that version tag (or version branch) first :-)
