### ISSUE TITLE
ECS _doc vs doc type

### ISSUE THREAD

**Issue by willemdh** [elastic/ecs#429]
Hello,

I'm a bit confused about the es ecs template https://github.com/elastic/ecs/blob/master/generated/elasticsearch/6/template.json
 _doc type
```
{
  "index_patterns": [
    "ecs-*"
  ], 
  "mappings": {
    "_doc": {
```

Tried making a default ecs template with a low order and another template with a high order containing some custom fields of the company I'm working in.

```
PUT _template/logstash-ecs
{
  "order" : 2147483644,
  "index_patterns" : [
    "logstash-ecs-*"
  ],
  "settings" : {
    "index" : {
      "refresh_interval" : "30s",
      "analysis" : {
        "normalizer" : {
          "normalizer_lowercase" : {
            "filter" : [
              "lowercase"
            ],
            "type" : "custom"
          }
        }
      },
      "number_of_shards" : "2",
      "number_of_replicas" : "1"
    }
  },
  "mappings" : {
    "doc" : {
      "properties" : {
        "digipolis" : {
          "properties" : {
            "subcel" : {
              "type" : "keyword",
              "ignore_above" : 1024
            }
          }
        }
      }
    }
  },
  "aliases" : {
    "logstash-ecs" : { },
    "ses-brocade" : { }
  }
}
```

There is no '`        document_type => "_doc"`' in my elasticsearch output. But the result is:

`[2019-04-11T15:51:45,947][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"logstash-ecs-001-2019.04.11", :_type=>"_doc", :routing=>nil}, #<LogStash::Event:0x4ccb5564>], :response=>{"index"=>{"_index"=>"logstash-ecs-001-2019.04.11", "_type"=>"_doc", "_id"=>nil, "status"=>400, "error"=>{"type"=>"illegal_argument_exception", "reason"=>"Rejecting mapping update to [logstash-ecs-001-2019.04.11] as the final mapping would have more than 1 type: [_doc, doc]"}}}}`

Tried to use _doc in my logstash-ecs template:

```
  "mappings" : {
    "_doc" : {
      "properties" : {
        "digipolis" : {
          "properties" : {
            "subcel" : {
```

But I keep getting:

`[2019-04-11T16:02:09,045][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"logstash-ecs-001-2019.04.11", :_type=>"doc", :routing=>nil}, #<LogStash::Event:0x48b6e6fd>], :response=>{"index"=>{"_index"=>"logstash-ecs-001-2019.04.11", "_type"=>"doc", "_id"=>nil, "status"=>400, "error"=>{"type"=>"illegal_argument_exception", "reason"=>"Rejecting mapping update to [logstash-ecs-001-2019.04.11] as the final mapping would have more than 1 type: [_doc, doc]"}}}}`

So what is the recommended way to handle this? I would prefer to keep the original generated ecs template and add any custom configurations / mappings / fields with an override template with a higher mapping. Is this a supported way of using ECS with Elastic 6?

Seems this question is related to https://discuss.elastic.co/t/elasticsearch-doc-type-deprecation-doc-vs-doc/139799 which was never answered..

**Comment by andrewkroh** [comment]
Using `_doc` in both of your index templates should fix the situation in Elasticsearch 6. You might want to stop indexing, fix the templates, delete the index that is currently be written to, then restart indexing. This is because changing the index templates doesn’t affect existing index and its mapping.

This document describes the schedule of changes for the document types. https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html#_schedule_for_removal_of_mapping_types

**Comment by willemdh** [comment]
Hmm, ok found the issue. Some template with a lower order astill had doc
