### ISSUE TITLE
The way of storing person information and mixing system and normal users

### ISSUE THREAD

**Issue by vbohata** [elastic/ecs#442]
We have couple of systems where user is actually some system user account which some apps/services use to authenticate against other systems. As sometimes it is really impossible to distinguish which user type it is and some systems put as user/login name some generic string like "network identification id" if the user is not authenticated, the user.name is valid place to store both system accounts and real/normal user names. But sometimes if it is possible to find it would be nice to store field like:
- user.type
with value like "system" or "regular".

Also there is sometimes information like user department. There is currently no way to store it. So either there could be more generic "user.organization.(unit/department)" fields or completely separate it to some "person" field. But again for some events it is really hard to detect the user department is related to some person and not a system account (where there are values like "Default Dept").

**Comment by webmat** [comment]
I really like these suggestions, thanks @vbohata!

I think `user.type` is pretty straightforward. I could go with the suggested values "system" and "regular". At the moment I'm not sure I see more than these two, so we could start with this. I'm adding `user.type` on my short list of things to add.

As for the organizational details, I can see how they will be useful as well. But I'd like to do a deeper dive into what else should be considered here. User role, source of the information (e.g. AD, LDAP, local?) and other metadata that could be related.

I want to have a good overview of what we can get around organizational information, before adding fields on that subject. For now, as usual you can always add this information in custom field, and report back what worked well and what didn't.

**Comment by vbohata** [comment]
Currently for organization information we use (with our prefix):
- organization.id
- organization.name
- organization.unit.name

It turned out these fields currently cover our needs. We consider them reusable and use them also in x509 (certicate) fields etc. and now we have:
- user.organization.unit.name

**Comment by webmat** [comment]
Excellent!

Out of curiosity, what granularity goes in `organization.name` and `organization.unit.name`? Can you give me examples of values for each?

**Comment by vbohata** [comment]
It really depends on organization type and size, something like: organization.name "My Company", organization.unit.name "IT/operations". Ideally it should be in the same format as used for example for certificates (o=My Company, ou=IT/operations) but it really depends on what is available for the entire user.

**Comment by jamiehynds** [comment]
Closing this one as some of the existing `organization` fields met the use case.
