### ISSUE TITLE
docs/index.asciidocs does not utilize /version file

### ISSUE THREAD

**Issue by ansoni** [elastic/ecs#451]
Hello,
  I am working on an internal fork of ecs with the goal of promoting changes upstream.  I re-use the ecs structure for building internal documentation/artifacts for usage and it mostly works except for docs/index.asciidoc which has the version hard-coded into it.  Ideally, we would also generate docs/index.asciidoc and any other asciidoc file that has a version in it.

Thanks,

Anthony

**Comment by ruflin** [comment]
We have a version file here: https://github.com/elastic/ecs/blob/master/version Agree it would be great if we would use this for generation in case we don't already do. @webmat might comment on this.

**Comment by webmat** [comment]
Yes, one thing I'd like to do soon is replace some of this static hardcoding with proper file templating. Perhaps mustache or Jinja2, where we could inject (and override) values & so on.

I'd be curious to hear more details about how you're leveraging the ECS repo. Your workflow around it, if you like.

We also intend to make the code useful to users directly. The initial goal was to come up with something that helps maintain user's custom templates, based on ECS. In other words, the main fields + your custom fields. But you're right that the documentation generator can also be used to create awesome documentation for your own users.

Note to self: we may just need to make the branding configurable 😂

**Comment by ebeahan** [comment]
Index is now also generated based on a Jinja2 template: https://github.com/elastic/ecs/blob/master/scripts/templates/index.j2#L13
