### ISSUE TITLE
Mixing ECS field versions issues

### ISSUE THREAD

**Issue by vbohata** [elastic/ecs#455]
The beats log shippers are using ECS fields whenever possible to publish events. Each event is also often being processed in logstash with additional mapping to ECS. For example Winlogbeat publishes:
- event.code: somecode
- winlog.event_data : somedata

In logstash I map winlog.event_data.sourceip to source.ip.
Now the beats exported fields conform to some ECS version while my logstash-side created fields can conform to another ECS version. In this simple example it will probably does not cause issues. But with a larger set of fields, multiple ECS versions and multiple version of beats log shippers this is just a matter of time until it creates inconsistencies. Yes, in the logstash one can check the incoming ECS version and parse the way it conforms or create a filter for backward or forward compatibility ... But again with more fields it is not possible to handle it.

I think this will become a major issue in future and should be somehow solved asap. Maybe:
- Creating logstash plugin and/or ES ingest pipeline to map fields to the correct name. So in LS name it like "ecs10.source.ip", call logstash "ecs filter" which transforms it for example to "source.ip" if it finds ecs.version to be 1.0.
- As the previous could be very hard to create (simple renaming, lowercasing, ... should work but bigger incompatibilities are impossible to solve automatically) maybe there shoyld be the way to mix multiple ECS field versions in a single document.

**Comment by farrp** [comment]
This has been a worry of mine as well - how to maintain multiple versions of ECS. I really love the idea of ECS but without some type of migration plan it has the possibility to become a mess, especially during the rollout of a new version across the infrastructure.Versioning the data helps, but there is still the mapping issue that vbohata mentions.
—
Regards,

Peter Farr
pfarr@OPSConsulting.ca
(416) 436-5977

Specializing in IT Operations and Service Management

**Comment by webmat** [comment]
A helpful pattern to avoid mapping conflicts during a rollout is to version the index name. For example, Beats does this by naming the index this way: `filebeat-7.0.1-YYYY.MM.dd` (or equivalent ending for ILM).

This means Filebeat 7.0.1 instances are always sending to a mapping built exactly for that version. Then the conflicts you may see during a rollout will simply be experienced as a Kibana index pattern conflict, which is much less severe than a mapping conflict at ingestion time. Index pattern conflicts are also only relevant if you're actually using the field directly (e.g. performing aggregations on a field that's changing significantly); if you're not using the field directly, you may not even notice the conflict... If there are conflicts, you can always mitigate them by temporarily creating other index templates, such as `filebeat-6.*` and `filebeat-7.*`.

The other part of that question -- which is building on top of an event that already has an ECS version -- I'm not sure I fully understand the problem you see. This field is meant to state what schema the event conforms to. So if a source sends and ECS 1.0 event, and you're modifying it with Logstash or Ingest Node to match ECS 1.1, the final event should have `ecs.version:1.1.0`.

**Comment by webmat** [comment]
I think the original concerns here have been addressed. Please open another issue if there's something else that needs to be addressed.
