### ISSUE TITLE
timestamp instead of @timestamp

### ISSUE THREAD

**Issue by ansoni** [elastic/ecs#457]
Shouldn't this line be "@timetamp"

https://github.com/elastic/ecs/blob/580752c2813a6e36f633be6c4213464f5350dc90/use-cases/beats.yml#L13

logging.yml and metricbeat.yml also have the same field.

It would be nice if the build script enforced the field correlation between these docs.

**Comment by webmat** [comment]
Thanks for the note, and yes, this should indeed be `@timestamp`. I’ll fix that when I have a moment.

Note that this use case section may be a little out of date. We’re working on another way to demonstrate ECS in different contexts. So you may find other inconsistencies in here

**Comment by ansoni** [comment]
bummer on the use-cases.  I have a forked version of ECS with some custom fields and made use of the use-cases.  Looking forward to seeing the updates!  Keep up the good work.
