### ISSUE TITLE
Support for server.uptime and process.uptime

### ISSUE THREAD

**Issue by mdelapenya** [elastic/ecs#475]
Is is worth it adding the milliseconds a server has been up? It's a value coming directly from the OS (both *NIX and Windows) using the `uptime` command.

For process it already exists a `process.start` which could define how to calculate the uptime.

I.e., as described here: (https://superuser.com/a/464413) in linux/mac, it's possible to gather this info:
```
$ ps -eo pid,comm,lstart,etime,time,args
  PID COMM             STARTED                          ELAPSED      TIME ARGS
    1 /sbin/launchd    Sun May 19 10:10:53 2019     09-04:18:37  38:47.10 /sbin/launchd
   39 /usr/sbin/syslog Sun May 19 10:11:01 2019     09-04:18:29   0:18.02 /usr/sbin/syslogd
   40 /usr/libexec/Use Sun May 19 10:11:01 2019     09-04:18:29   0:34.19 /usr/libexec/UserEventAgent (System)
   43 /System/Library/ Sun May 19 10:11:01 2019     09-04:18:29   0:14.74 /System/Library/PrivateFrameworks/Uninstall.framework/Resources/
   44 /usr/libexec/kex Sun May 19 10:11:01 2019     09-04:18:29   0:22.23 /usr/libexec/kextd
```

But again, please close this issue if you do not consider it :)

Thanks!

**Comment by webmat** [comment]
Thanks for submitting this, @mdelapenya!

Yeah I think it makes sense. I'm not opposed to keeping milliseconds (or nanos) precision when it's available. But I would think the optimal user experience when using/viewing the data would be to have this field's unit as seconds. What do you think?

**Comment by mdelapenya** [comment]
Hey @webmat, I agree 👍 

I can send a PR once I have bandwidth for it

Thanks for your feedback!
