### ISSUE TITLE
Modify message field to have a keyword option

### ISSUE THREAD

**Issue by Randy-312** [elastic/ecs#489]
I would like the message field to have the first 256 characters indexed so that we can query those fields. 

This is a follow-up to the discussion in https://github.com/elastic/ecs/issues/223

**Comment by webmat** [comment]
Hey @Randy-312, I've reviewed your comment on #223. Thanks for chiming in!

You're more than welcome to add a multi-field to `message` of type `keyword`. This would not be a conflict, as `message` would still be of datatype `text`, as ECS states. The field `message.keyword` would simply be considered as a custom field.

Here's how you can modify your Elasticsearch template to accomplish this:

```JSON
      "message": { 
        "type": "text",
        "fields": {
          "keyword": { 
            "type":     "keyword",
            "ignore_above": 1024
          }
        }
      }
```
