### ISSUE TITLE
Is the intention to have auditbeat (and others) migrate to the ECS

### ISSUE THREAD

**Issue by nick-george** [elastic/ecs#49]
Hi there, 

Is the plan to have auditbeat, metricbeat, packetbeat (etc) use the ECS mappings at some point? Will all the fields they produce be reflected in the ECS? If so, are you able to indicate if this migration work is already underway? 

I'm keen to store all the events from the various beats in a single set of time based indices (e.g logstash-*) to ease analysis. Further to this, I'm keen to have Kibana know the field mappings up front, rather than having to continually refresh the mappings cache (at least until https://github.com/elastic/kibana/issues/6498 has been implemented). 

Many thanks, 
Nick

**Comment by ruflin** [comment]
It is planned that all Beats switch to ECS. As changing field names is a breaking change we plan to do it in the next major release. To keep old fields working our idea is to use the upcoming field alias feature in Elasticsearch.

If you look at the Beats, you will see that new fields added normally already follow ECS.

For your question: Will all fields be in ECS? No. There are many fields in each Beat which are very service specific. For example all metrics for Redis will not show up in ECS as I think this is out of scope.

Even with ECS in place I would not recommend to put all data in one index. They can definitively share a common prefix. To only have to query one index I would recommend you also do have a look at index alias feature in Elasticsearch which could be helpful here.

**Comment by nick-george** [comment]
Thanks for all that advice @ruflin, I will definitely take it on board!
