### ISSUE TITLE
Translating FortiOS log fields to ECS 

### ISSUE THREAD

**Issue by enotspe** [elastic/ecs#492]
Dear community, we need some help for translating FortiOS fields to ECS fields. The idea is to reach something similar to #352 [#9199](https://github.com/elastic/beats/issues/9199)

We have extracted all fields listed on FortiOS 6.2.0 Log Reference (https://fortinetweb.s3.amazonaws.com/docs.fortinet.com/v2/attachments/be3d0e3d-4b62-11e9-94bf-00505692583a/FortiOS_6.2.0_Log_Reference.pdf)

to a Google sheets (https://docs.google.com/spreadsheets/d/1hZYIcozgZQhyXTekOJbXujFBAN-YnJ2cQFP_T0ejuio/edit?usp=sharing)

Feel free to copy or work on it.

Before translating, we need work on a mapping issue first. These fields have 2 datatypes:

- checksum | string  | uint32
- filesize | uint32  | uint64
- from | ip  | string
- to | ip  | string
- version | string  | uint32
- xid | uint16  | uint32

Altough filesize and xid have different datatypes, both of them refer to numbers, so they are not really a problem, like all fields that have different lenght, we can just map them to the larger type. 

But with the rest, how should we map them? string or integer? ip or string? should we create different fields deppending on the mapping? This last approach seems best.

**Comment by hoat23** [comment]
@ugosan  check this.

**Comment by webmat** [comment]
Hi @enotspe, thanks for dropping by!

I'm not sure I understand the issue you're facing.

ECS defines a set of fields as well as their data type. Once you determine which FortiOS field maps to which ECS field, you need to use the data type stated by ECS for your mapping to conform to ECS.

Your list does bring to mind a few pointers I can still give you:

* integers in ECS are virtually all [long](https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html), so most of your numerics should fit
* Various tools can report textual addresses in places that are otherwise meant to contain an IP (e.g. Apache HTTPD can report a hostname depending on how it's configured).
  * In cases where there's ambiguity, you should store this address in the `.address` field, and conditionally copy it to the corresponding `.ip` field, if the value is a valid IPv4 or IPv6.

I suppose these points don't answer your main question. Please let us know how else we can help you with this.

**Comment by enotspe** [comment]
by "mapping", i meant "translating". I have just corrected it.

**Comment by webmat** [comment]
Hi @enotspe, were my answers helpful? Is there anything else you need help with?

Please also make sure to ping us here, once you've started mapping some of the FortiOS fields to ECS. We'll be happy to help review your mapping to ECS.

**Comment by enotspe** [comment]
Yes @webmat , your answers were helpful. Thanks

**Comment by enotspe** [comment]
I have translated possible fields that can be translated to ECS (quite a few actually).  @webmat 

When should we use client vs source vs host???

OS should also be allowed to be nested from client or source, not only host as it is right now.

Application should be a category by itself.  Type, category, group, risk, id are just some fileds I can think of that need to be asigned to an application (network.application).

We also need some "security" fields, like virus, thread, ips signature, risk, etc. Not really sure where should they be nested from.

NAT fields as well.

I guess firewalls logs are a world on themselves and we still need to make a lot of progress on creating fields that are useful to this usecase.

**Comment by webmat** [comment]
Thanks for the feedback! Reading your comment feels like you're trying to guess our roadmap ;-)

`host.*` is really meant to contain the details of a host where the event is happening, it's not meant to describe one side of a network connection per se. So it's in a sense purely metadata. The sides of the network connections meant to be used together are source+destination, or client+server. If your use case works best with client+server, we recommend populating source+destination with the same information as well. We consider source+destination as the baseline.

Basic NAT fields are already in (https://github.com/elastic/ecs/pull/491). Let us know if you need more. 

Many aspects of security are in the works as well, for threats, threat matches, alerts, etc.

For application, two things: `network.application` is meant to describe application level network protocols. I understand there's a distinction between having support for `application.*` and the support we already have for `process.*`. But I'm curious. If/when we add support for application, how would you use it, vs the process field set?

**Comment by enotspe** [comment]
I have decided to split the translation: basically there are 3 types of logs that a fortigate produces:

1. traffic
2. utm
3. event

traffic logs are the most important, as they are the heart of all logging on FortiOS. UTM logs always depend of traffic logs.

traffic logs have the sense of connection, therefore client/server aproach works best for that type of logs. I dont agree with "populating source+destination with the same information as well", tough.

I think there should be a way to correlate host with client/server or source/destination. On most scenarios, you will end up with beat agents on hosts as well as collecting logs from firewalls where that hosts traffic gets filtered.

In Fortinet, we got:

- (src)devcategory/dstdevcategory
- (src)devtype/dstdevtype
- (src)osname/dstosname
- (src)osversion/dstosversion

This fields are listed under OS, but OS is not allowed to be nested from client/server or source/destination, just from host.

NAT fields are OK.

Regarding your application question: on firewalls, an application is some network traffic that has matched a signature on the firewall. This definition is very broadly and it can go from HTTP.BROWSER to FACEBOOK.CHAT. Usually they are nested, FACEBOOK.CHAT is child of FACEBOOK. It is not related at all to process.

In Fortinet, we got:

- app (name)
- appact (action)
- appcat (category)
- appid (id)
- applist (security_profile)
- apprisk (risk score)

One more concern (maybe the most important regarding firewalls): ACTION is also something that needs to be thought more deeply. 

In Fortinet, we got:

- action: firewall action
- appact: application action
- sslaction: ssl action.
- utmaction: utm action.
- craction: client reputation action (this is not action itself, it is an score on whether you should take some action for that client)

I have no clue on how to aproach these fields, wheter there should be a ACTION category or should be part of EVENT? maybe ACTION should be a category nested from EVENT.

I have focused my work only on traffic logs, because of the lack of security fields on ECS yet. But if we can have a decent amount of fields trasnlated from traffic logs, it would be an absolute success (consider that 1 out 3 firewalls in the world are Fortinet)

Some other comments: we need some fields for policy (firewall rule) and interface (ingress and egress). I guess they both should be under observer.

**Comment by enotspe** [comment]
I have separeted in different sheets fields by traffic, utm, event (not considering GTP type because it is a feature of FortiOS Carrier), so it would be easy to translate.

**Comment by enotspe** [comment]
based on @MikePaquette comment on [#290](https://github.com/elastic/ecs/issues/290#issuecomment-449384800) about how Palo Alto fields should be mapped:

"Another example, Palo Alto pan_traffic events could populate these fields like:
event.module: traffic
event.dataset: scan

Another example, Palo Alto pan_threat events could populate these fields like:
event.module: threat
event.dataset: wildfire_virus"

I have updated translation for "type" and "subtype" fileds.

**Comment by enotspe** [comment]
https://github.com/enotspe/fortinet-2-elasticsearch

**Comment by enotspe** [comment]
> Hi, the Google Sheets in OP is no longer accessible.
> Is there a backup or an alternative elsewhere?
> The GitHub link posted above has been useful but is not complete.

You can find the current sheet in fortidragon repo
