### ISSUE TITLE
Mapping process Id fields to keywords rather than longs

### ISSUE THREAD

**Issue by RedstormJones** [elastic/ecs#493]
I recently wrote a grok filter for SharePoint logs that often contain a process id and a process thread id, and since we are trying to stay up with ECS I naturally mapped these values to "process.pid" and "process.thread.id" in the grok filter. The identifier values in the Sharepoint logs are hexadecimal (0AD8, 0E6C, etc), so when Logstash tries to index documents with these id's it treats the values as strings, which then causes mapper_parsing_exceptions because ECS has already mapped the "process.pid" and "process.thread.id" fields to be longs.

My question/issue is - why are we mapping process id's, parent process id's and process thread id's to longs rather than keywords? The importance of these fields are their unique identifier values, not their numerical values, so shouldn't ECS have them mapped to keywords? 

Here is my grok filter:
```
^%{DATESTAMP:[event][created]}\s*%{DATA:[process][name]}\s*\(0x%{BASE16NUM:[process][pid]}\)\s*0x%{BASE16NUM:[process][thread][id]}\s*(?<service>\w*\s\w*)\s*(?<category>\w+(\s\w+)*)\s*%{WORD:[event][id]}\s*%{WORD:[log][level]}\s*%{DATA:message}\s*(?<guid>\w{8}\-\w{4}-\w{4}-\w{4}\-\w{12})?$
```

Here is an example log that the filter would parse:
```
06/18/2019 13:46:44.90 w3wp.exe (0x0E08) 0x1288	SharePoint Foundation General 6t8g	Verbose Looking up typical site https://spwebapp.company.com:443/sites/ZD101010101/03DDD/03CCCC_MMMM/PPP-040 - PPP-RRRR14 Mission Relocation Dates in web application SPWebApplication Name=SPWebAppName.	
``` 

Here is one of the mapper_parsing_exception errors:
```
[2019-06-18T19:50:16,051][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"filebeat-7.0.0", :_type=>"_doc", :routing=>nil}, #<LogStash::Event:0x16d4f86f>], :response=>{"index"=>{"_index"=>"filebeat-7.0.0-000333", "_type"=>"_doc", "_id"=>"Kt4jdGsBGf5_Z_mx9CCR", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse field [process.thread.id] of type [long] in document with id 'Kt4jdGsBGf5_Z_mx9CCR'", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"For input string: \"0A54\""}}}}}
```

In the meantime I've implemented the following workaround via Elastic support:
```
# convert process id strings to longs to align with ECS
ruby {
    id      => "ruby-convert-sharepoint-ids-to-hex"
    code    => '
    event.set("[process][pid]", event.get("[process][pid]").to_s.hex)
    event.set("[process][thread][id]", event.get("[process][thread][id]").to_s.hex)
    '
}
```

**Comment by webmat** [comment]
Hi @RedstormJones, thanks for dropping by! The expectation for pid and tid is indeed that they get stored as decimal.

The addition of fields to contain the hex representations of pid and tid was discussed in the past here https://github.com/elastic/ecs/issues/82. We've decided not to add them for now. If you would like to store their hex representation, you're welcome to do so in a custom field.

I'm curious about how widespread the hex representation is in your situation, however. The use who initially suggested it was also working with Sharepoint events. Do you have other tools or situations where you get hex pid and tid? Is this the only representation that makes sense for you, or does Sharepoint display mixed values? E.g. `PID: FF(255)`.

cc @vbohata have you been happy with storing your hex PID and TID in custom fields?

**Comment by neu5ron** [comment]
just throwing my 2 cents in: 
just to concur with @RedstormJones that a lot of the windows logs are like this..

However, to the point ECS will (from my point of view with latest 7.2 stuff) have some of this implemented during ingest/ETL by default -- appears this was done in winlogbeat security and sysmon   ingest processor stuff in winlogbeat.

this hex to decimal conversion is done in [HELK](https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-logstash/pipeline/1542-winevent-process-ids-conversions.conf). Therefore, given ECS and HELK doing this I would say keep as long/decimal :)
Also, since "custom logs" will have to be massaged/confirmed to any schema (ECS or not) anyways.
