### ISSUE TITLE
Add field: process.thread.name

### ISSUE THREAD

**Issue by felixbarny** [elastic/ecs#507]
There is already [`process.thread.id`](https://github.com/elastic/ecs/blob/141b22458feb1092dfcec856199d3fa21cd5a549/schemas/process.yml#L75), however, a thread name is arguably more descriptive. The use case for this would be Java logging, for example. For this use case, it's useful to see in which thread a log has been emitted.

**Comment by cpmoore** [comment]
In our own implementation we're already using `process.thread.name`.  Some of our java applications log only log the thread name, eg `Default Executor-thread-6308`

**Comment by felixbarny** [comment]
@cpmoore I'm interested in your setup: are you logging as JSON or parsing plain-text log files with logstash/filebeat/ingest node?

**Comment by cpmoore** [comment]
@felixbarny We’re using filebeat to send plain text logs to logstash and parsing them with a grok filter. 
This specific application I was referring to above is a vendor provided application to which we have no way of configuring It’s logging format.

**Comment by webmat** [comment]
Yes, adding this field makes sense and is straightforward. 

I'm adding it to my (long) list of quick fixes. Of course if someone has the time to send over a PR for this, I can fast track the approval :-)

**Comment by cpmoore** [comment]
@webmat 

I believe I opened the PR correctly.  Still kinda a newbie :smile:

**Comment by webmat** [comment]
@cpmoore You did, and were successful on the first try (no missing `make` & such).

Thank you! 💯
