### ISSUE TITLE
Beats Kubernetes Metadata not available in ECS

### ISSUE THREAD

**Issue by Reamer** [elastic/ecs#510]
Hi,
currently the (file)beat components report Kubernetes metadata with the following structure.

```
  "kubernetes": {
    "container": {
      "name": "filebeat"
    },
    "labels": {
      "controller-revision-hash": "2980298121",
      "k8s-app": "filebeat",
      "pod-template-generation": "17"
    },
    "namespace": "elastic-logging",
    "node": {
      "name": "s-cp-node-04.cloud.mycompany.com"
    },
    "pod": {
      "name": "filebeat-nxtxw",
      "uid": "be9663ee-9337-11e9-95cb-005056945e02"
    }
  },
``` 

At the moment this structure is not part of ecs. It's also not possible to mutate this structure to `container` fields. In #132 `kubernetes` was removed to implement a more generic structure. Is there any process for a generic structure?
I have seen [use-cases/kubernetes.md](https://github.com/elastic/ecs/blob/master/use-cases/kubernetes.md). Can someone explain this sentence? 
> Kubernetes container name. This name is unique within the pod only. It is different from the container.name field.

Best Regards
Reamer

**Comment by praseodym** [comment]
> I have seen [use-cases/kubernetes.md](https://github.com/elastic/ecs/blob/master/use-cases/kubernetes.md). Can someone explain this sentence?
> 
> > Kubernetes container name. This name is unique within the pod only. It is different from the container.name field.

I think this is best explained with an example. For example, the Kubernetes CoreDNS pod has a container named `coredns`; this name goes into `kubernetes.container.name`. In the Docker daemon on the host where the pod is running, this container is uniquely named `k8s_coredns_coredns-74c9d4d795-jp9lg_kube-system_0426f9ec-dd94-4c28-840b-22e0afb38271_0`; this name goes into `container.name`.

**Comment by Reamer** [comment]
Hi @praseodym,
I use [cri-o](https://cri-o.io/) as container runtime, so I have no metadata for `container.name`.

**Comment by kaiyan-sheng** [comment]
We just created a similar issue in beats repo for this: https://github.com/elastic/beats/issues/23585

**Comment by ebeahan** [comment]
ECS now includes the [`orchestrator.*` field set](https://www.elastic.co/guide/en/ecs/current/ecs-orchestrator.html) to capture details like these from container orchestrators, like k8s.
