### ISSUE TITLE
Define ECS set of fields for SQL information

### ISSUE THREAD

**Issue by simitt** [elastic/ecs#514]
Different beats modules exist that are collecting SQL information (MySQL, PostgreSQL). APM also collects SQL information when available. Aligning the information by defining a common field set in ECS would help retrieving information from the data in a unified way.

Following fields are currently defined in APM and beats and might help as a starting point for discussions:

**packetbeat**

[transaction_event fields](https://www.elastic.co/guide/en/beats/packetbeat/current/exported-fields-trans_event.html):
`transaction_event`
`event.dataset`
`type`
`method`
`query`

[postgresql](https://www.elastic.co/guide/en/beats/packetbeat/current/exported-fields-pgsql.html):
`pgsql.error_code`
`pgsql.error_message`
`pgsql.error_severity`
`pgsql.num_fields`
`pgsql.num_rows`

[mysql](https://www.elastic.co/guide/en/beats/packetbeat/current/exported-fields-mysql.html):
`mysql.affected_rows`
`mysql.insert_id`
`mysql.num_fields`
`mysql.num_rows`
`mysql.query`
`mysql.error_code`
`mysql.error_message`

**filebeat**
[ecs compliant](https://www.elastic.co/guide/en/beats/filebeat/7.2/exported-fields-ecs.html)
`service.type`
`event.module`
`event.dataset`

[postgresql](https://www.elastic.co/guide/en/beats/filebeat/7.2/exported-fields-postgresql.html)
`postgresql.log.timestamp`
`postgresql.log.core_id`
`postgresql.log.database`
`postgresql.log.query`
`postgresql.log.timezone`
`postgresql.log.thread_id`
`postgresql.log.user`
`postgresql.log.level`
`postgresql.log.message`

[mysql](https://www.elastic.co/guide/en/beats/filebeat/7.2/exported-fields-mysql.html)
`mysql.thread_id`
` mysql.error.thread_id`
`mysql.error.level`
`mysql.error.message`
`mysql.slowlog.lock_time.sec`
`mysql.slowlog.rows_sent`
`mysql.slowlog.rows_examined`
`mysql.slowlog.rows_affected`
`mysql.slowlog.bytes_sent`
`mysql.slowlog.bytes_received`
`mysql.slowlog.query`
`mysql.slowlog.id`
`mysql.slowlog.schema`
`mysql.slowlog.current_user`
`mysql.slowlog.last_errno`
`mysql.slowlog.killed`
`mysql.slowlog.query_cache_hit`
`mysql.slowlog.tmp_table`
`mysql.slowlog.tmp_table_on_disk`
`mysql.slowlog.tmp_tables`
`mysql.slowlog.tmp_disk_tables`
`mysql.slowlog.tmp_table_sizes`
`mysql.slowlog.filesort`
`mysql.slowlog.filesort_on_disk`
`mysql.slowlog.priority_queue`
`mysql.slowlog.full_scan`
`mysql.slowlog.full_join`
`mysql.slowlog.merge_passes`
`mysql.slowlog.sort_merge_passes`
`mysql.slowlog.sort_range_count`
`mysql.slowlog.sort_rows`
`mysql.slowlog.sort_scan_count`
`mysql.slowlog.log_slow_rate_type`
`mysql.slowlog.log_slow_rate_limit`
`mysql.slowlog.read_first`
`mysql.slowlog.read_last`
`mysql.slowlog.read_key`
`mysql.slowlog.read_next`
`mysql.slowlog.read_prev`
`mysql.slowlog.read_rnd`
`mysql.slowlog.read_rnd_next` 
 `mysql.slowlog.innodb.trx_id`
`mysql.slowlog.innodb.io_r_ops`
`mysql.slowlog.innodb.io_r_bytes`
`mysql.slowlog.innodb.io_r_wait.sec`
`mysql.slowlog.innodb.rec_lock_wait.sec`
`mysql.slowlog.innodb.queue_wait.sec`
`mysql.slowlog.innodb.pages_distinct`
`mysql.slowlog.user`
`mysql.slowlog.host`
`mysql.slowlog.ip`

**APM**
`span.type`
`span.subtype`
`span.name` (query summary)
`span.action`
`span.db.statement`
`span.db.type`
`span.db.instance`
`span.db.link`
`span.db.user`

**Comment by willemdh** [comment]
There are also the mssql fields, see 
https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-mssql-performance.html
https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-mssql-transaction_log.html

**Comment by webmat** [comment]
Another great idea, thanks @simitt!

Once again, do you think someone on the APM team could help get a PR started for this? And thanks for pulling together the fields from all of these sources, this will be very useful in implementing this.

We should try to define the most common fields across sources, I would expect around 10-15, including some basic stats that seem to be available from a few of the sources.

**Comment by cyrille-leclerc** [comment]
Notes to prepare the RFC:

## Sample Elastic APM Span document for a PostgreSQL call

```json
{
  "_index": "apm-7.8.0-span-000001",

  "_source": {
    "destination": {
      "address": "localhost",
      "port": 5432
    },
    "processor": {
      "name": "transaction",
      "event": "span"
    },
    "transaction": {
      "id": "7a2d30add01713e6"
    },
    "span": {
      "subtype": "postgresql",
      "destination": {
        "service": {
          "resource": "postgresql",
          "name": "postgresql",
          "type": "db"
        }
      },
      "name": "SELECT",
      "action": "query",
      "id": "ad83a5a6b16cd351",
      "type": "db",
      "db": {
        "statement": "select pg_sleep(0.05)",
        "type": "sql",
        "user": {
          "name": "test"
        }
      }
    }
  }
...
}
```
Details: https://gist.github.com/cyrille-leclerc/116a04511c38c5e6460a2b9cd5d265a8

## OpenTelemetry example for a MySQL call

See https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/database.md#mysql

| Key | Value |
| :---------------------- | :----------------------------------------------------------- |
| Span name               | `"SELECT * FROM orders WHERE order_id = ?"` |
| `db.system`             | `"mysql"` |
| `db.connection_string`  | `"Server=shopdb.example.com;Database=ShopDb;Uid=billing_user;TableCache=true;UseCompression=True;MinimumPoolSize=10;MaximumPoolSize=50;"` |
| `db.user`               | `"billing_user"` |
| `net.peer.name`         | `"shopdb.example.com"` |
| `net.peer.ip`           | `"192.0.2.12"` |
| `net.peer.port`         | `3306` |
| `net.transport`         | `"IP.TCP"` |
| `db.name`               | `"ShopDb"` |
| `db.statement`          | `"SELECT * FROM orders WHERE order_id = 'o4711'"` |
| `db.operation`          | not set |


We could compare the fields collected by Elastic APM and by OpenTelemetry.

**Comment by webmat** [comment]
Looking at OpenTelemetry for ideas and confirmation is a great idea 👍 

Quick comment on the JSON sample above: I avoid nesting the DB details inside span in the schema. From the APM context this database information is related to a span, sure. But in the general context of logging (including parsing DB access logs, slow logs or even replication logs), there's no concept of a span.

So I'd rather have an APM event fill both field sets:

```JSON
{
  "span": { 
    "id": "foo",
    "type": "db",
    ...
  },
  "db": {
    "type": "sql",
    "name": "SELECT",
    "statement": "",
    ....
  }
}
```

This will ensure users can correlate with other kinds of DB logs I've mentioned:

```JSON
{
  "db": {
    "type": "sql",
    "name": "SELECT",
    "statement": "",
    ....
  }
}
```

**Comment by mbrancato** [comment]
Does an RFC exist for this request? I think this is important when you have applications which log entries that are effectively reporting out changes from a backend database of some type.

I like something flexible for multi-term DB concepts like table (most SQL) / collections (Mongo / Firestore) / index (Elasticsearch). For that I'd like something like these where certain child fields should be populated based on the type of DB:

```
{
  "db": {
    "type": "sql",
    "operation": "SELECT",
    "table": ["table_one", "table_two"]
  }
}
```

```
{
  "db": {
    "type": "elasticsearch",
    "operation": "_bulk",
    "index": ["my_index"]
  }
}
```

```
{
  "db": {
    "type": "mongo",
    "collection": ["my_collection"]
  }
}
```

**Comment by ebeahan** [comment]
Hi, @mbrancato - thanks for those examples. No RFC has been opened on this topic yet, but the ideas here would be great to capture and formalize with an RFC.

**Comment by jthack** [comment]
Great idea mike! Chasing DB providers as a top level field seems less ideal compared to your solution.

**Comment by kgeller** [comment]
Since ECS has a stage 0 [RFC](https://github.com/elastic/ecs/blob/main/rfcs/text/0026-database-object.md) for creating a db fieldset, I am going to close out this issue and direct future input there. As always, feel free to re-open if anything changes.
