### ISSUE TITLE
ECS - AWS Cloudtrail

### ISSUE THREAD

**Issue by 0xtf** [elastic/ecs#535]
Hi,

I'm currently working on a Pipeline for AWS Cloudtrail. This was something that was originally started by Elastic PS (in an engagement) and after [tweeting](https://twitter.com/0xtf/status/1166035402588872706?s=20) about it I was advised to open an issue here. 

We are currently working on both the data dictionaries and the information model/schema. The work that has been done until now followed [Cloud ECS](https://www.elastic.co/guide/en/ecs/master/ecs-cloud.html). 

It is our goal to try and incorporate/push this work upstream.

**Comment by webmat** [comment]
Great to hear! Have you found that some fields present in CloudTrail were missing?

And actually, we'd be happy to review and comment on your mapping, if you have an online spreadsheet to share.

Here are other example issues where this kind of discussion happened: https://github.com/elastic/ecs/issues/492 and https://github.com/elastic/ecs/issues/504. Note that online spreadsheets like GDocs make it way easier for us to get right in there with comments :-)

**Comment by 0xtf** [comment]
Hi @webmat,

We sort of took the wrong approach in which we started editing the Pipeline directly without first working on some fundamentals. 

I'm going to be copying that over to the spreadsheet and get everything a bit more organized: https://docs.google.com/spreadsheets/d/1rtyP4s3R5iu55ob2uNWfbUoUO_GGBNOUV-PiHcCEMjI

I'd be happy to add editors in case someone is interested in helping. With the goal of creating alias with OSSEM, we could use all the help we can get. ☺️

**Comment by ebeahan** [comment]
Thanks for sharing your mapping work here with the community a while back, @0xtf!

I'll also point interested users to some of the log samples and their mappings in the Elastic Agent AWS Cloudtrail integration package: https://github.com/elastic/integrations/tree/master/packages/aws/data_stream/cloudtrail/_dev/test/pipeline
