### ISSUE TITLE
Improve documentation around how to use ECS with additional fields

### ISSUE THREAD

**Issue by ruflin** [elastic/ecs#54]
Additional documentation and recommendations should be created around ECS on how users should use ECS with their existing data structure, how to prevent conflicts with their own fields.

Add information about what is in the scope of ECS and what is not.

Also more info should be added about the terminology/style and if possible a grammar guide.

**Comment by webmat** [comment]
Related (with more active discussion): #101

**Comment by webmat** [comment]
Ah jeez, I missed this issue until I had posted #114, after discussion on #101 🤦‍♂️.

Since the other one includes more of the current thinking, @ruflin are you ok if we close this one? :-)
