### ISSUE TITLE
NGINX - Access log doesn't have a message field (Original Message)

### ISSUE THREAD

**Issue by Randy-312** [elastic/ecs#543]
I was reviewing nginx access logs, and it appears the original message has been entirely broken up into fields.  This prevents anyone from using the tailing features of logging.  It also means we don't have the 'orginal' log event, which MANY company's Auditors ask to be retained.

Or, is this retained in log.original or another field via FileBeats somehow?
I did NOT see it in Demo.elastic.co's JSON, so I assume this was just somehow missed as a thought.

**Comment by Randy-312** [comment]
ie. https://demo.elastic.co/app/kibana#/doc/filebeat-*/filebeat-7.2.0-2019.09.06-000176/_doc?id=98LFCW0BLZ_7yMG15UIk&_g=()

**Comment by ruflin** [comment]
@Randy-312 It's not kept at the moment. We had quite a few discussions around this in the past, see for example https://github.com/elastic/beats/pull/9172. If you check out the last comment, 2 processors were added for now to make it possible for the user to decide to add them.

**Comment by webmat** [comment]
@Randy-312 Thanks for bringing this up.

Since this is an issue with the Filebeat module, could you open the issue on the Beats repo instead, please?

Thanks!

**Comment by Randy-312** [comment]
Sure, I can open this in filebeat, but given that it's more of a configuration option, I'm not sure it's necessary.  I suspect the vast majority of customers would be fine with having the access logs NOT in the original format, and benefiting from the reduction in storage.  I DON"T think that's the same for the error logs though.

**Comment by ruflin** [comment]
@Randy-312 Interesting statement around error vs access. And it's one of the reasons why for now we made a config option.

**Comment by Randy-312** [comment]
Just a possible clarification.  It's adding a processor, not actually a config option.  Some folks would argue that's semantics, but to me, setting one flag is configuration.  Adding a copy_fileds processor and configuration is not.

> The copy_fields processor can be used to keep the original message:
>
>processors:
>- copy_fields:
>    fields:
>      - from: message
>        to: log.original
>    fail_on_error: false
>    ignore_missing: true


https://github.com/elastic/beats/issues/13574
