### ISSUE TITLE
API Gateway Layer 7 logs to ECS schema

### ISSUE THREAD

**Issue by Randy-312** [elastic/ecs#544]
We currently have filebeat sending in Layer7 logs to our ELK stack.
However, we're no longer 'parsing' it out, due to some directional changes to our pre-processing layer, and everything is simply unparsed.

We're going to align to ECS Schema, but need some guidance on Layer7, and if Anyone ELSE is working through this, they may wish to contribute as well.

We can start with Traffic Logging, which is what we have coming in today, and I have solid regex for as well.

Here are my notes so far..

[CA has documented some work for what they would do to send to elk.](https://community.broadcom.com/communities/community-home/librarydocuments/viewdocument?DocumentKey=af4d855f-307d-4c9d-8e8d-5f90b3cf007e)

[Here are their fields](https://docops.ca.com/ca-api-gateway/9-1/en/administer-the-gateway/configure-the-log-message-format)

[And CA's instructions on setup](https://docops.ca.com/ca-api-gateway/9-1/en/configure-security/tasks-menu-security-options/manage-log-audit-sinks/working-with-log-sinks-and-debug-logs)

**Comment by Randy-312** [comment]
If someone else is able to take up this work, let us know.   We won't be able to take this up anytime soon.

**Comment by Randy-312** [comment]
There may be an easier way to accomplish this now.
With the 9.4 CR1 release (documented in 10.0), [Layer7 is able to output log in JSON format.](https://techdocs.broadcom.com/content/broadcom/techdocs/us/en/ca-enterprise-software/layer7-api-management/api-gateway/10-0/using-the-container-gateway/getting-started-with-the-container-gateway/enriched-logging-in-json-format.html)

I would think about using filebeat to create new fields (ECS compliant) where the ones they provide aren't quite aligned to ECS.  Alternatively, renaming them to match our own format where we use record.

**Comment by webmat** [comment]
We created meta-issue #938 to add proxy support in ECS. Closing in favor of the meta issue. Stay tuned :-)
