### ISSUE TITLE
Question about PR

### ISSUE THREAD

**Issue by janniten** [elastic/ecs#546]
Hi,
I've opened a PR #545 and there was some problem with Travis.
It is not clear to me if the error is related to my code,
Shall I correct something?
Thank you
Regards
Ana

**Comment by webmat** [comment]
Hello, please ask questions about a PR as a comment on the same PR. Please don't open a separate issue :-) I'll go answer on the PR itself.

**Comment by janniten** [comment]
Thank you (and sorry :) ). Ill solve the dependencies firts and the generate a PR
