### ISSUE TITLE
ECS - Squid Log mapping

### ISSUE THREAD

**Issue by Randy-312** [elastic/ecs#549]
A colleague of mine is going to be working through mapping for Squid Logs to ECS.
Appears it will be very similar to what was [done for nginx already](https://github.com/elastic/beats/pull/9081)

This is also interesting: https://github.com/molu8bits/squid-filebeat-kibana/blob/master/filebeat/etc/filebeat/squid-fields.yml which is ONLY the CLF, and not the full Squid format (10 fields).

We may also need some help on any aliasing, like I see is documented for nginx.
I'm a little unclear on the mapping vs alias parts of this though.
[i.e., ](https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields-nginx.html)
nginx.access.body_sent.bytes
  type: alias 
  alias to: http.response.body.bytes

**Comment by Randy-312** [comment]
Can we get the Mapping label applied to this issue? @webmat

**Comment by kiran545** [comment]
here i have uploaded the sample Squid field mapping 
sample logs include as below ,
x.x.x.x - [10/Sep/2019:16:05:42 +0000] "CONNECT https:443 HTTP/1.1" 503 0 "-" "snowflake/1.0" TAG_NONE:HIER_NONE
x.x.x.x - [10/Sep/2019:16:05:54 +0000] "CONNECT https:443 HTTP/1.1" 503 0 "-" "snowflake/1.0" TAG_NONE:HIER_NONE
x.x.x.x - [10/Sep/2019:16:06:42 +0000] "CONNECT http:443 HTTP/1.1" 503 0 "-" "snowflake/1.0" TAG_NONE:HIER_NONE
x.x.x.x - [10/Sep/2019:16:06:54 +0000] "CONNECT http:443 HTTP/1.1" 503 0 "-" "snowflake/1.0" TAG_NONE:HIER_NONE
x.x.x.x- [10/Sep/2019:16:31:42 +0000] "CONNECT xxxx.s3.amazonaws.com:443 HTTP/1.1" 200 3284869 "-" "snowflake/1.0" TCP_TUNNEL:HIER_DIRECT
x.x.x.x - [10/Sep/2019:16:36:00 +0000] "CONNECT xxxx.s3.amazonaws.com:443 HTTP/1.1" 200 18572 "-" "snowflake/1.0" TCP_TUNNEL:HIER_DIRECT
[sample Squid ECS format.xlsx](https://github.com/elastic/ecs/files/3623792/sample.Squid.ECS.format.xlsx)

**Comment by webmat** [comment]
Here's some feedback on the mapping I see in the Excel file:

* I agree with the mappings for `client.ip`, `timestamp`, `request_method`, `status_code` and `http_version`
* URI: should go to `url.original`
  * If your URLs are full (from scheme all the way to path/query), copy it to `url.full` as well. This field can be formatted as URL in a Kibana index pattern.
  * Then if you need distinctive parts of the URL to be fleshed out as well for analysis, you should break it down in all of the other fields. domain, path, extension, etc.
* client identity: if this sometimes contains a username, it should go to `user.name`. When the source has no info (`-`), do not populate `user.name` with it, leave it out.
* content type: we don't have a place for it yet, but we're working on support for HTTP headers in https://github.com/elastic/ecs/pull/554
* response time: `event.duration`
* hierarchy_code: custom fields

**Comment by webmat** [comment]
I just noticed how the URI looked in the log samples provided by @kiran545 (thanks for dropping these in here).

I think the best you can do with this is directly populating `url.scheme`, `url.port`, and when present `url.domain`. I also think it's worth capturing the whole string (e.g. `xxxx.s3.amazonaws.com:443`), and despite not looking very much like a full URL, I would put it in `url.original`. From the field's description:

> Unmodified original url as seen in the event source.

These are meant to make sense in the context specific to the source. Web logs typically display a path with no domain/scheme, and in this context, that's what you expect in `url.original`. In this case, only connection level informations are logged, so `url.original` contains much less info, and I think that's fine.

**Comment by molu8bits** [comment]
I think the sample of log we see added by @kiran545 is not a standard "Common Log". Between source ip and date there should be two fields - usually empty and visible as "- -"
To verify this on some Squid instance I have configured common log using this directive:
`access_log /var/log/squid/access-common.log common`
and requested two resources for http and https ( https is intercepted in that configuration - it means the client machine is not aware of Squid Proxy)
`curl --user name:password http://www.example.com`
`curl -s https://google.com`
I got two lines in the Squid log:
`10.0.6.77 - - [08/Oct/2019:20:26:34 +0200] "GET http://www.example.com/ HTTP/1.1" 200 1777 TCP_HIT:HIER_NONE`
`10.0.6.77 - - [08/Oct/2019:20:27:15 +0200] "CONNECT 172.217.23.174:443 HTTP/1.1" 200 745 TCP_TUNNEL:ORIGINAL_DST`

In general Common Log is not a default option for Squid. If you skip log configuration - directive "access_log" then default Squid Native format is used for which filebeat I prepared.
If such Native Log is used then for the same requests following two logs are generated:

`1570559094.285    266 10.0.6.77 TCP_MISS/200 1769 GET http://www.example.com/ - ORIGINAL_DST/93.184.216.34 text/html`
`1570559316.871    260 10.0.6.77 TCP_TUNNEL/200 745 CONNECT 172.217.23.174:443 - ORIGINAL_DST/172.217.23.174 -`


When TLS/SSL connections are not intercepted by Squid (e.g. Linux client have environment variable https_proxy set) then Common Log for "curl -s https://google.com entry looks like:
`10.0.6.77 - - [08/Oct/2019:20:44:32 +0200] "CONNECT google.com:443 HTTP/1.1" 200 4454 TCP_TUNNEL:HIER_DIRECT`
and for Squid Native format:
`1570560119.256    320 10.0.6.77 TCP_TUNNEL/200 4455 CONNECT google.com:443 - HIER_DIRECT/172.217.22.14 -`

**Comment by kiran545** [comment]
@molu8bits  does that mean , the sample logs provided by me are customized ones?

**Comment by molu8bits** [comment]
Probably.
According to site [https://wiki.squid-cache.org/Features/LogFormat](https://wiki.squid-cache.org/Features/LogFormat)
Common Logfile Format consists of seven fields:
`remotehost rfc931 authuser [date] "method URL" status bytes`

One of rfc931 or authuser value should be set to Squid user if authentication is used  (I have no configuration with auth to verify this quickly, the other should be probably always empty. 
For default configuration both we should see as:
`remotehost **- -** [date] "method URL" status bytes`

**Comment by Randy-312** [comment]
I'll check in w/ the team that provides the 'standard' build we use.
A lot of companies have policies against tracking user credentials, and would remove the ability to log that field.  I've seen it replaced with '-' often, but it may be removed entirely here.

I'll get back to you.

**Comment by Randy-312** [comment]
While I'm checking on the CLF, I should mention that we're also looking to move over to Native log format as CLF doesn't provide as much value to us either.

Do continue the review for Native logging format, which I don't think the earlier samples necessarily reflect.

**Comment by molu8bits** [comment]
a.d. credentials: I think we won't see any credentials in squid logs, If Squid is configured with authentication there should be only username. That field I think is important for people using such authentication to build visualisations as it allows accountability. Old other tools like SquidAnalyser allowed to build quite useful graphs using field username.
a.d. CLF vs Native:  I've been always using Native Logs. I've seen some configuration on the Internet and imho not too much people use Comong Log. Anyway that could be solved by just adding two grok patterns in one filebeat for each of the type of log.

ps. I don't know if you aware that last version of my filebeat for Squid and ELK 7.x [https://github.com/molu8bits/squid-filebeat-kibana/tree/master/filebeat/module/squid](https://github.com/molu8bits/squid-filebeat-kibana/tree/master/filebeat/module/squid) was created by following procedure from https://www.elastic.co/guide/en/beats/devguide/current/filebeat-modules-devguide.html](https://www.elastic.co/guide/en/beats/devguide/current/filebeat-modules-devguide.html) so it should be very easy to adapt to your requirements. Of course after changing fields.yml to follow standard used by the other modules as it is mentioned in attached Excel file.

**Comment by kiran545** [comment]
below is the default log format which i tested with no prior customization:
1570638539.309    329 xx.xx.xxx TCP_TUNNEL/200 6324 CONNECT xxxxxxxxxxxxx.com:443 - HIER_DIRECT/x.x.x.x -
1570638732.009    320 xx.xx.xxx TCP_TUNNEL/200 6324 CONNECT xxxxxxxxxxxxx.com:443 - HIER_DIRECT/x.x.x.x -
1570639508.503    355 xx.xx.xxx TCP_TUNNEL/200 6324 CONNECT xxxxxxxxxxxxx.com:443 - HIER_DIRECT/x.x.x.x -

**Comment by Randy-312** [comment]
I found this [insightful.. ](http://www.squid-cache.org/Doc/config/logformat/), talking about the default formats.
![image](https://user-images.githubusercontent.com/12043436/66521139-2f497e00-eab0-11e9-98ce-b708d431f248.png)

**Comment by Randy-312** [comment]
the %ts.tu aligns to the squid format of seconds.milliseconds, which matches what was posted

**Comment by opoplawski** [comment]
Any more movement here?

**Comment by molu8bits** [comment]
@opoplawski 

https://github.com/elastic/beats/pull/19859

**Comment by Randy-312** [comment]
@molu8bits , I noticed in your merge request, you mapped the fields to ones starting with squid.access, which is a great start to align what type of squid logs they are.

Did you also map them into the official locations, like @webmat had talked about too?  I may have overlooked that.
But, having that mapping would allow for creation of standard dashboards across multiple proxy servers.
_For simplification (in a future release) it might also be good to only have this in one 'standard' place, with a way to identify what software created the log event._

> directly populating `url.scheme`, `url.port`, and when present `url.domain`. I also think it's worth capturing the whole string (e.g. `xxxx.s3.amazonaws.com:443`), and despite not looking very much like a full URL, I would put it in `url.original`. From the field's description:

I also wanted to thank you for keeping this moving forward!  Kudos!

**Comment by webmat** [comment]
We created meta-issue #938 to add proxy support in ECS. Closing in favor of the meta issue. Stay tuned :-)
