### ISSUE TITLE
Mapping syslog header fields to ECS

### ISSUE THREAD

**Issue by phruby02** [elastic/ecs#559]
I searched this forum and ECS guides for mapping syslog header fields to ECS, but I am still in doubt. Below is an example and a possible mapping. Is it consistent with the ECS intentions?   

Example: <134>1 2019-09-04T00:41:45Z fw-prv3 CheckPoint 10452 - [ ... structured data in the form of key-value pairs ... ]

The example above can be interpreted as follows, based on https://tools.ietf.org/html/rfc5424.

- <134> - PRI, Priority value, representing Facility and Severity. Priority value is calculated by multiplying the Facility number by 8 and then adding the Severity value. 
- 1 -  VERSION, version of the syslog protocol specification
- 2019-09-04T00:41:45Z - TIMESTAMP - formalized timestamp derived from RFC3339
- fw-prv3 - HOSTNAME, identifying the machine that originally sent the syslog message. Content of this field can also be FQDN or IP address 
- CheckPoint - APP-NAME, identifying the device or application that originated the message
- 10452 - PROCID, often used to provide the process name or process ID associated with a syslog system
- MSGID, identifying the type of message.

It seems that discussion on similar issues in this forum is inclining towards using log fields rather than event fields to represent the syslog priority value and header. However, ECS has currently only three log fields - level, logger and original, which is not sufficient to represent the example above in ECS. By adding custom fields a possible mapping of syslog fields to Elastic Common Schema could look like this:

- PRI: log.priority
- VERSION: log.version
- TIMESTAMP: log.timestamp
- HOSTNAME: log.hostname
- APP-NAME: log.provider
- PROCID: process.pid
- MSGID: log.code

Please let me know whether I am on the right track, or what could be adjusted?
Thanks,
Pavel

**Comment by webmat** [comment]
@phruby02 Please check out #525. I'll try to close on this PR this week. Read the discussion all the way to the end, as the PR's code will change.

But your thoughts on that PR are more than welcome.

Note that PR 525 is specifically about the Syslog priority fields. So here's my take on the rest of the fields, this is pretty standard stuff:

- Syslog version: we have nothing for that now, and the versions I've actually seen mentioned were rather one of two RFCs for the structure of the header. If you want to track this `version:1`, I think a custom field would make most sense, aka you're not going to find a match right now in ECS.
- `@timestamp` is meant to be the source's timestamp, whenever it's available. So I suggest you map your syslog timestamp to that. If you care about keeping the first time it was seen by your pipeline, the value already in `@timestamp` at ingestion time (with Beats and Logstash, at least) should be copied to `event.created`. All of the Beats modules do this as one of the first steps.
- `host.hostname` for the hostname. Careful that this is meant to be the hostname of where the event originates. If your pipeline has multiple Syslog forwarders adding their own headers, you need to take the hostname that maps to the source of the event, not the forwarders :-)
- `process.pid` 👍 
- `event.code` for well defined messages codes or IDs
- the application name can be put in `service.type`.
  - Note about field names `.type` and `.name`: in some places in ECS, we've established a pattern that `*.type` should contain the generic name of the software (e.g. nginx, httpd, my-custom-app) whereas its sister field `service.name` is meant to contain how it's being used. This lets you specific what this "nginx" actually doesg. So you could have two nginx deployments:
    - `service.type:nginx` and `service.name:nginx-proxy`
    - `service.type:nginx` and `service.name:nginx-php-fpm`

**Comment by phruby02** [comment]
Thanks!
Pavel

**Comment by webmat** [comment]
Check out specifically today's comment. I think this will be the final round on this :-)

https://github.com/elastic/ecs/pull/525#discussion_r328633874

I'll close this issue for now. Feel free to open separate issues if you have other questions :-)
