### ISSUE TITLE
ecs lowercase normalizer for host.name

### ISSUE THREAD

**Issue by willemdh** [elastic/ecs#56]
For a year or so I'm using a lowercase normalizer on some fields, which saves me several headaches. The root cause is that Windows tends to use uppercase hostnames while Linux uses lowercase hostnames. It's impossible to know before you search if you need to search lower or uppercase.  

Would it be an idea to add a default lowercase normalizer on certain ecs fields such as host.name (and maybe some other fields)? This way the original hostname is saved, but at least people can search for them in lowercase.

Example of my override of the default packetbeat template: 

```
PUT _template/packetbeat-overrides
{
  "order": 2147483646,
  "index_patterns": "packetbeat-*",
  "settings": {
    "analysis": {
      "normalizer": {
        "normalizer_lowercase": {
          "type": "custom",
          "filter": ["lowercase"]
        }
      }
    }
  },
  "mappings": {
    "doc": {
      "properties": {
        "beat": {
          "properties": {
            "name": {
              "type": "keyword",
              "ignore_above": 1024,
              "normalizer": "normalizer_lowercase"
            },
            "hostname": {
              "type": "keyword",
              "ignore_above": 1024,
              "normalizer": "normalizer_lowercase"
            }
          }
        }
      }
    }
  },
  "aliases" : {
    "packetbeat" : {},
    "beats-packetbeat" : {}
  }
```
}

**Comment by ruflin** [comment]
I remember we just had recently a discussion around this in Beats. Here is one related issue: https://github.com/elastic/beats/issues/7534 but there was also an other I couldn't find.

I don't think it should be up to ECS to have a convention here as there are definitively use cases where users want to have the case sensitive hostname. Instead it would be nice if this could be done on query time.

**Comment by willemdh** [comment]
> it would be nice if this could be done on query time

What do you mean with this? Like a Beat processor? Personally I like the normalizer better, as the data in Elasticsearch matches the real situation.

> I don't think it should be up to ECS to have a convention here as there are definitively use cases where users want to have the case sensitive hostname

I'll keep using my Beat override template then

**Comment by ruflin** [comment]
On query time I mean that even if we have `hoSt.local` and `Host.local` in the index, someone could write a query just for `host.local` and get both results, but I don't think this is possible.
