### ISSUE TITLE
Question: google admin activity log

### ISSUE THREAD

**Issue by weichea** [elastic/ecs#584]
Hello

Has anyone mapped out the google admin activity log to ecs schema? If yes, could you share it?

**Comment by jamiehynds** [comment]
@weichea The GSuite admin activity log is something we'd like to support in Elastic SIEM. Did you ever get around to mapping the events to ECS?

**Comment by weichea** [comment]
@jamiehynds Yea, we have mapped out some of the gadmin fields. Whats the best way for us share this?

**Comment by jamiehynds** [comment]
If you could drop me an email it'd be great - jamie.hynds@ elastic.co. Worth noting that we're not currently working on GSuite support, but would love to see the mappings you've done to date. Thanks!

**Comment by webmat** [comment]
A good way to capture these mappings could be via an online spreadsheet that you share publicly here (if you'r comfortable with that).

The column names could be like the ones supported by this experimental tool [ecs-mapper](https://github.com/elastic/ecs-mapper). So "source_field", "destination_field", and a few more if needed (see the [CSV Format](https://github.com/elastic/ecs-mapper#csv-format) heading).

**Comment by weichea** [comment]
@webmat let me check on the ecs-mapper.

Just a quick update, I'm getting approval internally before I can share the mapping. Shouldn't have any issue, hopefully I can get back next week.

**Comment by ebeahan** [comment]
Hi @weichea. It's been a bit, but wondering if you were able to obtain necessary approval to share your mappings?

**Comment by jamiehynds** [comment]
@weichea kindly provided Gsuite mappings to me via email. We are currently working on a new Beats module for GSuite, tracking here https://github.com/elastic/beats/pull/19769

**Comment by weichea** [comment]
@jamiehynds I have already sent it to you back in May... Do you want me to resend it?

**Comment by jamiehynds** [comment]
All good @weichea - I still have it. Thanks again :)

**Comment by ebeahan** [comment]
Excellent - thanks both for following up @jamiehynds @weichea !
