### ISSUE TITLE
Failed to parse mapping

### ISSUE THREAD

**Issue by johnsmith147258** [elastic/ecs#588]
Hello,

I'm using serilog to push log to elasticsearch and I have this error 

[2019-10-17T15:18:43,855][DEBUG][o.e.a.a.i.t.p.TransportPutIndexTemplateAction]  failed to put template [serilog-events-template]
org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_default_ : {dynamic_templates=[{numerics_in_fields={match_pattern=regex, path_match=fields\.[\d+]$, mapping={index=analyzed, omit_norms=true, type=string}}}, {string_fields={mapping={index=analyzed, omit_norms=true, type=string, fields={raw={ignore_above=256, index=not_analyzed, type=string}}}, match_mapping_type=string, match=*}}], _all={omit_norms=true, enabled=true}, properties={message={index=analyzed, type=string}, exceptions={type=nested, properties={ExceptionMessage={type=object, properties={MemberType={type=integer}}}, StackTraceString={index=analyzed, type=string}, HResult={type=integer}, RemoteStackTraceString={index=analyzed, type=string}, RemoteStackIndex={type=integer}, Depth={type=integer}}}}}]

Could you explain me whats the issue ?

**Comment by webmat** [comment]
Hello, it looks like you're trying to create a template with a setting that's no longer supported by Elasticsearch (`default`).

Please look at the serilog documentation, to make sure you're using versions of serilog and Elasticsearch that are compatible.

If that doesn't help, the right place to ask questions about Elasticsearch usage is on our Discuss forums at https://discuss.elastic.co, in the Elasticsearch section.
