### ISSUE TITLE
Mapping for DNS events

### ISSUE THREAD

**Issue by webmat** [elastic/ecs#596]
In communicating with an Elastic partner, I produced a stripped down DNS event in ECS format.

I thought I'd share it here, for the benefit of the community, who may be looking to feed DNS events from other sources into Elastic SIEM.

While not a mapping per se (it's just a final JSON event), seeing the shape of the event can be enlightening.

```JSON
{
  "dns": {
    
    "id": 23666,
    "op_code": "QUERY",
    "type": "answer",

    "question": {
      "name": "www.example.com",
      "type": "A",
      "class": "IN",
      "registered_domain": "example.com"
    },
    "header_flags": [
      "RD",
      "RA"
    ],

    "response_code": "NOERROR",
    "resolved_ip": [
      "10.0.190.47",
      "10.0.190.117"
    ],
    
    "answers": [
      {
        "data": "10.0.190.47",
        "name": "www.example.com",
        "type": "A",
        "class": "IN",
        "ttl": "59"
      },
      {
        "name": "www.example.com",
        "type": "A",
        "class": "IN",
        "ttl": "59",
        "data": "10.0.190.117"
      }
    ]
    
  },
  
  "network": {
    "type": "ipv4",
    "transport": "udp",
    "protocol": "dns",
    "direction": "outbound",
    "community_id": "1:19beef+RWVW9+BEEF/Q45VFU+2Y=",
    "bytes": 126
  },

  "source": {
    "ip": "192.168.86.26",
    "port": 5785,
    "bytes": 31,
  },
  "destination": {
    "ip": "8.8.4.4",
    "port": 53,
    "bytes": 95
  },

  "client": {
    "ip": "192.168.86.26",
    "port": 5785,
    "bytes": 31
  },
  "server": {
    "ip": "8.8.4.4",
    "port": 53,
    "bytes": 95
  },

  "event": {
    "duration": 122433000,
    "start": "2019-10-23T19:44:38.485Z",
    "end": "2019-10-23T19:44:38.607Z",
    "kind": "event",
    "category": "network_traffic",
  },
  
  "@timestamp": "2019-10-23T19:44:38.485Z",
  "ecs": {
    "version": "1.1.0"
  }
}
```

Domains and IPs of the innocent have been changed :-)

This event's `dns` and `network` sections are the most important for the DNS event, of course. It demonstrates differences vs Packetbeat's DNS schema, which was the inspiration for DNS in ECS.

Not all sources can populate all of these fields (thinking bout the `dns.answers` section in particular). But users should populate as many as possible, to get the best integration possible.

**Comment by bortok** [comment]
Hi @webmat ,

Could you please comment on compatibility of ECS "array of objects" datatype for dns.answers with Kibana limited support of such type and ECS FAQ statement "ECS does not use nested datatypes, which are arrays of objects." https://www.elastic.co/guide/en/ecs/current/ecs-faq.html ?

I just implemented a log parser for zeek.dns following ECS schema and this indeed doesn't work well with Kibana - dns.answers is being displayed as a single JSON object.

Best,
Alex

**Comment by webmat** [comment]
Yes, we try to avoid them as much as possible in ECS, as they aren't well supported in Kibana.

However in this case, we decided to keep it because the potential for various keys on these objects was really high, on DNSSEC records and potentially others. One mitigation we put in place was to have the resolved IPs (when the query does resolve to IPs) extracted in the array `dns.resolved_ip`. Arrays like this render much better in Kibana. We thought this was an acceptable tradeoff, as the `answers` array of objects can be so complex that there's no way to boil it down that still supports all kinds of answers you can get with DNS. So the expectation is that `dns.resolved_ip` and other short fields are what people are looking for most of the time, whereas `dns.answers` is kind of a "debugging section", where you can dig in to get all of the details of the exchange. You have to switch to the JSON pane to view that debugging, however.

If in your hunting there's other kinds of answers you frequently look at in aggregate, you're welcome to track them in custom fields. If you feel that such an aggregate would be beneficial to others, you're also welcome to open an issue on this repo to suggest what you have in mind :-)

Thanks for pointing out the FAQ statement. Seems like we need to soften it a little bit "we try to avoid it" now :-)

Finally, make sure to check out the Beat module for Zeek. Perhaps you can use it directly, or at least it can help you validate your mapping, if you can't use the Beats module.

**Comment by bortok** [comment]
Hi @webmat, after implementing dns.resolved_ip logic, it seems there is a gap between completeness of zeek.dns.answers and available ECS DNS fields. As you mentioned, dns.answers is really for "debugging". So, why don't expand ECS with dns.resolved_name field? Anything from zeek.dns.answers, for example, that is not an IPv4 or IPv6, would be copied into dns.resolved_name. That way it would be possible to capture CNAME to A resolution, as well as PTR, in Kibana-friendly format.
