### ISSUE TITLE
Consider adding an equivalent field to endgame.parent_process_name in ECS

### ISSUE THREAD

**Issue by andrew-goldstein** [elastic/ecs#597]
In the current version of ECS (`1.2` at the time of this writing), the [ECS Process fields](https://www.elastic.co/guide/en/ecs/current/ecs-process.html) have a field to store parent process id:

```
process.ppid
```

, however I'm not seeing a field to store the parent process name, which would be equivalent to:

```
endgame.parent_process_name
```

Please consider adding an equivalent field to `endgame.parent_process_name` in ECS.

_Originally posted by @andrew-goldstein in https://github.com/elastic/ecs/issues/589#issuecomment-543907968_

**Comment by webmat** [comment]
I agree with this, makes a lot of sense.
