### ISSUE TITLE
Numeric type fields : 'long'

### ISSUE THREAD

**Issue by zlammers** [elastic/ecs#602]
It appears that all numeric type fields are of 'type: long' in the ECS documentation.  Many of the current fields stating such should be much smaller numeric data types.  Here are some examples:

source.port | source.nat.port | destination.port | destination.nat.port : integer
log.syslog.facility.code | log.syslog.severity.code: byte
log.syslog.priority : short

The above list is not exhaustive - I'm sure there's more I didn't add above, but I couldn't find a numeric type that was not listed as long on quick review.  Certain fields (bytes/packets come to mind) should remain as long, of course.

**Comment by webmat** [comment]
Yes, we did it this way for simplicity's sake, and with the assumption that the storage savings of these smaller numerics would be negligible, compared to the size of a given event.

@jpountz in general, is it worth moving from `long` to smaller ints, when it fits the data? Is there an overhead per field that would make the savings irrelevant?

**Comment by jpountz** [comment]
There is no search-time benefit and very little index-time benefit from moving from `long` to `int`, `short` or `byte`.

**Comment by zlammers** [comment]
@jpountz That's surprising to me : there's no space benefit to using smaller numbers?  Is this true for older versions of ES, or only 6.x and/or 7.x ?  I've always kept numbers as small as possible (used to doing so for large RDBMS's I suppose)

Also, are there any metrics on 'very little index-time benefit' ?  We process multiple billions a day (~25b across multiple clusters), mostly in an ECS style schema (100-ish fields, maybe 15% numbers, we're migrating to ECS).   Taking one cluster for example, we can hit 250k EPS during peak business hours.  So the lower our index latency, the better - if there's a measurable benefit from going to smaller numbers, we would want to do so.  However, if even at that rate it's 'too hard to measure' I may just go the route suggested in the ECS doc and keep numbers as longs.

Thanks for the responses so far!

**Comment by jpountz** [comment]
@zlammers Elasticsearch dynamically figures out the number of required bits for integer datatypes. So if you index numbers in `[0,16)` for instance, it will use in the order of 4 bits per value regardless of whether the field is mapped as a byte, short, int or long.

Actually we rely on this internally by not having native support for bytes and shorts and just adding additional validation on top of the `int` datatype. So `byte`, `short` and `int` work exactly the same internally.

The reason for the little index-time benefit is that part of this compression needs to be deferred to when segments get written, so longs still use a bit more memory in the IndexWriter buffer than ints. As a consequence, you can fit more data in the IndexWriter buffer if you configure smaller data types. I believe this is a very small benefit though, and probably even more in your case where only 15% of fields are numbers.
