### ISSUE TITLE
ECS version showing as 1.1.0

### ISSUE THREAD

**Issue by PurpleV0id** [elastic/ecs#604]
I am running a new elastic instance based on 7.4.2 with the latest winlogbeat 7.4.2, I have sent the events to logstash and tried elasticsearch, all of my events are ecs.version 1.1.0.  The events are only from a win 10 workgroup machine at the moment.

**Comment by PurpleV0id** [comment]
ok I see the fields.yml now states is based on ecs 1.1.0
Looking through the beats release notes I can see 7.3.0 - Update to ECS 1.0.1. but no mention in the later beats of the newer version.  When is winlogbeat due to be updated?

**Comment by webmat** [comment]
Hi @PurpleV0id, this is a question related to Beats. Please ask Beats questions in the Beats section of discuss.elastic.co, or open issues on the Beats Github repo.
