### ISSUE TITLE
agent vs observer

### ISSUE THREAD

**Issue by enotspe** [elastic/ecs#607]
I am monitoring some firewalls via snmp from a logstash pipeline using snmp filter. Primarily, we are querying interface bw, cpu, mem, sessions.

What should the firewall be?? host?

What should logstash be? observer, agent?? I guess observer (like in heartbeat, when you ping a device, heartbeat server is the observer)

**Comment by webmat** [comment]
Agent and observer are both meant to capture details about a system performing the monitoring.

If the monitoring system is installed directly on the host, then it's an agent. If the monitoring system is doing its duty remotely, then it's an observer.

In both cases, the monitored system details should be captured as "host", however.

**Comment by MikePaquette** [comment]
Agreed.  
Yes, in this case:

- The Logstash system should be the observer.
- The monitored firewall should be the host.

I think it looks like this.
![image](https://user-images.githubusercontent.com/22619280/68897388-69cfb780-06fb-11ea-985a-3ba54df6224d.png)

Note: SNMP is a special case, as you _might_ have information about the SNMP agent running on the host. If you do have details in the event about the SNMP agent, you could populate them in the `agent.*` fields as well.

**Comment by enotspe** [comment]
thanks @webmat @MikePaquette 

One more question, what about when we receive syslog from a firewall via logstash?? 

firewall = observer
logstash???

I am asking because we have a multitenant deployment, meaning we have several logstash deployed, and some of them received logs from several tenants.

**Comment by MikePaquette** [comment]
> One more question, what about when we receive syslog from a firewall via logstash??
> firewall = observer
> logstash???

@enotspe In that case, the firewall is the observer and Logstash details are not captured by ECS.

Generally, Logstash (and other ETL or queueing system) details are not included in ECS fields.  The SNMP case where Logstash is the poller is an exception.

I think the standard firewall case you describe looks like this:

![image](https://user-images.githubusercontent.com/22619280/68949545-443cbf80-0788-11ea-9306-703069958288.png)

**Comment by enotspe** [comment]
thanks a lot for your answer @MikePaquette

**Comment by MikePaquette** [comment]
closing this one out.

**Comment by anubisg1** [comment]
This still confuses me... If a switch, like firewalls, switches, routers, LoadBalancers send syslog directly to logstash, what will those devices be? They seem to be that they should be both maybe?
