### ISSUE TITLE
ECS Docs search is broken for version 1.2

### ISSUE THREAD

**Issue by AndrewMcQuerry** [elastic/ecs#609]
When performing a search on the 1.2 version of the ECS docs, the search does not return as expected.

Example, searching for "class" within 1.2
https://www.elastic.co/search?fv-website_area=documentation&fv-product_name=Elastic%20Common%20Schema%20%28ECS%29&fv-product_version=1.2&q=class&size=20

Changing the version to 1.1 works:
https://www.elastic.co/search?fv-website_area=documentation&fv-product_name=Elastic%20Common%20Schema%20%28ECS%29&fv-product_version=1.1&q=class&size=20

Even "master" works:
https://www.elastic.co/search?fv-website_area=documentation&fv-product_name=Elastic%20Common%20Schema%20%28ECS%29&fv-product_version=master&q=class&size=20

**Comment by webmat** [comment]
Thanks for bringing this up, Andrew!

Hey @brianjolly who would be best equipped in the web team to help us fix search for the ECS section of the docs? We're happy to add any metadata to the asciidoc, if that can help in any way :-)

In the meantime Andrew I have two options for you as workarounds:

- Leverage Github's nice rendering of CSV (including real time filtering) over here: https://github.com/elastic/ecs/blob/v1.2.0/generated/csv/fields.csv
- Or check out the raw asciidoc file that backs the ECS fields documentation over here. All fields on one (looong) page: https://github.com/elastic/ecs/blob/v1.2.0/docs/field-details.asciidoc

Hope this helps

**Comment by ebeahan** [comment]
Following up on this issue, I can't reproduce the described behavior. However, I will investigate if others experience problems searching the ECS docs.
