### ISSUE TITLE
Add Elastic SIEM and Elastic Endpoint Security to list of Products and Solutions

### ISSUE THREAD

**Issue by MikePaquette** [elastic/ecs#619]
Documentation page https://www.elastic.co/guide/en/ecs/current/ecs-products-solutions.html should be updated to list Elastic SIEM App and Elastic Endpoint Security Server.

![image](https://user-images.githubusercontent.com/22619280/69254782-c6602600-0b84-11ea-812b-bb361316939e.png)

**Comment by webmat** [comment]
Makes sense. I'd like these new entries to link to somewhere.

* For SIEM I would link to the SIEM documentation section
* What should the link be for Endpoint?

**Comment by MikePaquette** [comment]
> What should the link be for Endpoint? [This product page](https://www.elastic.co/products/endpoint-security)?

Yes, for now that seems best, thanks.

**Comment by webmat** [comment]
Would be nice to link up the other bullet points as well.

@benskelker would you have some free cycles to tackle this issue?

**Comment by benskelker** [comment]
@MikePaquette @webmat 
yes

**Comment by webmat** [comment]
Hey no arm twisting ;-)

I want to close on #569 after the release next week. Since it's docs, I'll be able to backport to a few past versions (so it's not time sensitive vs the actual release)

**Comment by ebeahan** [comment]
This has been added to https://www.elastic.co/guide/en/ecs/current/ecs-products-solutions.html
