### ISSUE TITLE
New field: event.subcategory

### ISSUE THREAD

**Issue by vbohata** [elastic/ecs#645]
Some systems define events by category and subcategory. For example Windows event log - each event is categorized to category + subcategory by its event id, such as:
- System / Security System Extension
- Policy Change / Other Policy Change Events

Currently there is no ECS field to put the subcategory to. It would be nice to have a new field for this:
- event.subcategory

**Comment by MikePaquette** [comment]
@vbohata thanks for the suggestion.  I've been discussing this with some other folks recently about the idea of using ECS `event.type` field as a kind of subcategory.

Quick question:  in the examples you provided, if there were an `event.subcategory` field, how would you map them to `event.category` and `event.subcategory`?

**Comment by vbohata** [comment]
(Not only) windows event logs are categorized to category and subcategory by design. I would just use these names, so:
- event.category: System
- event.subcategory: Security System Extension

I think event.type is not well suited for this, for me the event type is something like:
- event.type: AUDIT
- event.type: APPLICATION_LOG
...

**Comment by ebeahan** [comment]
This predates the publishing of the event categorization fields, and I'm closing.
