### ISSUE TITLE
new winlogbeat exported field

### ISSUE THREAD

**Issue by janniten** [elastic/ecs#653]
Hi @webmat ,
I would like to propose a new winlogbeat field.
Where do I find the definition of those extended fields in order to create a PR and propose a new one?

Thank you
Regards
Ana

**Comment by webmat** [comment]
Your best bet for this is to open the issue on the Beats repo and tag it Winlogbeat.

The overall field definitions for custom Winlogbeat fields are here: https://github.com/elastic/beats/blob/master/winlogbeat/_meta/fields.common.yml

Then depending on the beats, there's often other `_meta/fields.yml` files per event sources, like the various modules. For example the security module's specific fields would be in this directory: https://github.com/elastic/beats/blob/master/x-pack/winlogbeat/module/security/_meta/fields.yml

Thanks for all of your help, Ana :-)
