### ISSUE TITLE
New top-level object: search

### ISSUE THREAD

**Issue by joshdevins** [elastic/ecs#666]
I'm working on building search event capture and metrics calculation into the Stack (prototype only so far) and want to raise the possibility of adding to the top level of ECS a `search` object. So far I am ingesting two event types into a single index: `query`, `click`. I extended ECS with the following fields and from this, I am able to use [transforms](https://www.elastic.co/guide/en/elasticsearch/reference/7.4/transforms.html) to calculate some basic per-query search metrics: number of clicks, max reciprocal rank, mean reciprocal rank, sum reciprocal rank (used for later aggregations and metrics) time to first click, time to last click. 

I'm not ready to suggest concrete extension and fields but on @MikePaquette 's suggestion, I wanted to get early feedback on the general idea and source input on how to possibly structure the schema.

Additional open topics so far:
 - What should the schema of the transform which adds the metrics be.
   - Should it be ECS as well?
   - How would we support adding new or user-defined metrics then?
 - We can simplify and remove some fields (like rank from click) if we put more responsibility on the transform to calculate fields
 - Need to support pagination fields (which page of the results were clicked)
 - Need to (ideally) support other event types like "business objectives" that resulted from the search results and clicks. Things further down the funnel and value-chain such as, item added to shopping cart, item purchased, track played, user followed, etc.

Prototype schema additions:

- search
  - query
    - id: generated either by the application layer or maybe Elasticsearch
    - value: the query string itself - only included when the event is a `query`
  - results
    - size: size of the result set displayed
    - ids: document IDs returned/displayed
  - click: only included when the event is a `click`
    - result
      - id: document ID of the clicked document
      - rank: rank in the result set of the clicked document
  - ab: A/B testing properties -- these are mostly for demo purposes but could be here as well
    - experiment: name of the experiment
    - variant: name of the variant of the experiment that the user was exposed to

```json
      "search": {
        "properties": {
          "query": {
            "properties": {
              "id": {
                "ignore_above": 1024,
                "type": "keyword"
              },
              "value": {
                "ignore_above": 1024,
                "type": "keyword"
              }
            }
          },
          "results": {
            "properties": {
              "size": {
                "type": "long"
              },
              "ids": {
                "ignore_above": 1024,
                "type": "keyword"
              }
            }
          },
          "click": {
            "properties": {
              "result": {
                "properties": {
                  "id": {
                    "ignore_above": 1024,
                    "type": "keyword"
                  },
                  "rank": {
                    "type": "long"
                  }
                }
              }
            }
          },
          "ab": {
            "properties": {
              "experiment": {
                "ignore_above": 1024,
                "type": "keyword"
              },
              "variant": {
                "ignore_above": 1024,
                "type": "keyword"
              }
            }
          }
        }
      },
```

**Comment by andrewstucki** [comment]
Personally, I'd love to see if there are multiple vendors/a generalized use-case for this -- some pre-existing search auditing frameworks or something like that?

With regard to some of the field mappings:

> - click: only included when the event is a click
>   - result
>     - id: document ID of the clicked document
>     - rank: rank in the result set of the clicked document
> - ab: A/B testing properties -- these are mostly for demo purposes but could be here as well
>   - experiment: name of the experiment
>   - variant: name of the variant of the experiment that the user was exposed to

My initial thought is that these are too implementation-specific to fit within the context of some sort of `search` scheme.

The others, `query` and `results` seem to fit more inline with the definition of what most `search` concepts would involve. The subfields for `query` and `results` like `id` and `ids` likely would need to be a bit more generalized to be re-usable in this space.

In the case of fields that don't necessarily map directly to ECS, there's always the custom field route or figuring out if it makes sense to model those in some other area of the schema.

**Comment by joshdevins** [comment]
> Personally, I'd love to see if there are multiple vendors/a generalized use-case for this -- some pre-existing search auditing frameworks or something like that?

AFAIK, there are no vendors doing this kind of things. It's typically built in-house by a team building a search experience. However there are many companies that either don't have this kind of staff, or they don't have time, knowledge, expertise, etc. Internally, this can also be a viable solution for *Search solutions (Swiftype) to base analytics off of. They log in a similar fashion already, but don't have per-query metrics available, for example. I'm looking to validate the schema with a few customers that are doing these types of analytics already on a home-made solution.

> My initial thought is that these are too implementation-specific to fit within the context of some sort of search scheme.

I'm new to ECS so I will be relying on others to help figure out which should be in the schema and which should just be extensions like using `labels`. For example, I would remove the `ab` field set and let people use the key-value pairs of `labels`.

The things that should be in the schema (I think) are those that are standard, necessary for calculating a basic set of metrics, and useful for downstream tasks that are coming such as LTR (learning to rank). So that's why we need `click.result.rank.*`.

> The subfields for query and results like id and ids likely would need to be a bit more generalized to be re-usable in this space.

How so more generalized? ID's are just opaque keywords in this schema which should really fit any ID scheme.

> In the case of fields that don't necessarily map directly to ECS, there's always the custom field route or figuring out if it makes sense to model those in some other area of the schema.

Would `lables` be appropriate for plain key-value types like A/B testing labels? Or is there another recommended way to extend ECS/use custom fields? I assume it's all just dynamic mapping anyways so they could add something that is use-case specific to, for example `search.query.foo`.

The alternative is to not use ECS at all, but there are a lot of useful fields already defined for things like user source (ID, IP, geo, etc.), amongst others.

**Comment by joshdevins** [comment]
Please see the related [PR](https://github.com/elastic/ecs/pull/729) for a more up-to-date spec.
