### ISSUE TITLE
Upper and Lowercase Normalisers

### ISSUE THREAD

**Issue by mbudge** [elastic/ecs#682]
Hi, 

We add a lot of upper and lower case normalisers to our beats and custom ECS mappings. 

Would it be worth adding this to the common schema (and beats templates) so it's easier to search data, with lower risk of missing documents as keyword fields are case sensitive?

Example dns mapping

analyser

                "analysis": {
  		"normalizer": {
  			"lowercase_normalizer": {
  				"type": "custom",
  				"filter": ["lowercase"]
  			},
  			"uppercase_normalizer": {
  				"type": "custom",
  				"filter": ["uppercase"]
  			}
  		}

mapping

`

          "question": {
            "properties": {
              "class": {
                "ignore_above": 1024,
                "normalizer": "uppercase_normalizer",
                "type": "keyword"
              },
              "etld_plus_one": {
                "ignore_above": 1024,
                "normalizer": "lowercase_normalizer",
                "type": "keyword"
              },
              "name": {
                "ignore_above": 1024,
                "normalizer": "lowercase_normalizer",
                "type": "keyword",
                "fields": {
                  "ngram": { 
                    "type": "text",
                    "analyzer": "ngram_analyzer"
                  }
                }
              },
              "registered_domain": {
                "ignore_above": 1024, 
                "normalizer": "lowercase_normalizer",
                "type": "keyword"
              }, 
              "subdomain": {
                "ignore_above": 1024, 
                "normalizer": "lowercase_normalizer",
                "type": "keyword"
              }, 
              "top_level_domain": {
                "ignore_above": 1024, 
                "normalizer": "lowercase_normalizer",
                "type": "keyword"
              },
              "type": {
                "ignore_above": 1024,
                "normalizer": "uppercase_normalizer",
                "type": "keyword"
              },
              "response_code": {
                "ignore_above": 1024, 
                "normalizer": "lowercase_normalizer",
                "type": "keyword"
              }
            }
          },

`

**Comment by jgregmac** [comment]
I agree with the need for standard ways to deal with case-preserved fields that require case-insensitive searches.  I came up with a different solution for our scenario.  In our case, we want to be able to perform case-insensitive searches for file names (which matches Windows file naming standards), while still allowing case-sensitive searching (which could be needed for Linux filesystem searches, under some circumstances).

I use a normalizer to force lowercase indexing of the base keywords, then add a second "raw" field using a standard keyword analysis.

Analysts get case-insensitive results to searches on the "file.name" field, and case-sensitive results for "file.name.raw".

```json
{
    "settings": {
        "analysis": {
            "normalizer": {
                "lowercase": {
                "type": "custom",
                "filter": ["lowercase"]
                }
            }
        }
    },
    "mappings" : {
        "properties" : {
            "file" : {
                "properties" : {
                  "directory" : {
                    "ignore_above" : 1024,
                    "type" : "keyword",
                    "normalizer" : "lowercase",
                    "fields" : {
                      "raw" : {
                        "type" : "keyword"
                      }
                    }
                  },
                  "path" : {
                    "ignore_above" : 1024,
                    "type" : "keyword",
                    "normalizer" : "lowercase",
                    "fields" : {
                      "raw" : {
                        "type" : "keyword"
                      }
                    }
                  },
                  "name" : {
                    "ignore_above" : 1024,
                    "type" : "keyword",
                    "normalizer" : "lowercase",
                    "fields" : {
                      "raw" : {
                        "type" : "keyword"
                      }
                    }
                  }
                }
            },
            "process" : {
                "properties" : {
                  "executable" : {
                    "ignore_above" : 1024,
                    "type" : "keyword",
                    "normalizer" : "lowercase",
                    "fields" : {
                      "raw" : {
                        "type" : "keyword"
                      }
                    }
                  },
                  "name" : {
                    "ignore_above" : 1024,
                    "type" : "keyword",
                    "normalizer" : "lowercase",
                    "fields" : {
                      "raw" : {
                        "type" : "keyword"
                      }
                    }
                  }
                }
            }
        }
    }
}
```

**Comment by djptek** [comment]
Hi @mbudge , while there is definitely value in adding upper and lower case normalisers, for example in order to improve efficiency by moving processing to ingest time rather than retrieval time, this is only relevant to a sub-set of ECS's intended use cases. The complementary use case set would not benefit from the addition and may require additional resources to process or store these so perhaps it would be better not to add these to ECS.

The recommended path to integrate additional fields alongside ECS is by using the [ECS Toolset](https://github.com/elastic/ecs/blob/main/USAGE.md) to merge custom fields with the ECS Fields that best fit your use case.

Closing for now, please feel free to re-open if you would like to continue this discussion.
