### ISSUE TITLE
Recommened way to map custom date formats to for example event.created with ingest pipeline

### ISSUE THREAD

**Issue by willemdh** [elastic/ecs#70]
Hello,

I was wondering what's the recommended way to map a field to an ecs date field. Let's say I try to assign a timestamp to `event.created`.

So I took the official ecs template which has:

```
        "event": {
          "properties": {
            "created": {
              "type": "date"
            }
```

Es cluster logs gives me a `org.elasticsearch.index.mapper.MapperParsingException: failed to parse [event.created]` because `Invalid format: "2018-08-07 22:51:09" is malformed at " 22:51:09"`

My pipeline looks like:

```
PUT _ingest/pipeline/filebeat-nagios-audit
{
  "description": "Filebeat Nagios Audit Pipeline",
  "processors": [
    {
      "set": {
        "field": "pipeline",
        "value": "filebeat-nagios-audit"
      }
    },
    {
      "grok": {
        "field": "message",
        "patterns": [
          "%{TIMESTAMP_ISO8601:event.created} - %{GREEDYDATA:event.category} \\[%{NUMBER:event.type_id}] %{GREEDYDATA:user.name}:%{IPORHOST:source.ip} - %{GREEDYDATA:log.message}"
        ]
      }
    },
    {
      "date": {
        "field": "event.created",
        "target_field": "@timestamp",
        "formats": [
          "yyyy-MM-dd HH:mm:ss"
        ],
        "timezone": "Europe/Brussels"
      }
    },
    {
      "gsub": {
        "field": "source.ip",
        "pattern": "localhost",
        "replacement": "127.0.0.1"
      }
    }
  ]
}
```

So should I update the date type format of `event.created` or should I map to a temporary field and then use the date processor to `event.created`?

**Comment by ruflin** [comment]
I would adjust the date type format in case all your events have the same date format. It should not have an affect on how you query the data.

**Comment by willemdh** [comment]
Ok, i'll adjust the date fomat
