### ISSUE TITLE
Clarify that full-text-search convention is compatible with nesting convention

### ISSUE THREAD

**Issue by andrewthad** [elastic/ecs#714]
According to ECS's guidelines page, objects should be nested:

> The document structure should be nested JSON objects. If you use Beats or Logstash, the nesting of JSON objects is done for you automatically. If you’re ingesting to Elasticsearch using the API, your fields must be nested objects, not strings containing dots.

Cool, don't use dots in object keys. But then on the conventions page, we see that using dots in keys is recommended for fields that need full-text search:

> So the ECS multi-field convention for text is:
> * Canonical field: `myfield` is keyword
> * Multi-field: `myfield.text` is text

I haven't actually tried this out yet, but I assume these are compatible because in Elasticsearch, a multi-field turns one field into two or more fields, so insertion and retrieval don't actually show the extra field. Or at least that's my interpretation. If this is correct, I'd like to mention this in the documentation.

**Comment by webmat** [comment]
Your interpretation sounds mostly correct, yes.

However the multi-fields are not adding dots in keys in the document. The multi-fields are purely a feature of Elasticsearch mappings, where ES is instructed to index a given key in multiple ways.

In the documentation example we're saying a document such as `{"myfield":"foo bar baz"}` would index `myfield` as `keyword` -- the default for text fields in ECS. Then the same document has `myfield` also indexed as `text` for full text search. The full text search queries are performed via the `myfield.text` key name.

But no matter how we query Elasticsearch, that document still looks like `{"myfield":"foo bar baz"}`, there's no key with dots in it.

I don't think the fact that it's queried via `myfield.text` is inconsistent with other parts of ECS. You'll notice that querying any nested field -- such as `source.ip` -- references a nested field (`{"source":{"ip":"192.0.2.1"}}`). So the dots are always a query time shorthand to reference the nesting.

If we dig deeper, there's other subtleties on the Elasticsearch side that could be explained around  nesting vs dots, and whether Elasticsearch mappings have a concept of nesting (they don't). But I think that's outside the scope of ECS to explain.
