### ISSUE TITLE
Making of all objects reusable

### ISSUE THREAD

**Issue by vbohata** [elastic/ecs#72]
I have seen a lot of use cases to use host and other objects inside the another ones. Also mentioned in couple of issues here). I think all or almost all objects should be designed to be reusable. Just now I found another field name which could cause a collision in the future:

user_agent.device, .. vs. device object. In user_agent the device is keyword, but should be renamed to user_agent.device.name or user_agent.device_name, so everyone could put device fields inside user_agent. Maybe not the best example with user_agent but if anybody see device, it should be related to device.* object. Like host.name vs hostname ...

If not possible in all cases the documentation should clearly mention it. For each field group there should be info if it is mentioned to be only top level or reusable in any level.

**Comment by ruflin** [comment]
++ on what you wrote above. The same name should always have the same meaning and properties. I think #62 is the same issue and I opened a PR for this here: https://github.com/elastic/ecs/pull/74 Do you want to open a PR for the device issue? Any other items you see where we need a change?

Would be good to get your feedback on https://github.com/elastic/ecs/issues/71

**Comment by vbohata** [comment]
Yes, open a PR for the device please. At this time I do not see any items needing a change (as you wrote a PR for host has already been opened).
I also added feedback to the issue you mentioned.

**Comment by ruflin** [comment]
We now defined the ones that are reusable. Please open a PR if you think some more should be reusable.
