### ISSUE TITLE
Log content-related fields should not be at the first level

### ISSUE THREAD

**Issue by vbohata** [elastic/ecs#73]
I am currently trying to use some ECS fields for messages sent by filebeat and parsed by logstash into several fields. It looks like very messy to mix device or metadata fields like "host", "device", ... with log content fields like "url.*". I propose that all log content (parsed log line/message) should be nested the same way. So instead of having "url.*" or something like "iis.url.*" there should be something like "logdata.url" or something like "meta.log.offset", ... and "data.log.url.path", ... or just "log.*" and rename current "log" field because it is also a little bit confusing with event.

So instead of having:
source.ip
client.ip
...

It would be nice to have something like:
source.ip, or event.source.ip or ...
log.client.ip

So for everybody it is clear that client.ip is related to the log content, not to the originator of log or ...

**Comment by vbohata** [comment]
Also this gets worse if the log originator is sending just json with its own field names, and every version it changes these names :). In this way this it impossible to rewrite all these fields so it has to be somehow anchored (for example under log. field or "log.data" field). For some use cases (in fact cases when not using *beats) it seems it is pointless to define "data" fields in ECS. Maybe it would be easier to focus only on metadata related fields in ECS ... I know for correlation it is not ideal but the field correlation for non-beats agents/systems is often impossible.

**Comment by ruflin** [comment]
I'm not sure I can fully follow on this. I think for correlation purpose it is important that we don't treat log or metrics data different with a prefix as otherwise we can't correlate.

If some of your fields don't match with ECS you should put them under your own prefix, you should only use ECS for the ones that match.

I'm aware of the json logs problem. The way I solve it is to decode the json into a service specific object, for example `kibana.meta` and then use the ingest rename processor for the fields that match ECS. If you can't use the ingest processor and renaming cannot happen on your agent, you could use `copy_to` or perhaps the alias feature.

**Comment by ruflin** [comment]
For the postgres case: 

* Yes only a subset will be mapped to ECS
* For the other fields there is also the option that the fields inside the postgres object stay as a field alias (https://github.com/elastic/elasticsearch/issues/31372)

I was also thinking if users will be confused on what belongs to postgres and what not. The reason I hope this is not a big issue is that everything will be in one json document. And if that is not enough, we have the field alias option to make it clear that it belongs to postgres.

For the collision: It will definitively happen but that will be the case whatever we come up with. At the same time I think the top level entries are so generic that it is unlikely it will collide with any service. If there is a service it will have to work around ecs like naming it `geo-app` for example. If we have a custom namespace for all custom fields, I think the likelyhood that two fields may conflict is much higher. 

I understand the request to separate data directly coming from the event itself (and I think that not only applies to log data but also metrics) and what is enrichment of the event. The challenge I see here is that in some cases the same fields can be meta data or part of the event itself and I want to correlate them. So if they are in two different locations, this becomes tricky. Let's take docker metadata as an example here. It can be attached to an even coming from a container. At the same time the data is part of a metric event fetched about this docker container. If I want to get all info about a container, I will potentially want to know all data about this container, which are events fetched from the service in the container but also the metrics about the container.

**Comment by vbohata** [comment]
It depends. For example I have logs which contains "organization.id". It is part of the log content itself. But if someone wants to enrich the data with organization the log belogs to ... it creates problem.

**Comment by ruflin** [comment]
There are two solutions to this: Either you put both valued into `organization.id` or you must decide which one is the one you want to correlate on and put it in their. The other value I would suggest to put under a prefix which is describes the log you are fetching it from.

**Comment by ebeahan** [comment]
Closing this as stale - please feel free to open a new issue if something still needs to be addressed.
