### ISSUE TITLE
Add a logstash_id field  - Feature request

### ISSUE THREAD

**Issue by mbudge** [elastic/ecs#730]
Hi, 

Not sure where to add it but a logstash_id field would be a good idea. 

It would allow customers to identify which logstash server redirected the logs.

This helps with debugging and operational issues.

It could be an object like 

logstash.id
logstash.name
logstash.location
logstash.hostname
logstash.pipeline_id

Thanks,

Matthew

**Comment by jasonneurohr** [comment]
+1 this. I have a step in my pipeline to add "ls_node" to capture the current Logstash node name for debugging.

**Comment by webmat** [comment]
We created meta-issue #940 to discuss capturing pipeline details in ECS. Closing in favor of the meta issue.
