### ISSUE TITLE
Keyword multi field for some numeric fields

### ISSUE THREAD

**Issue by vbohata** [elastic/ecs#735]
Is there any plan to support keyword multi field for source port and similar fields for make them available in Kibana ML? See https://github.com/elastic/ecs/issues/104#issuecomment-415526828, https://discuss.elastic.co/t/can-not-split-by-number-fields-in-multi-metric-machine-learning-jobs/93081, https://discuss.elastic.co/t/numeric-population-fields-in-population-job/171095

**Comment by webmat** [comment]
@randomuserid Has this been a problem for you so far, with ML? I wasn't aware of this limitation.

**Comment by webmat** [comment]
Based on the answer in the second linked discuss post, it sounds like it's possible to do it now? My understanding is that it's discouraged by not being in the default UI, but it's available in the "Advanced" section.

If I'm misreading the answer mentioned above, the approach you mention in https://github.com/elastic/ecs/issues/104#issuecomment-415526828 sounds good to me. I think adding custom multi-fields to ECS fields is a valid thing to do.

**Comment by webmat** [comment]
Closing as I think this was a misunderstanding of the capabilities around numerics. Please reopen if that's not the case.
