### ISSUE TITLE
Endpoint Metadata Introducing a Variant Field to host.os type

### ISSUE THREAD

**Issue by nnamdifrankie** [elastic/ecs#744]
This is a follow up to the conversation on the slack channel about the impact of introducing a custom field to ECS **host.os** ype. The Elastic Endpoint Team had a need to futher qualify or classify linux based operating system(OS). We considered distribution (distro) which is a linux concept that indicates what is packaged with the OS and by what entity. But we resolved to use variant as a canonical field so we are portable across all OS. 

This issue is to make the ECS team aware of the changes and to consider if this is a field that the want to commit to the ECS schema.

**Comment by webmat** [comment]
Thanks for opening this. This is related to #576 as well

**Comment by webmat** [comment]
I'll close this one in favour of #576. I think we'll be going through the RFC process to revise all of the OS fields.

When that happens, we'll definitely want feedback from the Endpoint team. So make sure you subscribe to the other issue, or drop additional thoughts there :-)
