### ISSUE TITLE
Need new "Implementing ECS" reference location

### ISSUE THREAD

**Issue by matschaffer** [elastic/ecs#745]
A few places in the docs (e.g., https://www.elastic.co/guide/en/ecs/current/ecs-http.html, https://www.elastic.co/guide/en/ecs/current/ecs-network.html) have this phrasing:

> The field value must be normalized to lowercase for querying. See the documentation section "Implementing ECS".

But it looks like that doc section got removed in https://github.com/elastic/ecs/pull/400/files#diff-4011c9c185cee17fb59160d47c1b81dfL12

Seems like https://www.elastic.co/guide/en/ecs/current/ecs-guidelines.html is probably the new location to reference but it lacks the [Lowercase Capitalization](https://github.com/elastic/ecs/pull/400/files#diff-4011c9c185cee17fb59160d47c1b81dfL69) section that we seem to be referring to in that comment.

I _think_ the value lowercasing advice might also apply to log.leve in https://www.elastic.co/guide/en/ecs/current/ecs-log.html, but would be good to clear up the intention of the existing docs before I open an issue on that I think.

**Comment by webmat** [comment]
Thanks for pointing this out.

I think the way we'll solve this is to leverage a new mechanism we've used to identify which fields are expected to be arrays #727. 

Using this mechanism, we'll more formally identify which fields should be normalized to lowercase. This issue could be used to vote on additional fields that should be marked as such. We initially had:

* `network.application`
* `network.protocol`
* `network.transport`
* `network.type`
* `http.request.method`

You're suggesting to add to the list:

* `log.level`

This makes sense as well. Although we had discussed normalizing this field even more here #129.

Anybody reading this, thinking about normalizing some other fields are welcome to chime in here. The criteria for which fields this would apply to is: we want to avoid loss of information. Short keyword fields like protocol names, other standard names or fields provided by agents are all good candidates for normalization. Any field that contains information where we may want to hunt for threats (file names, process details, etc) won't qualify, as we want to preserve original case. 

For those where we want to preserve the original case, we'll instead have to look at ways to offer case sensitive and case insensitive search, likely via a multi-fields. Someone mentioned that recently, but I can't find the issue or discuss post.
