### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by hazcod** [elastic/ecs#765]
Hi, i'm having difficulties interpreting this in real world scenarios.
Suppose I have an event from a network firewall that contains information about `user`,`http`,`network` and `application`. How would that work?
Will I need to split the log event into multiple events, or do they layer one over another?

**Comment by MikePaquette** [comment]
@hazcod good question.

ECS has been scoped for storing and analyzing _event_ data, such as logs and metrics, in Elasticsearch.  Generally one Elasticsearch document is created per _event_, where that event could be a  "thing that happened", a request/response transaction, or a measurement of numeric or categorical metrics.

So in your example, if the firewall log event contains details of a single "thing that happened", then you do not need to split the log event into multiple events — simply populate the `user.*`, `http*`, and `network.*` ECS fields with the information from your firewall event, in addition to other relevant ECS field sets.  See below for an example of which ECS field sets are typically populated when NGFW logs are mapped to ECS.

However, less commonly there could be cases where details about multiple "things that happened" are included in one log message.  These are sometimes referred to as "compound events."  For compound events, it can be better to split the log into multiple events during the ingestion process to maintain the one-Elasticsearch-document per event relationship.

Hope this helps.

Example of ECS field sets typically populated when mapping NGFW logs to ECS:
![image](https://user-images.githubusercontent.com/22619280/75574945-3821f880-5a2d-11ea-9695-4575e61ad87d.png)

**Comment by hazcod** [comment]
Thank you for the indication @MikePaquette.
Would it be possible to include a real log line/event in the README?

**Comment by webmat** [comment]
We now have a more concrete walk through this thinking in the [getting started](https://www.elastic.co/guide/en/ecs/current/ecs-getting-started.html) documentation page.
