### ISSUE TITLE
related.file field

### ISSUE THREAD

**Issue by janniten** [elastic/ecs#767]
Hi,
While working with file manipulation audit events,  I realize that could be useful to have a related.file in order to be able to track when a file was moved/renamed/copied/modified and easily detect the source file and the substituent operations
One example that comes into my mind now: new malware technique evades detection by simply copying a file. Having the related.file can speed up the identification of the original file.

Does it make sense? If so, I can open a PR

Regards
Ana

**Comment by dcode** [comment]
are you auditing the actual file rename/copy? what would that event look like. I've been looking at files that contain other files or when malware drops other files. A useful analytic would be to traverse a tree of file and/or process objects to characterize the relationships among the files and processes. What did you have in mind?

**Comment by janniten** [comment]
Hi, I'm auditing file renaming (in this case through Netapp ONTAP auditory). 
This is particularly of our interest because the file renaming is an activity seen as a part of ransomware behavior.
If we have the related.file.* we think is it easier to identify the relationship, as you have mentioned
Below part of an event related to rename files

![image](https://user-images.githubusercontent.com/33020901/77559107-0aa95d00-6ebc-11ea-8a32-a4ffe399b0d5.png)

**Comment by webmat** [comment]
We're thinking about going with this approach instead, WDYT? https://github.com/elastic/ecs/issues/1076

**Comment by janniten** [comment]
LGTM
Anyway I'll try to find cases that could not be modeled like https://github.com/elastic/ecs/issues/1076
(I hope I am not successful)

**Comment by webmat** [comment]
Alright, I'll close this one then.

We haven't tackled Samir's suggestion yet over in #1076, but I suspect that when we do, we'll consider more than the 3 fields he's currently requesting.

If you find more fields that would be useful, as always you're welcome to let us know over in there :-)
