### ISSUE TITLE
Is master stable?

### ISSUE THREAD

**Issue by ansoni** [elastic/ecs#768]
Running into all sorts of issues trying to build from master.

https://github.com/elastic/ecs/blob/master/scripts/generators/csv_generator.py#L5 
should most likely by "from generators import ecs_helpers"

Ran into issues with the registered code here (causing a python non-ascii exception):  https://github.com/elastic/ecs/blob/master/schemas/pe.yml#L40

While I did wrap some custom automation around ECS to make it easily extendable for me, I don't think my thin wrappers are causing these issues (my thin wrappers actually allow me to work around it:-/

Is master not stable?

**Comment by webmat** [comment]
The code is stable, yes. Code that breaks CI doesn't get merged.

Make sure you're using the correct language versions. See [CONTRIBUTING.](https://github.com/elastic/ecs/blob/master/CONTRIBUTING.md)

If that doesn't help, can you share the errors you're seeing?

**Comment by webmat** [comment]
Closing for now. Don't hesitate to reopen if you have more details to provide :-)

**Comment by ansoni** [comment]
Thanks Martin.  I did find some version issues with my local python.  I would say that moving the build system from virtualenv to docker would probably help with having the consistent go and python version for a build.
