### ISSUE TITLE
Introduce log.file.path and friends

### ISSUE THREAD

**Issue by roncohen** [elastic/ecs#770]
Filebeat uses `log.file.path` to describe the file from which a log line was harvested. There’s no such ECS field. [This](https://github.com/elastic/ecs/blob/54f600d76cebcfcf121e1666a2ea8f2c72c6b892/use-cases/logging.md) describes `source.path` which also does not seem to exist in ECS. There’s `file.path` which probably is meant to mean that a specific log line contained a reference to a file, rather than that the log line was read from that file. Would be great to get `log.file.path` into ECS.

**Comment by webmat** [comment]
Agreed.

You're right that `file.*` at the top level is meant to capture details about files that are mentioned in the event itself.

`log.*` is mostly meant to capture metadata about the source of a log, so adding `log.file.path` for the source of a log event would make sense.

My first instinct would be to add this single field only, not nest all of `file.*` at `log.file.*`. Makes sense?

**Comment by roncohen** [comment]
I’m good with that. Thank you!

**Comment by webmat** [comment]
#802 👀
