### ISSUE TITLE
[1.5] *.user.id fields missing array definitions

### ISSUE THREAD

**Issue by codebrain** [elastic/ecs#777]
Similar in nature to #776 

It looks as though the following `*.user.id` fields are missing the normalize->array definitions:

- `user.id`
- `client.user.id`
- `destination.user.id`
- `host.user.id`
- `server.user.id`
- `source.user.id`

The descriptions "Unique identifiers of the user." indicates this can contain more than one `id`

**Comment by webmat** [comment]
When introducing the normalize/array pattern, I adjusted a few definitions accordingly. Here "identifiers" is pluralized but it shouldn't.

The `user` field set is currently not meant to correlate IDs from multiple systems, it's meant to capture a single user, as seen in an event.

 So `user.id` is really expected be a single value, it's the definition we need to adjust :-)

**Comment by codebrain** [comment]
OK, let me change this so that we no longer use an array type.
