### ISSUE TITLE
questiom about `package` schema

### ISSUE THREAD

**Issue by neu5ron** [elastic/ecs#778]
Nice work on 1.5.0! I have a quick question about the `package`schema. Could this be used for log sources that have information about software, but thats not `installed` per say? ie: devices that extract files (some would be software) and have information about it. 
Or is this schema specifically reserved for the installed scenarios.

**Comment by webmat** [comment]
Well I'd have a tendency to leave this open to you. If the semantics and fields of the `package` field sets fit your use case, why not use it?

On the other hand, one thing that's important to know about `package` is that it's really tailored to software installed via a package manager, or that can be discovered via a package database. It's not meant to be used for arbitrary software, like if you were to scan `C:\Program Files` for all executables or something.

**Comment by webmat** [comment]
Closing this based on the two emojis ;-)

Please ask future usage questions on https://discuss.elastic.co and tag them `elastic-common-schema`
