### ISSUE TITLE
node not host?

### ISSUE THREAD

**Issue by bsteele1832** [elastic/ecs#806]
The documentation describes the host object as belonging to (general compute resource like a server, physical/virtual or container). Its seems strange then that for the whole of the ECS I can't find anything that stores the metrics of the majority of devices out there like... switches, routers, printers etc... Should the object "host" be made more generic and renamed to "device" or "node" and then have it contain a field called "type" which will state "unknown" or "server", "printer", "ups", "switch", "projector" etc... Either this or rewrite the documentation to make it clear that "host" is also to be used for the other kinds of devices and not just general compute resources.

**Comment by dainperkins** [comment]
hi @bsteele1832 

When referencing metrics from a router/switch/printer etc  host would be the appropriate field.
We could probably make some changes in the docs to reflect that.

host.type could certainly be used for the types you are referencing.

thanks
/d

**Comment by bsteele1832** [comment]
Perfect… thanks 😊

**Comment by webmat** [comment]
Thanks for answering this, @dainperkins.

Looks like the question has been answered.

Please ask future usage questions on https://discuss.elastic.co and tag them `elastic-common-schema` :-)
