### ISSUE TITLE
Cant use ECS host field when host is used in input section of pipeline configuration file

### ISSUE THREAD

**Issue by bsteele1832** [elastic/ecs#807]
If my logstash pipeline configuration file contains the "input" section declaring the "host" IP address then I am prevented from using the ECS "host" object for copying or renaming data to. See the attached file and the reference to "host" on line 3 and then again on line 11. These are two completely different "host" fields but the one on line 11 is trying to use the one declared on line 3. I know this because using data injection I get the following error message:

"error"=>{"type"=>"mapper_parsing_exception", "reason"=>"Could not dynamically add mapping for field [host.model]. **Existing mapping for [host] must be of type object but found [text]**."}}}}

![image](https://user-images.githubusercontent.com/45306600/77676254-fc277800-6f85-11ea-9239-9e2b56f372c5.png)

[camp-sn-inventory.config.txt](https://github.com/elastic/ecs/files/4388709/camp-sn-inventory.config.txt)

**Comment by dainperkins** [comment]
@bsteele1832, if you rename host to e.g. [host][ip] it will then allow you to add additional fields under the [host] object.

Depending on the event I'd consider using [observer][xxx] for ASA records that aren't specifically related to the ASA itself (e.g. ssh sessions, fwsm sessions, etc.)

thanks
/d

**Comment by bsteele1832** [comment]
Thanks,

So are you saying that there is no conflict between the “host” in the input section of the .config file and the “host” field inside ECS? Because I don’t have a problem with any other ECS field and I am able to use them with impunity.

Is your instruction to rename the ECS “host” object not just bypassing the root cause of this problem?


Thanks,
Brian


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by dainperkins** [comment]
No, it's a conflict.... (theres probably a specific programming term - my brain keeps thinking type-casting and then I think of "The Rock")  

As soon as you (or the input section) use host as a text field ( host => "myhost") it can no longer be used as an object  - [host][ip], [host][name].

I know there are some logstash issues opened in terms of on going ECS implementation but I don't have any specifics in terms of this depth of support.

Personally I have a little block of logstash code for a few things that I know every pipeline is likely to need (e.g. rename host -> host.ip, tweak timestamps, etc...)

**Comment by bsteele1832** [comment]
Hi Dain,

I am glad its a conflict because I thought I was going mad. I know what you mean about “The Rock”. I would like to try and guess your thinking of “overrides” after “inheritance” in the hierarchy of Object Oriented Programming perhaps? This would fit as it looks like the “host” in the input section of the .config is overriding the “host” of the ECS?

So... if I perform the rename that you are suggesting then I assume I am renaming the “host” of the input section? Presumable its OK to rename the “host” from the input section during the “filter” section because filter comes after input then therefore the input host is not required anymore. This then reveals the “host” from ECS which I can then use freely?


Regards,
Brian




Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by dainperkins** [comment]
I was thinking a little more basic - like casting a variable as "int" means you can't treat is an an object, but the semantics are buried in the C class I took 30 years ago :)

But yes, in my logstash pipelines (usually syslog based for e.g. ASA, etc) I end up with host as the ip of the sending system, so in the filter I rename it as [host][ip] and everything ends up working the way I want.

I do typically have a type set in the input & an "if type == [whatever type of log I am dealing with]" in the filter (and sometimes in output sections) to make sure I'm not e.g. filtering meraki logs with ASA logic (as a for instance)

/d

**Comment by bsteele1832** [comment]
Sounds great… I will give that a try 😊 By the way, are you from ElasticSearch or another organisation?

Thanks,
Brian

**Comment by dainperkins** [comment]
@bsteele1832 ,

let us know if it works...

I'm an SA @ Elastic

/d

**Comment by bsteele1832** [comment]
Hi Dain,

Sorry for the delay. I will let you know when I test that but I am sure your correct 😊. Also… if I have a Kibana/Canvas question where do I raise those please? I have some very strange things happening ☹


Regards,
Brian

**Comment by dainperkins** [comment]
@bsteele1832 

general question might be better at discuss.elastic.co, or the community slack channel - https://www.elastic.co/blog/join-our-elastic-stack-workspace-on-slack.  I'm going to close this issue out.

**Comment by bsteele1832** [comment]
Hi Dani,

How do I have a conversation with someone to understand your licensing? I want to be able to develop in ElasticStack and sell my solutions and so I need to URGENTLY understand the costs for your licensing and support for myself and the solutions I sell to my customers.

Please arrange for anyone to call me urgently ANYTIME to have this discussion.


Regards,
Brian Steele
07872-622262

SPYDER-LABS (EMEA) limited


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
