### ISSUE TITLE
How to log when one service calls another

### ISSUE THREAD

**Issue by gshively11** [elastic/ecs#825]
I'm having some trouble populating fields in the following situation:

Service A receives a request from a client's browser. Service A then initiates a request to Service B.  When we generate a log from within Service A for the call to Service B, we still want to record all of Service A's metadata in the log along with the metadata related to the request to Service B.

I'm not sure how to populate fields like http, client, server, source, destination, and user in this case, since there seems to be a case for both Service A's and Service B's data to exist there.  I dug through the issues and documentation but didn't find anything that provided guidance on how to handle this situation.

In our homegrown log schema, we would log information for dependencies (outgoing calls from within a service) in a separate section, but I don't see something like that here.

**Comment by ebeahan** [comment]
Hi @gshively11

Have you considered an approaching keeping the events from Service A to Service B independent but leverage a common identifier (e.g. the [`trace.id`](https://www.elastic.co/guide/en/ecs/current/ecs-tracing.html)) field to associate the events with a single transaction?

**Comment by ebeahan** [comment]
ping @simitt - does this sound like what APM is doing or how is APM handling this use case?

**Comment by simitt** [comment]
As suggested by @ebeahan for elastic APM we propagate the `trace.id` to all involved events. We just recently added [`span.id`](https://github.com/elastic/ecs/blob/master/schemas/tracing.yml#L33) to ECS. A span is created for an operation within a transaction, e.g. an outgoing request to another service, or a database query. All events have a `parent.id` set when available to be able to create a waterfall, and if the parent is a `transaction` the `transaction.id` is also set in the event. 

Additional metadata such as service information are only set on a per event document basis, in the example above that would mean `transaction`,`span`,`error` events from clientA only have clientA metadata, serviceA events have serviceA metadata set etc.

**Comment by webmat** [comment]
Another thing to note is that you're correct that ECS doesn't currently offer much for your specific use case.

This should not block you however. You should feel free to capture everything you need in [custom fields](https://www.elastic.co/guide/en/ecs/current/ecs-custom-fields-in-ecs.html), and also populate the ECS fields where things line up.

Doing this lets you move forward exactly as you need. If we ever add equivalent fields, and you've followed the field naming guidance for custom fields linked above; you'll be in a position to adopt the new fields without disruption.

**Comment by gshively11** [comment]
Thanks for chiming in all. We're doing what @webmat suggested and just creating custom fields as needed for now. We'll keep an eye on the schema as new versions are released to see if we can transition to core/extended fields later on.

**Comment by webmat** [comment]
Awesome! And of course if you think you have a set of fields that work well and would like to contribute them to ECS, this is always welcome. It's as simple as opening an issue with details of how you're approaching this :-)
