### ISSUE TITLE
Communication between microservices with rabbitmq

### ISSUE THREAD

**Issue by ohardy** [elastic/ecs#834]
Hi,

I have the impression that there are no fields today concerning this subject.
Anyone can help me regarding that ?

Else we should think about adding some fields about that :)

**Comment by webmat** [comment]
You're right that we don't have anything yet about this.

Out of curiosity, what kind of attributes would you like to capture about these messages?

**Comment by ebeahan** [comment]
@ohardy I'm going to close this issue out, but please feel free to re-open or open an additional issue if you have other questions 😄
