### ISSUE TITLE
Make the ECS tooling able to build the artifacts based on a git ref

### ISSUE THREAD

**Issue by webmat** [elastic/ecs#837]
As we continue to improve the ECS tooling, it's sometimes useful to be able to build based on past versions of ECS. Especially when using the ECS tooling to generate customized artifacts.

Backporting the changes to the tooling to past version branches is time intensive and has very small returns, and is therefore unlikely to happen.

Instead we're considering adding the ability to load ECS schema files as of a specific git ref (tag, branch, or commit).

The format of the schema files has been stable enough that I think we'll be able to use this reliably with at least the most recent versions of ECS.

**Comment by webmat** [comment]
cc @joshdevins

**Comment by marshallmain** [comment]
I can take this issue on as this is a current need for the endpoint team.

**Comment by webmat** [comment]
Yes that would be great, thanks for volunteering for this!

I would recommend keeping the implementation as laser focused as possible on the few functions that actually load the files.

I'm in the process of refactoring and hopefully simplifying the merging of other schemas, setting of defaults, validation & so on. This will touch many parts of the code :-)
