### ISSUE TITLE
Expected locations for url fields in http requests/responses

### ISSUE THREAD

**Issue by vbohata** [elastic/ecs#85]
The docs says URL can be reused in other prefixes. According to #83 it is actually a top level item. As url can be part of both http request and response (in case of redirects), should not docs mentioned this use case if expected to use the url this way? If not what are correct locations for url objects?

**Comment by ruflin** [comment]
This also ties into the discussion here: https://github.com/elastic/ecs/issues/71 If we say all "objects/fields" are reusable we can "indicate" the best places to use them but not document all of them.

If we add it to the http request and response agree that it could be a more straight forward one that would need documentation.

If you add it on the top level or inside each request / response depends on your correlation needs. Do you want to correlate all urls? Put it into the top level field. Only want to correlate responses, use the response url field. If you want both, copy the field also in the top url fields.

**Comment by vbohata** [comment]
OK, thanks.
