### ISSUE TITLE
Numbers in field names

### ISSUE THREAD

**Issue by willemdh** [elastic/ecs#858]
Hello,

I was wondering what's the policy about numbers in field names? I did not found anything related to numbers in https://www.elastic.co/guide/en/ecs/current/ecs-guidelines.html

Grtz

Willem

**Comment by webmat** [comment]
Hey @willemdh, in the future please ask general questions on https://discuss.elastic.co and tag them `elastic-common-schema`. From now on, Github issues should be used specifically to request changes to ECS or report problems.

As for numbers in field names, don't have a set policy around that for now. What did you have in mind? Was this for a potential addition to new fields in ECS? Note that for custom fields, you're free to name your fields exactly how you like.

**Comment by willemdh** [comment]
Sorry @webmat I'll post on the Elastic forums next time first.

About the numbers... The reason is that our company is changing names and our new name contains a number..... Thanks for confirming that should not be an issue. I'm making a custom object with custom organzation specific values...
