### ISSUE TITLE
Tracing fields are inconsistently nested

### ISSUE THREAD

**Issue by percygrunwald** [elastic/ecs#862]
**Description of the issue:**
The "Tracing" fields are inconsistently nested with respect to all other (non-base) ECS fields, as well as between the schema definition and the generated mappings file.

1. With the exception of [Base](https://www.elastic.co/guide/en/ecs/current/ecs-base.html) all children of other field groups are prefixed with something related to the group. E.g. the `name` child of the [Host](https://www.elastic.co/guide/en/ecs/current/ecs-host.html) group is nested under the `host` prefix, such that its fully-qualified name is `host.name`. The fields in the [Tracing](https://www.elastic.co/guide/en/ecs/current/ecs-tracing.html) group do not follow this convention.

2. All schema definitions other than [`base.yml`](https://github.com/elastic/ecs/blob/master/schemas/base.yml) appear to follow the convention of listing the "relative" path to the field (relative to the `name` of the group in the YAML file). E.g. the `md5` item of the `name: hash` group of [`hash.yml`](https://github.com/elastic/ecs/blob/master/schemas/host.yml) is not prefixed with `hash`, but the fully-qualified reference to this field would be `hash.md5`. Following this convention (i.e. expecting the only exception to be the Base group of fields), you would expect the Tracing group of fields to be prefixed with `tracing.` when generating the fully-qualified name. This is also inconsistent with the [generated mapping templates](https://github.com/elastic/ecs/blob/1.5/generated/elasticsearch/7/template.json) for both 1.4 and 1.5.

We find ourselves in a situation where we have generated a whitelist of ECS fields, which allows `tracing.trace.id` and `tracing.transaction.id`, based on the convention of the schema files, but our mapping file does not match. This is really painful.

**Expected behavior:**
The "Tracing" group of fields is prefixed with `tracing.`, or we create 2 new groups: `Trace` and `Transaction` both with `id` fields underneath, which would be consistent with the naming convention.

**Comment by webmat** [comment]
It's true that these two fields are nested differently than most other fields in ECS.

The fields have been named `trace.id` and `transaction.id` for a long time in the Elastic Stack (before ECS). So they're not going to change. What needs to change is how the ECS documentation presents this, in order for this to be clearer.

At the time we added them to ECS, the thought creating two field sets with only a single "id" field was too heavy-handed. So instead we created this "tracing" field set, and we hacked the same mechanism used by base fields to have these fields not nested under `tracing.`.

Here are my thoughts on the current state of things. In most places the information is correct, but in some places we can make this more obvious that there's shenanigans going on:

Correct:

* The fields as listed on the [tracing page](https://www.elastic.co/guide/en/ecs/current/ecs-tracing.html) do state the full field names (just like anywhere else) and they are listed as `trace.id` and `transaction.id`.
* [generated/ecs/fields.csv](https://github.com/elastic/ecs/blob/master/generated/csv/fields.csv) lists them as `trace.id` and `transaction.id`.
* The ES templates in [generated/elasticsearch](https://github.com/elastic/ecs/blob/master/generated/elasticsearch) have them as `trace.id` and `transaction.id`.
* For anyone looking to build on top of ECS programmatically, the files to use are in [generated/ecs](https://github.com/elastic/ecs/tree/master/generated/ecs) (not in `schemas/`). Those files have all defaults made explicit, and a bunch of precalculated values like the attribute `flat_name` which do correctly capture the final field name, after considering field reuse, or whether or not fields are namespaced under their field set name.

Where we can do better:

My assumption is that you're building off of the files in `schemas/*.yml`? That's one of the things I think we need to improve. This is a common mistake. It's where contributors are meant to make modifications to ECS fields, so they're the best known files.

But for anyone looking to build on top of ECS programmatically, the two files to use are in [generated/ecs](https://github.com/elastic/ecs/tree/master/generated/ecs), not in `schemas/`. These files have all defaults made explicit, they have a bunch of precalculated values like the attribute `flat_name` which do correctly capture the final field name. There's lots of complexities around field reuse, and whether or not fields are namespaced under their field set name etc.

So making these files more discoverable and better documenting them would be one major thing we can address here.

Another simple thing we could do is add a standard warning to the docs for any field set that have attribute `root=true` (which means not namespaced under the fieldset name). Perhaps a warning block between the main description of the field set and the list of fields similar to this:

Base fields:

> Attention: The fields of the "base" field set are not nested under the namespace "base."

Tracing fields:

> Attention: The fields of the "tracing" field set are not nested under the namespace "tracing."

Do you think these two improvements would help?

And where do you think would be the best place to make the [generated/ecs](https://github.com/elastic/ecs/tree/master/generated/ecs) files more discoverable?

**Comment by ebeahan** [comment]
Please feel free to re-open if there's any additional thoughts, but I'm going to close for now.
