### ISSUE TITLE
Add `--artifacts` option for `generator.py`

### ISSUE THREAD

**Issue by ebeahan** [elastic/ecs#885]
#873 included discussion for adding an `--artifacts` option to `generator.py` to specify which artifacts are generated in the script's output, and I agree this would be a useful addition.

**Examples:**

Current behavior with customizations: `--artifacts csv,beats,intermediate`
Exclude `csv`: `--artifacts beats,intermediate`

This feature won't consider handling `asciidoc` doc generation for custom artifacts as part of its available outputs.

**Comment by webmat** [comment]
Closing, as many artifacts require multiple files and subdirectories.

Folks should .gitignore what they don't need, and optionally move files from a temp output directory to wherever they want.
