### ISSUE TITLE
Align input options for `--include` and `--subset` arguments

### ISSUE THREAD

**Issue by ebeahan** [elastic/ecs#899]
#### Summary

There is inconsistency between the expected inputs for the `--include` and `--subset` arguments:

`--include`: Expects a single directory containing the YAML schema files
`--subset`: Expects a single subset definition YAML file. Will accept a directory but execution fails with an exception.

#### Proposal

The documentation (#893) has been improved to clarify, but the difference does cause confusions for users (#843). Propose adjusting each feature to accept both individual files or directories as valid inputs.

**Comment by djptek** [comment]
@ebeahan can I take this one?

**Comment by ebeahan** [comment]
@djptek Absolutely!

**Comment by djptek** [comment]
PR submitted https://github.com/elastic/ecs/pull/1519

**Comment by ebeahan** [comment]
Resolved via #1519
