### ISSUE TITLE
64-bit unsigned integer field type usage 

### ISSUE THREAD

**Issue by ebeahan** [elastic/ecs#900]
#### Summary

Starting a discussion of the upcoming uint64 data type and its possible application in ECS once released. Looking to collect high-level thoughts and feedback, with the outcomes consolidated into a RFC stage 0 proposal if the concept has interest.

#### Identified potential uses:

* in the `registry.*` field set #673 
* the Windows [`FILETIME` struct](https://docs.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-filetime)
* Windows [USN Journal](https://github.com/elastic/elasticsearch/issues/17006#issuecomment-252318741)
* additional fields from [endpoint](https://github.com/elastic/elasticsearch/issues/32434#issuecomment-573843862).

#### References

Elasticsearch issue for adding uint64 integers: elastic/elasticsearch#32434
in-progress PR: elastic/elasticsearch#60050

**Comment by dainperkins** [comment]
would be useful for 64bit counters (e.g. ifxmibs bytes_in,etc)

**Comment by ebeahan** [comment]
I investigated this a bit more recently as a possible upcoming change to ECS.

With 64-bit integers not supported in Javascript, Kibana has several known issues with 64-bit integer support: https://github.com/elastic/kibana/issues/40183. 

May still guide those ECS users who require the additional precision and understand the possible side-effects and degraded experience in exchange for it.

**Comment by ebeahan** [comment]
Not pursuing in the near future.
