### ISSUE TITLE
Improve documentation to ensure source/destination are populated as a priority

### ISSUE THREAD

**Issue by webmat** [elastic/ecs#948]
The definition of the Client & Server field sets are pretty extensive, whereas Source & Destination's definitions are pretty bare.

We've been encouraging people to populate source & destination as a baseline, and client & server only when relevant or helpful. Elastic Security mostly considers source & destination.

However the ECS documentation doesn't make that obvious. There's only a vague mention about prioritizing source/destination in the client/server definitions. No mention of this in source/destination.

- [x] #967 We should expand the definitions of the source & destination field sets to clearly state that they are the baseline, compared to client & server.
- [x] #969 We could also consider having a standalone documentation page that talks about capturing network related events holistically. It could cover:
  - the src/dst baseline, and showcase when cli/srv are useful (e.g. DNS)
  - it could discuss populating the `network.*` fields
  - it could discuss how `event.category:network` + `event.type:protocol` should always come with `network.protocol:[appropriate protocol name]`. Most category/type pairs are complete on their own. But not the pair network/protocol; it should come with `network.protocol`.

**Comment by ebeahan** [comment]
> We could also consider having a standalone documentation page that talks about capturing network related events holistically

++ I think this makes a lot of sense to capture this and in the future other ECS design patterns.

**Comment by ebeahan** [comment]
@jamesmotherway I've opened https://github.com/elastic/ecs/pull/967 aiming to address the first bullet point, if you have any feedback there.

**Comment by ebeahan** [comment]
Closing as #967 and #969 have both been merged 🎉
