### ISSUE TITLE
ECS Schema Management

### ISSUE THREAD

**Issue by robgil** [elastic/ecs#95]
Conceptually, managing schemas needs to be better defined. From an operational perspective, we're essentially managing multiple index patterns for the same index.

For example, we'll have `ECS Core`, `ECS Extended`, and `ECS Applications`. We need to define a good way, and/or create a tool to create a full index someone would use for particular use cases. Creating index templates can be complicated and frustrating. Anything we can do to make that easier for folks will increase adoption.

For example, we can have a simple python tool that allows you to pass in the schemas you want in your index, and spit out the schema.

`./schema.py --generate ecs ecs-e memcached`

This would compile the `Elastic Common Schema`, the `Extended Elastic Common Schema`, and an application specific `Memcached` schema. The `Memcached` schema would cover anything unique to `Memcached`. 

Once we have our schema generated, it would be nice to apply it somewhere.

`./schema.py --generate ecs ecs-e memcached --index-pattern 'mylogs-*' --template-name mylogs -H <ES Host> -u <user> -p <pass>`

This would generate the combined schema and add the `"template": "mylogs-*"` to the index template. It would also then add the template to the ES host defined.

Example curl
```
url --user '<user>:<pass>' -X PUT -d@<my-combined-schema>.json -H 'Content-Type: application/json' https://<ES Host>:9243/_template/mylogs
```

I expect that this would be used most often by OSS users, but schema management will probably find its way in to ECE.

**Comment by ruflin** [comment]
Assuming we have a template for `core` and `extended` it would mean they are both applied to the same index? And we would use `order` to set their priority? @clintongormley Will we be able to use `order` in the long run?

**Comment by robgil** [comment]
Agree with all points so far. I thought the order would be explicit in that core would always come first, then extended, then application. Since its a unified schema, I don't think it should really matter what order it is because none of the fields should overlap anyway. It should just be a simple merge. We should have some kind of validation when new schemas are PRd that they are not introducing fields that already exist in core/extended.

**Comment by webmat** [comment]
See #497 for a concrete plan
