### ISSUE TITLE
Adding event.transaction.id

### ISSUE THREAD

**Issue by vbohata** [elastic/ecs#96]
For some events I need to track their transaction/session or correlation ids. I think there should be a new field event.transaction.id for this use case.

**Comment by ruflin** [comment]
I think we can take inspiration here from apm: https://github.com/elastic/apm-server/blob/master/_meta/fields.common.yml#L266

Here it is `transaction.id`, I would not nest it under event.

**Comment by ebeahan** [comment]
ECS now contains the [`transaction.id`](https://www.elastic.co/guide/en/ecs/current/ecs-tracing.html#field-transaction-id) field.

There's some recent conversation taking place around introducing a `session.id` field in the [session RFC](https://github.com/elastic/ecs/blob/master/rfcs/text/0004-session.md) to associate multiple events together based on a common session identifier.
